"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from hackarena3.proto.hackarena.platform.common.v1 import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class User(_message.Message):
    """Normalized platform user."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    EMAIL_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    ROLES_FIELD_NUMBER: _builtins.int
    LOCALE_FIELD_NUMBER: _builtins.int
    ISSUER_FIELD_NUMBER: _builtins.int
    PREFERRED_USERNAME_FIELD_NUMBER: _builtins.int
    email: _builtins.str
    """Primary email, if available."""
    display_name: _builtins.str
    """Display name."""
    locale: _builtins.str
    """Locale, if available."""
    issuer: _builtins.str
    """Issuer identifier."""
    preferred_username: _builtins.str
    """Username-like identifier."""
    @_builtins.property
    def id(self) -> _types_pb2.Uuid:
        """User identifier."""

    @_builtins.property
    def roles(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Platform roles."""

    def __init__(
        self,
        *,
        id: _types_pb2.Uuid | None = ...,
        email: _builtins.str = ...,
        display_name: _builtins.str = ...,
        roles: _abc.Iterable[_builtins.str] | None = ...,
        locale: _builtins.str = ...,
        issuer: _builtins.str = ...,
        preferred_username: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["display_name", b"display_name", "email", b"email", "id", b"id", "issuer", b"issuer", "locale", b"locale", "preferred_username", b"preferred_username", "roles", b"roles"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___User: _TypeAlias = User  # noqa: Y015

@_typing.final
class GetMeRequest(_message.Message):
    """Empty request; identity inferred from auth context."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetMeRequest: _TypeAlias = GetMeRequest  # noqa: Y015

@_typing.final
class GetMeResponse(_message.Message):
    """GetMe response."""

    DESCRIPTOR: _descriptor.Descriptor

    ME_FIELD_NUMBER: _builtins.int
    EXPIRES_AT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def me(self) -> Global___User:
        """Current user."""

    @_builtins.property
    def expires_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        me: Global___User | None = ...,
        expires_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["expires_at", b"expires_at", "me", b"me"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expires_at", b"expires_at", "me", b"me"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetMeResponse: _TypeAlias = GetMeResponse  # noqa: Y015
