"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Uuid(_message.Message):
    """UUID wrapper for consistent IDs."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    """Canonical UUID string."""
    def __init__(
        self,
        *,
        value: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Uuid: _TypeAlias = Uuid  # noqa: Y015

@_typing.final
class PageRequest(_message.Message):
    """Pagination request parameters."""

    DESCRIPTOR: _descriptor.Descriptor

    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    page_size: _builtins.int
    """Max items to return."""
    page_token: _builtins.str
    """Opaque continuation token."""
    def __init__(
        self,
        *,
        page_size: _builtins.int = ...,
        page_token: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page_size", b"page_size", "page_token", b"page_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PageRequest: _TypeAlias = PageRequest  # noqa: Y015

@_typing.final
class PageResponse(_message.Message):
    """Pagination response metadata."""

    DESCRIPTOR: _descriptor.Descriptor

    NEXT_PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    next_page_token: _builtins.str
    """Token for the next page, if any."""
    def __init__(
        self,
        *,
        next_page_token: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["next_page_token", b"next_page_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PageResponse: _TypeAlias = PageResponse  # noqa: Y015
