# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hackarena/platform/common/v1/types.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'hackarena/platform/common/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(hackarena/platform/common/v1/types.proto\x12\x1chackarena.platform.common.v1\"\"\n\x04Uuid\x12\x14\n\x05value\x18\x01 \x01(\tR\x05valueJ\x04\x08\x02\x10\x64\"O\n\x0bPageRequest\x12\x1b\n\tpage_size\x18\x01 \x01(\rR\x08pageSize\x12\x1d\n\npage_token\x18\x02 \x01(\tR\tpageTokenJ\x04\x08\x03\x10\x32\"<\n\x0cPageResponse\x12&\n\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageTokenJ\x04\x08\x02\x10\x32\x42\x1f\xaa\x02\x1cHackArena.Platform.Common.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hackarena.platform.common.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034HackArena.Platform.Common.V1'
  _globals['_UUID']._serialized_start=74
  _globals['_UUID']._serialized_end=108
  _globals['_PAGEREQUEST']._serialized_start=110
  _globals['_PAGEREQUEST']._serialized_end=189
  _globals['_PAGERESPONSE']._serialized_start=191
  _globals['_PAGERESPONSE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
