from hackarena3.types import (
    BotContext,
    BotProtocol,
    CarDimensions,
    CarState,
    CenterlinePoint,
    CommandCooldownState,
    Controls,
    DriveGear,
    GhostModeBlocker,
    GhostModePhase,
    GroundType,
    GroundWidth,
    GhostModeState,
    GearShift,
    OpponentState,
    PitEntrySource,
    PitstopLayout,
    PitstopZoneFlag,
    Quaternion,
    RaceSnapshot,
    RuntimeConfig,
    TireSlipPerWheel,
    TireTemperaturePerWheel,
    TireType,
    TireWearPerWheel,
    TrackLayout,
    Vec3,
)


def run_bot(bot: BotProtocol, config: RuntimeConfig | None = None) -> int:
    from hackarena3.client import run_bot as _run_bot

    return _run_bot(bot=bot, config=config)


__all__ = [
    "BotContext",
    "BotProtocol",
    "CarDimensions",
    "CarState",
    "CenterlinePoint",
    "CommandCooldownState",
    "Controls",
    "DriveGear",
    "GhostModeBlocker",
    "GhostModePhase",
    "GroundType",
    "GroundWidth",
    "GhostModeState",
    "GearShift",
    "OpponentState",
    "PitEntrySource",
    "PitstopLayout",
    "PitstopZoneFlag",
    "Quaternion",
    "RaceSnapshot",
    "RuntimeConfig",
    "TireSlipPerWheel",
    "TireTemperaturePerWheel",
    "TireType",
    "TireWearPerWheel",
    "TrackLayout",
    "Vec3",
    "run_bot",
]
