# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hackarena3.proto.achievement.v1 import achievement_public_pb2 as achievement_dot_v1_dot_achievement__public__pb2


class AchievementServiceStub(object):
    """Api for achievement fetching.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAchievements = channel.unary_unary(
                '/achievement.v1.AchievementService/GetAchievements',
                request_serializer=achievement_dot_v1_dot_achievement__public__pb2.GetAchievementsRequest.SerializeToString,
                response_deserializer=achievement_dot_v1_dot_achievement__public__pb2.GetAchievementsResponse.FromString,
                _registered_method=True)
        self.GetAchievementTotals = channel.unary_unary(
                '/achievement.v1.AchievementService/GetAchievementTotals',
                request_serializer=achievement_dot_v1_dot_achievement__public__pb2.GetAchievementTotalsRequest.SerializeToString,
                response_deserializer=achievement_dot_v1_dot_achievement__public__pb2.GetAchievementTotalsResponse.FromString,
                _registered_method=True)
        self.StreamAchievementGrants = channel.unary_stream(
                '/achievement.v1.AchievementService/StreamAchievementGrants',
                request_serializer=achievement_dot_v1_dot_achievement__public__pb2.StreamAchievementGrantsRequest.SerializeToString,
                response_deserializer=achievement_dot_v1_dot_achievement__public__pb2.StreamAchievementGrantsResponse.FromString,
                _registered_method=True)


class AchievementServiceServicer(object):
    """Api for achievement fetching.
    """

    def GetAchievements(self, request, context):
        """Gets all achievements for specific team_id.
        Returns both achieved and not achieved achievements.
        Secret achievement are hidden until achieved.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAchievementTotals(self, request, context):
        """Get how many achievements each team has.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAchievementGrants(self, request, context):
        """Global stream of achievement grant events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AchievementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAchievements': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAchievements,
                    request_deserializer=achievement_dot_v1_dot_achievement__public__pb2.GetAchievementsRequest.FromString,
                    response_serializer=achievement_dot_v1_dot_achievement__public__pb2.GetAchievementsResponse.SerializeToString,
            ),
            'GetAchievementTotals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAchievementTotals,
                    request_deserializer=achievement_dot_v1_dot_achievement__public__pb2.GetAchievementTotalsRequest.FromString,
                    response_serializer=achievement_dot_v1_dot_achievement__public__pb2.GetAchievementTotalsResponse.SerializeToString,
            ),
            'StreamAchievementGrants': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAchievementGrants,
                    request_deserializer=achievement_dot_v1_dot_achievement__public__pb2.StreamAchievementGrantsRequest.FromString,
                    response_serializer=achievement_dot_v1_dot_achievement__public__pb2.StreamAchievementGrantsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'achievement.v1.AchievementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('achievement.v1.AchievementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AchievementService(object):
    """Api for achievement fetching.
    """

    @staticmethod
    def GetAchievements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/achievement.v1.AchievementService/GetAchievements',
            achievement_dot_v1_dot_achievement__public__pb2.GetAchievementsRequest.SerializeToString,
            achievement_dot_v1_dot_achievement__public__pb2.GetAchievementsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAchievementTotals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/achievement.v1.AchievementService/GetAchievementTotals',
            achievement_dot_v1_dot_achievement__public__pb2.GetAchievementTotalsRequest.SerializeToString,
            achievement_dot_v1_dot_achievement__public__pb2.GetAchievementTotalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAchievementGrants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/achievement.v1.AchievementService/StreamAchievementGrants',
            achievement_dot_v1_dot_achievement__public__pb2.StreamAchievementGrantsRequest.SerializeToString,
            achievement_dot_v1_dot_achievement__public__pb2.StreamAchievementGrantsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
