# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: achievement/v1/achievement_public.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'achievement/v1/achievement_public.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hackarena3.proto.achievement.v1 import achievement_types_pb2 as achievement_dot_v1_dot_achievement__types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'achievement/v1/achievement_public.proto\x12\x0e\x61\x63hievement.v1\x1a&achievement/v1/achievement_types.proto\"\xd5\x01\n\x19\x41\x63hievementRepresentation\x12X\n\x0b\x63onditional\x18\x01 \x01(\x0b\x32\x34.achievement.v1.ConditionalAchievementRepresentationH\x00R\x0b\x63onditional\x12L\n\x07numeric\x18\x02 \x01(\x0b\x32\x30.achievement.v1.NumericAchievementRepresentationH\x00R\x07numericB\x10\n\x0erepresentation\"1\n\x16GetAchievementsRequest\x12\x17\n\x07team_id\x18\x01 \x01(\tR\x06teamId\"\xac\x01\n\x17GetAchievementsResponse\x12\x42\n\x1dremaining_secret_achievements\x18\x01 \x01(\x05R\x1bremainingSecretAchievements\x12M\n\x0c\x61\x63hievements\x18\x02 \x03(\x0b\x32).achievement.v1.AchievementRepresentationR\x0c\x61\x63hievements2x\n\x12\x41\x63hievementService\x12\x62\n\x0fGetAchievements\x12&.achievement.v1.GetAchievementsRequest\x1a\'.achievement.v1.GetAchievementsResponseB\x1b\xaa\x02\x18HA3.Proto.Achievement.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'achievement.v1.achievement_public_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\030HA3.Proto.Achievement.V1'
  _globals['_ACHIEVEMENTREPRESENTATION']._serialized_start=100
  _globals['_ACHIEVEMENTREPRESENTATION']._serialized_end=313
  _globals['_GETACHIEVEMENTSREQUEST']._serialized_start=315
  _globals['_GETACHIEVEMENTSREQUEST']._serialized_end=364
  _globals['_GETACHIEVEMENTSRESPONSE']._serialized_start=367
  _globals['_GETACHIEVEMENTSRESPONSE']._serialized_end=539
  _globals['_ACHIEVEMENTSERVICE']._serialized_start=541
  _globals['_ACHIEVEMENTSERVICE']._serialized_end=661
# @@protoc_insertion_point(module_scope)
