# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hackarena3.proto.achievement.v1 import achievement_admin_pb2 as achievement_dot_v1_dot_achievement__admin__pb2


class AchievementServiceAdminStub(object):
    """Service definition for administrative actions related to achievements.
    This service provides methods for managing achievements, such as granting,
    refusing, and updating their display information.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GrantAchievement = channel.unary_unary(
                '/achievement.v1.AchievementServiceAdmin/GrantAchievement',
                request_serializer=achievement_dot_v1_dot_achievement__admin__pb2.GrantAchievementRequest.SerializeToString,
                response_deserializer=achievement_dot_v1_dot_achievement__admin__pb2.GrantAchievementResponse.FromString,
                _registered_method=True)
        self.RefuseAchievement = channel.unary_unary(
                '/achievement.v1.AchievementServiceAdmin/RefuseAchievement',
                request_serializer=achievement_dot_v1_dot_achievement__admin__pb2.RefuseAchievementRequest.SerializeToString,
                response_deserializer=achievement_dot_v1_dot_achievement__admin__pb2.RefuseAchievementResponse.FromString,
                _registered_method=True)
        self.GetAchievementDisplays = channel.unary_unary(
                '/achievement.v1.AchievementServiceAdmin/GetAchievementDisplays',
                request_serializer=achievement_dot_v1_dot_achievement__admin__pb2.GetAchievementDisplaysRequest.SerializeToString,
                response_deserializer=achievement_dot_v1_dot_achievement__admin__pb2.GetAchievementDisplaysResponse.FromString,
                _registered_method=True)
        self.UpdateAchievementDisplay = channel.unary_unary(
                '/achievement.v1.AchievementServiceAdmin/UpdateAchievementDisplay',
                request_serializer=achievement_dot_v1_dot_achievement__admin__pb2.UpdateAchievementDisplayRequest.SerializeToString,
                response_deserializer=achievement_dot_v1_dot_achievement__admin__pb2.UpdateAchievementDisplayResponse.FromString,
                _registered_method=True)


class AchievementServiceAdminServicer(object):
    """Service definition for administrative actions related to achievements.
    This service provides methods for managing achievements, such as granting,
    refusing, and updating their display information.
    """

    def GrantAchievement(self, request, context):
        """Grants a specific achievement to a team.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefuseAchievement(self, request, context):
        """Refuses (or revokes) a specific achievement for a team.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAchievementDisplays(self, request, context):
        """Retrieves display information (e.g., name, description, icon) for all available achievements.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAchievementDisplay(self, request, context):
        """Updates the display information for a specific achievement.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AchievementServiceAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GrantAchievement': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantAchievement,
                    request_deserializer=achievement_dot_v1_dot_achievement__admin__pb2.GrantAchievementRequest.FromString,
                    response_serializer=achievement_dot_v1_dot_achievement__admin__pb2.GrantAchievementResponse.SerializeToString,
            ),
            'RefuseAchievement': grpc.unary_unary_rpc_method_handler(
                    servicer.RefuseAchievement,
                    request_deserializer=achievement_dot_v1_dot_achievement__admin__pb2.RefuseAchievementRequest.FromString,
                    response_serializer=achievement_dot_v1_dot_achievement__admin__pb2.RefuseAchievementResponse.SerializeToString,
            ),
            'GetAchievementDisplays': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAchievementDisplays,
                    request_deserializer=achievement_dot_v1_dot_achievement__admin__pb2.GetAchievementDisplaysRequest.FromString,
                    response_serializer=achievement_dot_v1_dot_achievement__admin__pb2.GetAchievementDisplaysResponse.SerializeToString,
            ),
            'UpdateAchievementDisplay': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAchievementDisplay,
                    request_deserializer=achievement_dot_v1_dot_achievement__admin__pb2.UpdateAchievementDisplayRequest.FromString,
                    response_serializer=achievement_dot_v1_dot_achievement__admin__pb2.UpdateAchievementDisplayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'achievement.v1.AchievementServiceAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('achievement.v1.AchievementServiceAdmin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AchievementServiceAdmin(object):
    """Service definition for administrative actions related to achievements.
    This service provides methods for managing achievements, such as granting,
    refusing, and updating their display information.
    """

    @staticmethod
    def GrantAchievement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/achievement.v1.AchievementServiceAdmin/GrantAchievement',
            achievement_dot_v1_dot_achievement__admin__pb2.GrantAchievementRequest.SerializeToString,
            achievement_dot_v1_dot_achievement__admin__pb2.GrantAchievementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefuseAchievement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/achievement.v1.AchievementServiceAdmin/RefuseAchievement',
            achievement_dot_v1_dot_achievement__admin__pb2.RefuseAchievementRequest.SerializeToString,
            achievement_dot_v1_dot_achievement__admin__pb2.RefuseAchievementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAchievementDisplays(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/achievement.v1.AchievementServiceAdmin/GetAchievementDisplays',
            achievement_dot_v1_dot_achievement__admin__pb2.GetAchievementDisplaysRequest.SerializeToString,
            achievement_dot_v1_dot_achievement__admin__pb2.GetAchievementDisplaysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAchievementDisplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/achievement.v1.AchievementServiceAdmin/UpdateAchievementDisplay',
            achievement_dot_v1_dot_achievement__admin__pb2.UpdateAchievementDisplayRequest.SerializeToString,
            achievement_dot_v1_dot_achievement__admin__pb2.UpdateAchievementDisplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
