"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from hackarena3.proto.achievement.v1 import achievement_types_pb2 as _achievement_types_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _GrantAchievementReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _GrantAchievementReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GrantAchievementReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GRANT_ACHIEVEMENT_REASON_UNSPECIFIED: _GrantAchievementReason.ValueType  # 0
    GRANT_ACHIEVEMENT_REASON_NONE: _GrantAchievementReason.ValueType  # 1
    GRANT_ACHIEVEMENT_REASON_NO_TEAM: _GrantAchievementReason.ValueType  # 2
    GRANT_ACHIEVEMENT_REASON_NO_ACHIEVEMENT: _GrantAchievementReason.ValueType  # 3
    GRANT_ACHIEVEMENT_REASON_ALREADY_GRANTED: _GrantAchievementReason.ValueType  # 4

class GrantAchievementReason(_GrantAchievementReason, metaclass=_GrantAchievementReasonEnumTypeWrapper): ...

GRANT_ACHIEVEMENT_REASON_UNSPECIFIED: GrantAchievementReason.ValueType  # 0
GRANT_ACHIEVEMENT_REASON_NONE: GrantAchievementReason.ValueType  # 1
GRANT_ACHIEVEMENT_REASON_NO_TEAM: GrantAchievementReason.ValueType  # 2
GRANT_ACHIEVEMENT_REASON_NO_ACHIEVEMENT: GrantAchievementReason.ValueType  # 3
GRANT_ACHIEVEMENT_REASON_ALREADY_GRANTED: GrantAchievementReason.ValueType  # 4
Global___GrantAchievementReason: _TypeAlias = GrantAchievementReason  # noqa: Y015

class _RefuseAchievementReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RefuseAchievementReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RefuseAchievementReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    REFUSE_ACHIEVEMENT_REASON_UNSPECIFIED: _RefuseAchievementReason.ValueType  # 0
    REFUSE_ACHIEVEMENT_REASON_NONE: _RefuseAchievementReason.ValueType  # 1
    REFUSE_ACHIEVEMENT_REASON_NO_TEAM: _RefuseAchievementReason.ValueType  # 2
    REFUSE_ACHIEVEMENT_REASON_NO_ACHIEVEMENT: _RefuseAchievementReason.ValueType  # 3
    REFUSE_ACHIEVEMENT_REASON_ALREADY_REFUSED: _RefuseAchievementReason.ValueType  # 4

class RefuseAchievementReason(_RefuseAchievementReason, metaclass=_RefuseAchievementReasonEnumTypeWrapper): ...

REFUSE_ACHIEVEMENT_REASON_UNSPECIFIED: RefuseAchievementReason.ValueType  # 0
REFUSE_ACHIEVEMENT_REASON_NONE: RefuseAchievementReason.ValueType  # 1
REFUSE_ACHIEVEMENT_REASON_NO_TEAM: RefuseAchievementReason.ValueType  # 2
REFUSE_ACHIEVEMENT_REASON_NO_ACHIEVEMENT: RefuseAchievementReason.ValueType  # 3
REFUSE_ACHIEVEMENT_REASON_ALREADY_REFUSED: RefuseAchievementReason.ValueType  # 4
Global___RefuseAchievementReason: _TypeAlias = RefuseAchievementReason  # noqa: Y015

class _UpdateAchievementDisplayReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _UpdateAchievementDisplayReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_UpdateAchievementDisplayReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UPDATE_ACHIEVEMENT_DISPLAY_REASON_UNSPECIFIED: _UpdateAchievementDisplayReason.ValueType  # 0
    UPDATE_ACHIEVEMENT_DISPLAY_REASON_NONE: _UpdateAchievementDisplayReason.ValueType  # 1
    UPDATE_ACHIEVEMENT_DISPLAY_REASON_NO_ACHIEVEMENT: _UpdateAchievementDisplayReason.ValueType  # 2

class UpdateAchievementDisplayReason(_UpdateAchievementDisplayReason, metaclass=_UpdateAchievementDisplayReasonEnumTypeWrapper): ...

UPDATE_ACHIEVEMENT_DISPLAY_REASON_UNSPECIFIED: UpdateAchievementDisplayReason.ValueType  # 0
UPDATE_ACHIEVEMENT_DISPLAY_REASON_NONE: UpdateAchievementDisplayReason.ValueType  # 1
UPDATE_ACHIEVEMENT_DISPLAY_REASON_NO_ACHIEVEMENT: UpdateAchievementDisplayReason.ValueType  # 2
Global___UpdateAchievementDisplayReason: _TypeAlias = UpdateAchievementDisplayReason  # noqa: Y015

@_typing.final
class GrantAchievementRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEAM_ID_FIELD_NUMBER: _builtins.int
    ACHIEVEMENT_ID_FIELD_NUMBER: _builtins.int
    team_id: _builtins.str
    achievement_id: _builtins.str
    def __init__(
        self,
        *,
        team_id: _builtins.str = ...,
        achievement_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["achievement_id", b"achievement_id", "team_id", b"team_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GrantAchievementRequest: _TypeAlias = GrantAchievementRequest  # noqa: Y015

@_typing.final
class GrantAchievementResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IS_GRANTED_SUCCESSFULLY_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    is_granted_successfully: _builtins.bool
    reason: Global___GrantAchievementReason.ValueType
    def __init__(
        self,
        *,
        is_granted_successfully: _builtins.bool = ...,
        reason: Global___GrantAchievementReason.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_granted_successfully", b"is_granted_successfully", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GrantAchievementResponse: _TypeAlias = GrantAchievementResponse  # noqa: Y015

@_typing.final
class RefuseAchievementRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEAM_ID_FIELD_NUMBER: _builtins.int
    ACHIEVEMENT_ID_FIELD_NUMBER: _builtins.int
    team_id: _builtins.str
    achievement_id: _builtins.str
    def __init__(
        self,
        *,
        team_id: _builtins.str = ...,
        achievement_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["achievement_id", b"achievement_id", "team_id", b"team_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RefuseAchievementRequest: _TypeAlias = RefuseAchievementRequest  # noqa: Y015

@_typing.final
class RefuseAchievementResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IS_REFUSED_SUCCESSFULLY_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    is_refused_successfully: _builtins.bool
    reason: Global___RefuseAchievementReason.ValueType
    def __init__(
        self,
        *,
        is_refused_successfully: _builtins.bool = ...,
        reason: Global___RefuseAchievementReason.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_refused_successfully", b"is_refused_successfully", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RefuseAchievementResponse: _TypeAlias = RefuseAchievementResponse  # noqa: Y015

@_typing.final
class GetAchievementDisplaysRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetAchievementDisplaysRequest: _TypeAlias = GetAchievementDisplaysRequest  # noqa: Y015

@_typing.final
class GetAchievementDisplaysResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DISPLAYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def displays(self) -> _containers.RepeatedCompositeFieldContainer[_achievement_types_pb2.AchievementDisplay]: ...
    def __init__(
        self,
        *,
        displays: _abc.Iterable[_achievement_types_pb2.AchievementDisplay] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["displays", b"displays"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetAchievementDisplaysResponse: _TypeAlias = GetAchievementDisplaysResponse  # noqa: Y015

@_typing.final
class UpdateAchievementDisplayRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACHIEVEMENT_ID_FIELD_NUMBER: _builtins.int
    NEW_ACHIEVEMENT_DISPLAY_FIELD_NUMBER: _builtins.int
    achievement_id: _builtins.str
    @_builtins.property
    def new_achievement_display(self) -> _achievement_types_pb2.NewAchievementDisplay: ...
    def __init__(
        self,
        *,
        achievement_id: _builtins.str = ...,
        new_achievement_display: _achievement_types_pb2.NewAchievementDisplay | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["new_achievement_display", b"new_achievement_display"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["achievement_id", b"achievement_id", "new_achievement_display", b"new_achievement_display"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateAchievementDisplayRequest: _TypeAlias = UpdateAchievementDisplayRequest  # noqa: Y015

@_typing.final
class UpdateAchievementDisplayResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IS_UPDATED_SUCCESSFULLY_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    is_updated_successfully: _builtins.bool
    reason: Global___UpdateAchievementDisplayReason.ValueType
    def __init__(
        self,
        *,
        is_updated_successfully: _builtins.bool = ...,
        reason: Global___UpdateAchievementDisplayReason.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["is_updated_successfully", b"is_updated_successfully", "reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateAchievementDisplayResponse: _TypeAlias = UpdateAchievementDisplayResponse  # noqa: Y015
