# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hackarena3.proto.auth.v1 import game_token_issuer_pb2 as auth_dot_v1_dot_game__token__issuer__pb2


class GameTokenIssuerServiceStub(object):
    """Auth API for issuing game tokens.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueGameToken = channel.unary_unary(
                '/auth.v1.GameTokenIssuerService/IssueGameToken',
                request_serializer=auth_dot_v1_dot_game__token__issuer__pb2.IssueGameTokenRequest.SerializeToString,
                response_deserializer=auth_dot_v1_dot_game__token__issuer__pb2.IssueGameTokenResponse.FromString,
                _registered_method=True)


class GameTokenIssuerServiceServicer(object):
    """Auth API for issuing game tokens.
    """

    def IssueGameToken(self, request, context):
        """Issues requested game token for HA3.
        Context resolution rules:
        - user_id comes from verified auth transport context.
        - for team token types, server resolves HA3 team_id for user.
        - exactly one HA3 team is required for team token types.
        - for TEAM_BOT_DEV, server generates random instance_uuid per issued token.
        Expected errors:
        - UNAUTHENTICATED: missing or invalid auth context.
        - INVALID_ARGUMENT: token_type is UNSPECIFIED.
        - FAILED_PRECONDITION: team token requested and HA3 team lookup returns 0 or >1 teams.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameTokenIssuerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueGameToken': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueGameToken,
                    request_deserializer=auth_dot_v1_dot_game__token__issuer__pb2.IssueGameTokenRequest.FromString,
                    response_serializer=auth_dot_v1_dot_game__token__issuer__pb2.IssueGameTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.v1.GameTokenIssuerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.v1.GameTokenIssuerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameTokenIssuerService(object):
    """Auth API for issuing game tokens.
    """

    @staticmethod
    def IssueGameToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.GameTokenIssuerService/IssueGameToken',
            auth_dot_v1_dot_game__token__issuer__pb2.IssueGameTokenRequest.SerializeToString,
            auth_dot_v1_dot_game__token__issuer__pb2.IssueGameTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
