# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/game_token_issuer.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'auth/v1/game_token_issuer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hackarena3.proto.auth.v1 import game_token_pb2 as auth_dot_v1_dot_game__token__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61uth/v1/game_token_issuer.proto\x12\x07\x61uth.v1\x1a\x18\x61uth/v1/game_token.proto\"S\n\x15IssueGameTokenRequest\x12:\n\ntoken_type\x18\x01 \x01(\x0e\x32\x1b.auth.v1.GameTokenIssueTypeR\ttokenType\"H\n\x16IssueGameTokenResponse\x12.\n\x05token\x18\x01 \x01(\x0b\x32\x18.auth.v1.SignedGameTokenR\x05token*\x84\x02\n\x12GameTokenIssueType\x12%\n!GAME_TOKEN_ISSUE_TYPE_UNSPECIFIED\x10\x00\x12\"\n\x1eGAME_TOKEN_ISSUE_TYPE_TEAM_BOT\x10\x01\x12&\n\"GAME_TOKEN_ISSUE_TYPE_TEAM_BOT_DEV\x10\x02\x12#\n\x1fGAME_TOKEN_ISSUE_TYPE_SPECTATOR\x10\x03\x12(\n$GAME_TOKEN_ISSUE_TYPE_TEAM_SPECTATOR\x10\x04\x12,\n(GAME_TOKEN_ISSUE_TYPE_TEAM_DEV_SPECTATOR\x10\x05\x32k\n\x16GameTokenIssuerService\x12Q\n\x0eIssueGameToken\x12\x1e.auth.v1.IssueGameTokenRequest\x1a\x1f.auth.v1.IssueGameTokenResponseB\x14\xaa\x02\x11HA3.Proto.Auth.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.game_token_issuer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021HA3.Proto.Auth.V1'
  _globals['_GAMETOKENISSUETYPE']._serialized_start=230
  _globals['_GAMETOKENISSUETYPE']._serialized_end=490
  _globals['_ISSUEGAMETOKENREQUEST']._serialized_start=70
  _globals['_ISSUEGAMETOKENREQUEST']._serialized_end=153
  _globals['_ISSUEGAMETOKENRESPONSE']._serialized_start=155
  _globals['_ISSUEGAMETOKENRESPONSE']._serialized_end=227
  _globals['_GAMETOKENISSUERSERVICE']._serialized_start=492
  _globals['_GAMETOKENISSUERSERVICE']._serialized_end=599
# @@protoc_insertion_point(module_scope)
