"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from hackarena3.proto.auth.v1 import game_token_pb2 as _game_token_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _GameTokenInactiveReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _GameTokenInactiveReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GameTokenInactiveReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GAME_TOKEN_INACTIVE_REASON_UNSPECIFIED: _GameTokenInactiveReason.ValueType  # 0
    GAME_TOKEN_INACTIVE_REASON_MALFORMED: _GameTokenInactiveReason.ValueType  # 1
    GAME_TOKEN_INACTIVE_REASON_INVALID_SIGNATURE: _GameTokenInactiveReason.ValueType  # 2
    GAME_TOKEN_INACTIVE_REASON_EXPIRED: _GameTokenInactiveReason.ValueType  # 3
    GAME_TOKEN_INACTIVE_REASON_NOT_YET_VALID: _GameTokenInactiveReason.ValueType  # 4
    GAME_TOKEN_INACTIVE_REASON_ISSUER_NOT_ALLOWED: _GameTokenInactiveReason.ValueType  # 5
    GAME_TOKEN_INACTIVE_REASON_AUDIENCE_NOT_ALLOWED: _GameTokenInactiveReason.ValueType  # 6
    GAME_TOKEN_INACTIVE_REASON_TOKEN_TYPE_NOT_ALLOWED: _GameTokenInactiveReason.ValueType  # 7
    GAME_TOKEN_INACTIVE_REASON_SCOPE_NOT_ALLOWED: _GameTokenInactiveReason.ValueType  # 8
    GAME_TOKEN_INACTIVE_REASON_REVOKED: _GameTokenInactiveReason.ValueType  # 9
    GAME_TOKEN_INACTIVE_REASON_INTERNAL_ERROR: _GameTokenInactiveReason.ValueType  # 10

class GameTokenInactiveReason(_GameTokenInactiveReason, metaclass=_GameTokenInactiveReasonEnumTypeWrapper):
    """Standardized reason why token is not active."""

GAME_TOKEN_INACTIVE_REASON_UNSPECIFIED: GameTokenInactiveReason.ValueType  # 0
GAME_TOKEN_INACTIVE_REASON_MALFORMED: GameTokenInactiveReason.ValueType  # 1
GAME_TOKEN_INACTIVE_REASON_INVALID_SIGNATURE: GameTokenInactiveReason.ValueType  # 2
GAME_TOKEN_INACTIVE_REASON_EXPIRED: GameTokenInactiveReason.ValueType  # 3
GAME_TOKEN_INACTIVE_REASON_NOT_YET_VALID: GameTokenInactiveReason.ValueType  # 4
GAME_TOKEN_INACTIVE_REASON_ISSUER_NOT_ALLOWED: GameTokenInactiveReason.ValueType  # 5
GAME_TOKEN_INACTIVE_REASON_AUDIENCE_NOT_ALLOWED: GameTokenInactiveReason.ValueType  # 6
GAME_TOKEN_INACTIVE_REASON_TOKEN_TYPE_NOT_ALLOWED: GameTokenInactiveReason.ValueType  # 7
GAME_TOKEN_INACTIVE_REASON_SCOPE_NOT_ALLOWED: GameTokenInactiveReason.ValueType  # 8
GAME_TOKEN_INACTIVE_REASON_REVOKED: GameTokenInactiveReason.ValueType  # 9
GAME_TOKEN_INACTIVE_REASON_INTERNAL_ERROR: GameTokenInactiveReason.ValueType  # 10
Global___GameTokenInactiveReason: _TypeAlias = GameTokenInactiveReason  # noqa: Y015

@_typing.final
class IntrospectGameTokenRequest(_message.Message):
    """Request for token introspection."""

    DESCRIPTOR: _descriptor.Descriptor

    JWT_FIELD_NUMBER: _builtins.int
    jwt: _builtins.str
    """Compact JWT string encoded as header.payload.signature."""
    def __init__(
        self,
        *,
        jwt: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["jwt", b"jwt"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IntrospectGameTokenRequest: _TypeAlias = IntrospectGameTokenRequest  # noqa: Y015

@_typing.final
class IntrospectGameTokenResponse(_message.Message):
    """Token introspection result."""

    DESCRIPTOR: _descriptor.Descriptor

    ACTIVE_FIELD_NUMBER: _builtins.int
    HEADER_FIELD_NUMBER: _builtins.int
    CLAIMS_FIELD_NUMBER: _builtins.int
    INACTIVE_REASON_FIELD_NUMBER: _builtins.int
    INACTIVE_REASON_DEBUG_FIELD_NUMBER: _builtins.int
    active: _builtins.bool
    """True if token is valid and currently active."""
    inactive_reason: Global___GameTokenInactiveReason.ValueType
    """Standardized inactive reason.
    When active == true, inactive_reason MUST be UNSPECIFIED.
    When active == false, inactive_reason SHOULD be a specific non-UNSPECIFIED reason.
    """
    inactive_reason_debug: _builtins.str
    """Debug-only detail for logs/diagnostics; not intended for end users."""
    @_builtins.property
    def header(self) -> _game_token_pb2.GameTokenHeader:
        """Decoded JWT header. MAY be unset when active == false."""

    @_builtins.property
    def claims(self) -> _game_token_pb2.GameTokenClaims:
        """Decoded and typed game claims. MAY be unset when active == false."""

    def __init__(
        self,
        *,
        active: _builtins.bool = ...,
        header: _game_token_pb2.GameTokenHeader | None = ...,
        claims: _game_token_pb2.GameTokenClaims | None = ...,
        inactive_reason: Global___GameTokenInactiveReason.ValueType = ...,
        inactive_reason_debug: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["claims", b"claims", "header", b"header"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "claims", b"claims", "header", b"header", "inactive_reason", b"inactive_reason", "inactive_reason_debug", b"inactive_reason_debug"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___IntrospectGameTokenResponse: _TypeAlias = IntrospectGameTokenResponse  # noqa: Y015
