"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from hackarena3.proto.auth.v1 import game_token_pb2 as _game_token_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _JwkKeyUse:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _JwkKeyUseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_JwkKeyUse.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    JWK_KEY_USE_UNSPECIFIED: _JwkKeyUse.ValueType  # 0
    JWK_KEY_USE_SIG: _JwkKeyUse.ValueType  # 1

class JwkKeyUse(_JwkKeyUse, metaclass=_JwkKeyUseEnumTypeWrapper):
    """JWK "use" values for game token signing keys."""

JWK_KEY_USE_UNSPECIFIED: JwkKeyUse.ValueType  # 0
JWK_KEY_USE_SIG: JwkKeyUse.ValueType  # 1
Global___JwkKeyUse: _TypeAlias = JwkKeyUse  # noqa: Y015

class _JwkKeyType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _JwkKeyTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_JwkKeyType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    JWK_KEY_TYPE_UNSPECIFIED: _JwkKeyType.ValueType  # 0
    JWK_KEY_TYPE_EC: _JwkKeyType.ValueType  # 1

class JwkKeyType(_JwkKeyType, metaclass=_JwkKeyTypeEnumTypeWrapper):
    """JWK "kty" values supported by game token JWKS."""

JWK_KEY_TYPE_UNSPECIFIED: JwkKeyType.ValueType  # 0
JWK_KEY_TYPE_EC: JwkKeyType.ValueType  # 1
Global___JwkKeyType: _TypeAlias = JwkKeyType  # noqa: Y015

class _JwkEcCurve:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _JwkEcCurveEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_JwkEcCurve.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    JWK_EC_CURVE_UNSPECIFIED: _JwkEcCurve.ValueType  # 0
    JWK_EC_CURVE_P256: _JwkEcCurve.ValueType  # 1

class JwkEcCurve(_JwkEcCurve, metaclass=_JwkEcCurveEnumTypeWrapper):
    """JWK "crv" values supported by game token JWKS."""

JWK_EC_CURVE_UNSPECIFIED: JwkEcCurve.ValueType  # 0
JWK_EC_CURVE_P256: JwkEcCurve.ValueType  # 1
Global___JwkEcCurve: _TypeAlias = JwkEcCurve  # noqa: Y015

@_typing.final
class GameTokenJwk(_message.Message):
    """Public JWK entry used for verifying game tokens."""

    DESCRIPTOR: _descriptor.Descriptor

    USE_FIELD_NUMBER: _builtins.int
    KTY_FIELD_NUMBER: _builtins.int
    KID_FIELD_NUMBER: _builtins.int
    CRV_FIELD_NUMBER: _builtins.int
    ALG_FIELD_NUMBER: _builtins.int
    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    use: Global___JwkKeyUse.ValueType
    kty: Global___JwkKeyType.ValueType
    kid: _builtins.str
    """JWK key identifier ("kid")."""
    crv: Global___JwkEcCurve.ValueType
    alg: _game_token_pb2.JwtAlgorithm.ValueType
    """JWT/JWK algorithm for this key, for example ES256."""
    x: _builtins.str
    """EC public key X coordinate encoded as base64url (RFC 7517)."""
    y: _builtins.str
    """EC public key Y coordinate encoded as base64url (RFC 7517)."""
    def __init__(
        self,
        *,
        use: Global___JwkKeyUse.ValueType = ...,
        kty: Global___JwkKeyType.ValueType = ...,
        kid: _builtins.str = ...,
        crv: Global___JwkEcCurve.ValueType = ...,
        alg: _game_token_pb2.JwtAlgorithm.ValueType = ...,
        x: _builtins.str = ...,
        y: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["alg", b"alg", "crv", b"crv", "kid", b"kid", "kty", b"kty", "use", b"use", "x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GameTokenJwk: _TypeAlias = GameTokenJwk  # noqa: Y015

@_typing.final
class GetGameTokenJwksRequest(_message.Message):
    """Request for public game-token JWKS."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetGameTokenJwksRequest: _TypeAlias = GetGameTokenJwksRequest  # noqa: Y015

@_typing.final
class GetGameTokenJwksResponse(_message.Message):
    """Public game-token JWKS payload."""

    DESCRIPTOR: _descriptor.Descriptor

    KEYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def keys(self) -> _containers.RepeatedCompositeFieldContainer[Global___GameTokenJwk]: ...
    def __init__(
        self,
        *,
        keys: _abc.Iterable[Global___GameTokenJwk] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["keys", b"keys"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetGameTokenJwksResponse: _TypeAlias = GetGameTokenJwksResponse  # noqa: Y015
