# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/game_token_jwks.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'auth/v1/game_token_jwks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hackarena3.proto.auth.v1 import game_token_pb2 as auth_dot_v1_dot_game__token__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61uth/v1/game_token_jwks.proto\x12\x07\x61uth.v1\x1a\x18\x61uth/v1/game_token.proto\"\xd9\x01\n\x0cGameTokenJwk\x12$\n\x03use\x18\x01 \x01(\x0e\x32\x12.auth.v1.JwkKeyUseR\x03use\x12%\n\x03kty\x18\x02 \x01(\x0e\x32\x13.auth.v1.JwkKeyTypeR\x03kty\x12\x10\n\x03kid\x18\x03 \x01(\tR\x03kid\x12%\n\x03\x63rv\x18\x04 \x01(\x0e\x32\x13.auth.v1.JwkEcCurveR\x03\x63rv\x12\'\n\x03\x61lg\x18\x05 \x01(\x0e\x32\x15.auth.v1.JwtAlgorithmR\x03\x61lg\x12\x0c\n\x01x\x18\x06 \x01(\tR\x01x\x12\x0c\n\x01y\x18\x07 \x01(\tR\x01y\"\x19\n\x17GetGameTokenJwksRequest\"E\n\x18GetGameTokenJwksResponse\x12)\n\x04keys\x18\x01 \x03(\x0b\x32\x15.auth.v1.GameTokenJwkR\x04keys*=\n\tJwkKeyUse\x12\x1b\n\x17JWK_KEY_USE_UNSPECIFIED\x10\x00\x12\x13\n\x0fJWK_KEY_USE_SIG\x10\x01*?\n\nJwkKeyType\x12\x1c\n\x18JWK_KEY_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fJWK_KEY_TYPE_EC\x10\x01*A\n\nJwkEcCurve\x12\x1c\n\x18JWK_EC_CURVE_UNSPECIFIED\x10\x00\x12\x15\n\x11JWK_EC_CURVE_P256\x10\x01\x32o\n\x14GameTokenJwksService\x12W\n\x10GetGameTokenJwks\x12 .auth.v1.GetGameTokenJwksRequest\x1a!.auth.v1.GetGameTokenJwksResponseB\x14\xaa\x02\x11HA3.Proto.Auth.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.game_token_jwks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021HA3.Proto.Auth.V1'
  _globals['_JWKKEYUSE']._serialized_start=386
  _globals['_JWKKEYUSE']._serialized_end=447
  _globals['_JWKKEYTYPE']._serialized_start=449
  _globals['_JWKKEYTYPE']._serialized_end=512
  _globals['_JWKECCURVE']._serialized_start=514
  _globals['_JWKECCURVE']._serialized_end=579
  _globals['_GAMETOKENJWK']._serialized_start=69
  _globals['_GAMETOKENJWK']._serialized_end=286
  _globals['_GETGAMETOKENJWKSREQUEST']._serialized_start=288
  _globals['_GETGAMETOKENJWKSREQUEST']._serialized_end=313
  _globals['_GETGAMETOKENJWKSRESPONSE']._serialized_start=315
  _globals['_GETGAMETOKENJWKSRESPONSE']._serialized_end=384
  _globals['_GAMETOKENJWKSSERVICE']._serialized_start=581
  _globals['_GAMETOKENJWKSSERVICE']._serialized_end=692
# @@protoc_insertion_point(module_scope)
