# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hackarena3.proto.auth.v1 import game_token_introspection_pb2 as auth_dot_v1_dot_game__token__introspection__pb2


class GameTokenIntrospectionServiceStub(object):
    """Auth API for validating and decoding game tokens.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntrospectGameToken = channel.unary_unary(
                '/auth.v1.GameTokenIntrospectionService/IntrospectGameToken',
                request_serializer=auth_dot_v1_dot_game__token__introspection__pb2.IntrospectGameTokenRequest.SerializeToString,
                response_deserializer=auth_dot_v1_dot_game__token__introspection__pb2.IntrospectGameTokenResponse.FromString,
                _registered_method=True)


class GameTokenIntrospectionServiceServicer(object):
    """Auth API for validating and decoding game tokens.
    """

    def IntrospectGameToken(self, request, context):
        """Validates token signature/claims and returns typed token content.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameTokenIntrospectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IntrospectGameToken': grpc.unary_unary_rpc_method_handler(
                    servicer.IntrospectGameToken,
                    request_deserializer=auth_dot_v1_dot_game__token__introspection__pb2.IntrospectGameTokenRequest.FromString,
                    response_serializer=auth_dot_v1_dot_game__token__introspection__pb2.IntrospectGameTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.v1.GameTokenIntrospectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.v1.GameTokenIntrospectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameTokenIntrospectionService(object):
    """Auth API for validating and decoding game tokens.
    """

    @staticmethod
    def IntrospectGameToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.GameTokenIntrospectionService/IntrospectGameToken',
            auth_dot_v1_dot_game__token__introspection__pb2.IntrospectGameTokenRequest.SerializeToString,
            auth_dot_v1_dot_game__token__introspection__pb2.IntrospectGameTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
