# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/game_token_introspection.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'auth/v1/game_token_introspection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hackarena3.proto.auth.v1 import game_token_pb2 as auth_dot_v1_dot_game__token__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&auth/v1/game_token_introspection.proto\x12\x07\x61uth.v1\x1a\x18\x61uth/v1/game_token.proto\".\n\x1aIntrospectGameTokenRequest\x12\x10\n\x03jwt\x18\x01 \x01(\tR\x03jwt\"\x98\x02\n\x1bIntrospectGameTokenResponse\x12\x16\n\x06\x61\x63tive\x18\x01 \x01(\x08R\x06\x61\x63tive\x12\x30\n\x06header\x18\x02 \x01(\x0b\x32\x18.auth.v1.GameTokenHeaderR\x06header\x12\x30\n\x06\x63laims\x18\x03 \x01(\x0b\x32\x18.auth.v1.GameTokenClaimsR\x06\x63laims\x12I\n\x0finactive_reason\x18\x04 \x01(\x0e\x32 .auth.v1.GameTokenInactiveReasonR\x0einactiveReason\x12\x32\n\x15inactive_reason_debug\x18\x05 \x01(\tR\x13inactiveReasonDebug*\x9f\x04\n\x17GameTokenInactiveReason\x12*\n&GAME_TOKEN_INACTIVE_REASON_UNSPECIFIED\x10\x00\x12(\n$GAME_TOKEN_INACTIVE_REASON_MALFORMED\x10\x01\x12\x30\n,GAME_TOKEN_INACTIVE_REASON_INVALID_SIGNATURE\x10\x02\x12&\n\"GAME_TOKEN_INACTIVE_REASON_EXPIRED\x10\x03\x12,\n(GAME_TOKEN_INACTIVE_REASON_NOT_YET_VALID\x10\x04\x12\x31\n-GAME_TOKEN_INACTIVE_REASON_ISSUER_NOT_ALLOWED\x10\x05\x12\x33\n/GAME_TOKEN_INACTIVE_REASON_AUDIENCE_NOT_ALLOWED\x10\x06\x12\x35\n1GAME_TOKEN_INACTIVE_REASON_TOKEN_TYPE_NOT_ALLOWED\x10\x07\x12\x30\n,GAME_TOKEN_INACTIVE_REASON_SCOPE_NOT_ALLOWED\x10\x08\x12&\n\"GAME_TOKEN_INACTIVE_REASON_REVOKED\x10\t\x12-\n)GAME_TOKEN_INACTIVE_REASON_INTERNAL_ERROR\x10\n2\x81\x01\n\x1dGameTokenIntrospectionService\x12`\n\x13IntrospectGameToken\x12#.auth.v1.IntrospectGameTokenRequest\x1a$.auth.v1.IntrospectGameTokenResponseB\x14\xaa\x02\x11HA3.Proto.Auth.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.game_token_introspection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021HA3.Proto.Auth.V1'
  _globals['_GAMETOKENINACTIVEREASON']._serialized_start=409
  _globals['_GAMETOKENINACTIVEREASON']._serialized_end=952
  _globals['_INTROSPECTGAMETOKENREQUEST']._serialized_start=77
  _globals['_INTROSPECTGAMETOKENREQUEST']._serialized_end=123
  _globals['_INTROSPECTGAMETOKENRESPONSE']._serialized_start=126
  _globals['_INTROSPECTGAMETOKENRESPONSE']._serialized_end=406
  _globals['_GAMETOKENINTROSPECTIONSERVICE']._serialized_start=955
  _globals['_GAMETOKENINTROSPECTIONSERVICE']._serialized_end=1084
# @@protoc_insertion_point(module_scope)
