# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hackarena3.proto.weather.v1 import weather_pb2 as weather_dot_v1_dot_weather__pb2


class WeatherQueryServiceStub(object):
    """Public read API for frontend/bots/spectators.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeatherNow = channel.unary_unary(
                '/weather.v1.WeatherQueryService/GetWeatherNow',
                request_serializer=weather_dot_v1_dot_weather__pb2.GetWeatherNowRequest.SerializeToString,
                response_deserializer=weather_dot_v1_dot_weather__pb2.GetWeatherNowResponse.FromString,
                _registered_method=True)
        self.StreamWeatherUpdates = channel.unary_stream(
                '/weather.v1.WeatherQueryService/StreamWeatherUpdates',
                request_serializer=weather_dot_v1_dot_weather__pb2.StreamWeatherUpdatesRequest.SerializeToString,
                response_deserializer=weather_dot_v1_dot_weather__pb2.WeatherUpdateEvent.FromString,
                _registered_method=True)
        self.GetForecastNow = channel.unary_unary(
                '/weather.v1.WeatherQueryService/GetForecastNow',
                request_serializer=weather_dot_v1_dot_weather__pb2.GetForecastNowRequest.SerializeToString,
                response_deserializer=weather_dot_v1_dot_weather__pb2.GetForecastNowResponse.FromString,
                _registered_method=True)
        self.StreamForecastUpdates = channel.unary_stream(
                '/weather.v1.WeatherQueryService/StreamForecastUpdates',
                request_serializer=weather_dot_v1_dot_weather__pb2.StreamForecastUpdatesRequest.SerializeToString,
                response_deserializer=weather_dot_v1_dot_weather__pb2.ForecastUpdateEvent.FromString,
                _registered_method=True)


class WeatherQueryServiceServicer(object):
    """Public read API for frontend/bots/spectators.
    """

    def GetWeatherNow(self, request, context):
        """Returns current weather.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWeatherUpdates(self, request, context):
        """Streams current weather updates whenever effective weather changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetForecastNow(self, request, context):
        """Returns forecast from current backend time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamForecastUpdates(self, request, context):
        """Streams forecast updates whenever effective forecast changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWeatherNow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeatherNow,
                    request_deserializer=weather_dot_v1_dot_weather__pb2.GetWeatherNowRequest.FromString,
                    response_serializer=weather_dot_v1_dot_weather__pb2.GetWeatherNowResponse.SerializeToString,
            ),
            'StreamWeatherUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWeatherUpdates,
                    request_deserializer=weather_dot_v1_dot_weather__pb2.StreamWeatherUpdatesRequest.FromString,
                    response_serializer=weather_dot_v1_dot_weather__pb2.WeatherUpdateEvent.SerializeToString,
            ),
            'GetForecastNow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetForecastNow,
                    request_deserializer=weather_dot_v1_dot_weather__pb2.GetForecastNowRequest.FromString,
                    response_serializer=weather_dot_v1_dot_weather__pb2.GetForecastNowResponse.SerializeToString,
            ),
            'StreamForecastUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamForecastUpdates,
                    request_deserializer=weather_dot_v1_dot_weather__pb2.StreamForecastUpdatesRequest.FromString,
                    response_serializer=weather_dot_v1_dot_weather__pb2.ForecastUpdateEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.v1.WeatherQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weather.v1.WeatherQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeatherQueryService(object):
    """Public read API for frontend/bots/spectators.
    """

    @staticmethod
    def GetWeatherNow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.v1.WeatherQueryService/GetWeatherNow',
            weather_dot_v1_dot_weather__pb2.GetWeatherNowRequest.SerializeToString,
            weather_dot_v1_dot_weather__pb2.GetWeatherNowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWeatherUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/weather.v1.WeatherQueryService/StreamWeatherUpdates',
            weather_dot_v1_dot_weather__pb2.StreamWeatherUpdatesRequest.SerializeToString,
            weather_dot_v1_dot_weather__pb2.WeatherUpdateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetForecastNow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.v1.WeatherQueryService/GetForecastNow',
            weather_dot_v1_dot_weather__pb2.GetForecastNowRequest.SerializeToString,
            weather_dot_v1_dot_weather__pb2.GetForecastNowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamForecastUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/weather.v1.WeatherQueryService/StreamForecastUpdates',
            weather_dot_v1_dot_weather__pb2.StreamForecastUpdatesRequest.SerializeToString,
            weather_dot_v1_dot_weather__pb2.ForecastUpdateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WeatherAdminServiceStub(object):
    """Admin API for schedule management and what-if simulations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeatherSchedule = channel.unary_unary(
                '/weather.v1.WeatherAdminService/GetWeatherSchedule',
                request_serializer=weather_dot_v1_dot_weather__pb2.GetWeatherScheduleRequest.SerializeToString,
                response_deserializer=weather_dot_v1_dot_weather__pb2.GetWeatherScheduleResponse.FromString,
                _registered_method=True)
        self.ReplaceWeatherSchedule = channel.unary_unary(
                '/weather.v1.WeatherAdminService/ReplaceWeatherSchedule',
                request_serializer=weather_dot_v1_dot_weather__pb2.ReplaceWeatherScheduleRequest.SerializeToString,
                response_deserializer=weather_dot_v1_dot_weather__pb2.ReplaceWeatherScheduleResponse.FromString,
                _registered_method=True)
        self.SimulateForecast = channel.unary_unary(
                '/weather.v1.WeatherAdminService/SimulateForecast',
                request_serializer=weather_dot_v1_dot_weather__pb2.SimulateForecastRequest.SerializeToString,
                response_deserializer=weather_dot_v1_dot_weather__pb2.SimulateForecastResponse.FromString,
                _registered_method=True)


class WeatherAdminServiceServicer(object):
    """Admin API for schedule management and what-if simulations.
    """

    def GetWeatherSchedule(self, request, context):
        """Admin only. Returns current persisted global schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceWeatherSchedule(self, request, context):
        """Admin only. Replaces persisted global schedule with provided entries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateForecast(self, request, context):
        """Admin only. Simulates forecast for temporary schedule.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWeatherSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeatherSchedule,
                    request_deserializer=weather_dot_v1_dot_weather__pb2.GetWeatherScheduleRequest.FromString,
                    response_serializer=weather_dot_v1_dot_weather__pb2.GetWeatherScheduleResponse.SerializeToString,
            ),
            'ReplaceWeatherSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceWeatherSchedule,
                    request_deserializer=weather_dot_v1_dot_weather__pb2.ReplaceWeatherScheduleRequest.FromString,
                    response_serializer=weather_dot_v1_dot_weather__pb2.ReplaceWeatherScheduleResponse.SerializeToString,
            ),
            'SimulateForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateForecast,
                    request_deserializer=weather_dot_v1_dot_weather__pb2.SimulateForecastRequest.FromString,
                    response_serializer=weather_dot_v1_dot_weather__pb2.SimulateForecastResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.v1.WeatherAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weather.v1.WeatherAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeatherAdminService(object):
    """Admin API for schedule management and what-if simulations.
    """

    @staticmethod
    def GetWeatherSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.v1.WeatherAdminService/GetWeatherSchedule',
            weather_dot_v1_dot_weather__pb2.GetWeatherScheduleRequest.SerializeToString,
            weather_dot_v1_dot_weather__pb2.GetWeatherScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplaceWeatherSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.v1.WeatherAdminService/ReplaceWeatherSchedule',
            weather_dot_v1_dot_weather__pb2.ReplaceWeatherScheduleRequest.SerializeToString,
            weather_dot_v1_dot_weather__pb2.ReplaceWeatherScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.v1.WeatherAdminService/SimulateForecast',
            weather_dot_v1_dot_weather__pb2.SimulateForecastRequest.SerializeToString,
            weather_dot_v1_dot_weather__pb2.SimulateForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
