"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _WeatherType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _WeatherTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_WeatherType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    WEATHER_TYPE_UNSPECIFIED: _WeatherType.ValueType  # 0
    WEATHER_TYPE_CLEAR: _WeatherType.ValueType  # 1
    WEATHER_TYPE_PARTLY_CLOUDY: _WeatherType.ValueType  # 2
    WEATHER_TYPE_OVERCAST: _WeatherType.ValueType  # 3
    WEATHER_TYPE_LIGHT_RAIN: _WeatherType.ValueType  # 4
    WEATHER_TYPE_MEDIUM_RAIN: _WeatherType.ValueType  # 5
    WEATHER_TYPE_HEAVY_RAIN: _WeatherType.ValueType  # 6

class WeatherType(_WeatherType, metaclass=_WeatherTypeEnumTypeWrapper):
    """Fixed weather states supported by backend and frontend."""

WEATHER_TYPE_UNSPECIFIED: WeatherType.ValueType  # 0
WEATHER_TYPE_CLEAR: WeatherType.ValueType  # 1
WEATHER_TYPE_PARTLY_CLOUDY: WeatherType.ValueType  # 2
WEATHER_TYPE_OVERCAST: WeatherType.ValueType  # 3
WEATHER_TYPE_LIGHT_RAIN: WeatherType.ValueType  # 4
WEATHER_TYPE_MEDIUM_RAIN: WeatherType.ValueType  # 5
WEATHER_TYPE_HEAVY_RAIN: WeatherType.ValueType  # 6
Global___WeatherType: _TypeAlias = WeatherType  # noqa: Y015

class _ForecastPreset:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ForecastPresetEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ForecastPreset.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FORECAST_PRESET_UNSPECIFIED: _ForecastPreset.ValueType  # 0
    FORECAST_PRESET_1_HOUR_STEP_15_MIN: _ForecastPreset.ValueType  # 1
    FORECAST_PRESET_12_HOURS_STEP_1_HOUR: _ForecastPreset.ValueType  # 2

class ForecastPreset(_ForecastPreset, metaclass=_ForecastPresetEnumTypeWrapper):
    """Allowed forecast presets."""

FORECAST_PRESET_UNSPECIFIED: ForecastPreset.ValueType  # 0
FORECAST_PRESET_1_HOUR_STEP_15_MIN: ForecastPreset.ValueType  # 1
FORECAST_PRESET_12_HOURS_STEP_1_HOUR: ForecastPreset.ValueType  # 2
Global___ForecastPreset: _TypeAlias = ForecastPreset  # noqa: Y015

@_typing.final
class ForecastPoint(_message.Message):
    """Forecast point (estimation, not guaranteed real outcome)."""

    DESCRIPTOR: _descriptor.Descriptor

    TIME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    RAIN_PROBABILITY_FIELD_NUMBER: _builtins.int
    TEMPERATURE_C_FIELD_NUMBER: _builtins.int
    type: Global___WeatherType.ValueType
    rain_probability: _builtins.float
    """Value range: 0.0..1.0"""
    temperature_c: _builtins.int
    """Air temperature in Celsius degrees."""
    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp:
        """Slot time (UTC)"""

    def __init__(
        self,
        *,
        time: _timestamp_pb2.Timestamp | None = ...,
        type: Global___WeatherType.ValueType = ...,
        rain_probability: _builtins.float = ...,
        temperature_c: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rain_probability", b"rain_probability", "temperature_c", b"temperature_c", "time", b"time", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ForecastPoint: _TypeAlias = ForecastPoint  # noqa: Y015

@_typing.final
class WeatherNow(_message.Message):
    """Current weather snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    TEMPERATURE_C_FIELD_NUMBER: _builtins.int
    type: Global___WeatherType.ValueType
    temperature_c: _builtins.int
    """Air temperature in Celsius degrees."""
    def __init__(
        self,
        *,
        type: Global___WeatherType.ValueType = ...,
        temperature_c: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["temperature_c", b"temperature_c", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WeatherNow: _TypeAlias = WeatherNow  # noqa: Y015

@_typing.final
class ForecastSpecAtTime(_message.Message):
    """Forecast specification for explicit start time."""

    DESCRIPTOR: _descriptor.Descriptor

    START_TIME_FIELD_NUMBER: _builtins.int
    PRESET_FIELD_NUMBER: _builtins.int
    STOCHASTIC_FIELD_NUMBER: _builtins.int
    SEED_FIELD_NUMBER: _builtins.int
    preset: Global___ForecastPreset.ValueType
    stochastic: _builtins.bool
    """If true, backend may apply stochastic variation."""
    seed: _builtins.int
    """Optional deterministic seed for reproducible results."""
    @_builtins.property
    def start_time(self) -> _timestamp_pb2.Timestamp:
        """UTC start time used for simulation/projection."""

    def __init__(
        self,
        *,
        start_time: _timestamp_pb2.Timestamp | None = ...,
        preset: Global___ForecastPreset.ValueType = ...,
        stochastic: _builtins.bool = ...,
        seed: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_seed", b"_seed", "seed", b"seed", "start_time", b"start_time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_seed", b"_seed", "preset", b"preset", "seed", b"seed", "start_time", b"start_time", "stochastic", b"stochastic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__seed: _TypeAlias = _typing.Literal["seed"]  # noqa: Y015
    _WhichOneofArgType__seed: _TypeAlias = _typing.Literal["_seed", b"_seed"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__seed) -> _WhichOneofReturnType__seed | None: ...

Global___ForecastSpecAtTime: _TypeAlias = ForecastSpecAtTime  # noqa: Y015

@_typing.final
class ForecastSpecNow(_message.Message):
    """Forecast specification "from now"."""

    DESCRIPTOR: _descriptor.Descriptor

    PRESET_FIELD_NUMBER: _builtins.int
    preset: Global___ForecastPreset.ValueType
    """Preset defining forecast horizon and time step."""
    def __init__(
        self,
        *,
        preset: Global___ForecastPreset.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["preset", b"preset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ForecastSpecNow: _TypeAlias = ForecastSpecNow  # noqa: Y015

@_typing.final
class WeatherSandboxTarget(_message.Message):
    """Weather target for a specific active sandbox session."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    sandbox_id: _builtins.str
    """Target active sandbox identifier."""
    def __init__(
        self,
        *,
        sandbox_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WeatherSandboxTarget: _TypeAlias = WeatherSandboxTarget  # noqa: Y015

@_typing.final
class WeatherOfficialRaceTarget(_message.Message):
    """Weather target for active official race session."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___WeatherOfficialRaceTarget: _TypeAlias = WeatherOfficialRaceTarget  # noqa: Y015

@_typing.final
class WeatherTarget(_message.Message):
    """Explicit weather source target.
    Exactly one target must be set.
    """

    DESCRIPTOR: _descriptor.Descriptor

    OFFICIAL_RACE_FIELD_NUMBER: _builtins.int
    SANDBOX_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def official_race(self) -> Global___WeatherOfficialRaceTarget: ...
    @_builtins.property
    def sandbox(self) -> Global___WeatherSandboxTarget: ...
    def __init__(
        self,
        *,
        official_race: Global___WeatherOfficialRaceTarget | None = ...,
        sandbox: Global___WeatherSandboxTarget | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["official_race", b"official_race", "sandbox", b"sandbox", "target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["official_race", b"official_race", "sandbox", b"sandbox", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_target: _TypeAlias = _typing.Literal["official_race", "sandbox"]  # noqa: Y015
    _WhichOneofArgType_target: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_target) -> _WhichOneofReturnType_target | None: ...

Global___WeatherTarget: _TypeAlias = WeatherTarget  # noqa: Y015

@_typing.final
class GetForecastNowRequest(_message.Message):
    """Public forecast request. Backend computes forecast from current server time."""

    DESCRIPTOR: _descriptor.Descriptor

    SPEC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def spec(self) -> Global___ForecastSpecNow:
        """Forecast parameters."""

    def __init__(
        self,
        *,
        spec: Global___ForecastSpecNow | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["spec", b"spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["spec", b"spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetForecastNowRequest: _TypeAlias = GetForecastNowRequest  # noqa: Y015

@_typing.final
class GetForecastNowResponse(_message.Message):
    """Public forecast response."""

    DESCRIPTOR: _descriptor.Descriptor

    POINTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def points(self) -> _containers.RepeatedCompositeFieldContainer[Global___ForecastPoint]: ...
    def __init__(
        self,
        *,
        points: _abc.Iterable[Global___ForecastPoint] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["points", b"points"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetForecastNowResponse: _TypeAlias = GetForecastNowResponse  # noqa: Y015

@_typing.final
class StreamForecastUpdatesRequest(_message.Message):
    """Public stream request for forecast updates."""

    DESCRIPTOR: _descriptor.Descriptor

    SPEC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def spec(self) -> Global___ForecastSpecNow:
        """Forecast parameters."""

    def __init__(
        self,
        *,
        spec: Global___ForecastSpecNow | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["spec", b"spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["spec", b"spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamForecastUpdatesRequest: _TypeAlias = StreamForecastUpdatesRequest  # noqa: Y015

@_typing.final
class ForecastUpdateEvent(_message.Message):
    """Forecast update event pushed by backend when effective forecast changes."""

    DESCRIPTOR: _descriptor.Descriptor

    POINTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def points(self) -> _containers.RepeatedCompositeFieldContainer[Global___ForecastPoint]: ...
    def __init__(
        self,
        *,
        points: _abc.Iterable[Global___ForecastPoint] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["points", b"points"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ForecastUpdateEvent: _TypeAlias = ForecastUpdateEvent  # noqa: Y015

@_typing.final
class GetWeatherNowRequest(_message.Message):
    """Public request for current weather state."""

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def target(self) -> Global___WeatherTarget:
        """Required weather target.
        Request must include exactly one target; otherwise it is rejected.
        """

    def __init__(
        self,
        *,
        target: Global___WeatherTarget | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetWeatherNowRequest: _TypeAlias = GetWeatherNowRequest  # noqa: Y015

@_typing.final
class GetWeatherNowResponse(_message.Message):
    """Public response with current weather state."""

    DESCRIPTOR: _descriptor.Descriptor

    NOW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def now(self) -> Global___WeatherNow: ...
    def __init__(
        self,
        *,
        now: Global___WeatherNow | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["now", b"now"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["now", b"now"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetWeatherNowResponse: _TypeAlias = GetWeatherNowResponse  # noqa: Y015

@_typing.final
class StreamWeatherUpdatesRequest(_message.Message):
    """Public stream request for current weather updates."""

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def target(self) -> Global___WeatherTarget:
        """Required weather target.
        Request must include exactly one target; otherwise it is rejected.
        """

    def __init__(
        self,
        *,
        target: Global___WeatherTarget | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamWeatherUpdatesRequest: _TypeAlias = StreamWeatherUpdatesRequest  # noqa: Y015

@_typing.final
class WeatherUpdateEvent(_message.Message):
    """Current weather update event pushed by backend when effective weather changes."""

    DESCRIPTOR: _descriptor.Descriptor

    NOW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def now(self) -> Global___WeatherNow: ...
    def __init__(
        self,
        *,
        now: Global___WeatherNow | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["now", b"now"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["now", b"now"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WeatherUpdateEvent: _TypeAlias = WeatherUpdateEvent  # noqa: Y015

@_typing.final
class WeatherScheduleEntry(_message.Message):
    """Global weather schedule entry used by admin API."""

    DESCRIPTOR: _descriptor.Descriptor

    FROM_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    TEMPERATURE_C_FIELD_NUMBER: _builtins.int
    type: Global___WeatherType.ValueType
    temperature_c: _builtins.int
    """Air temperature in Celsius degrees for this schedule segment."""
    def __init__(
        self,
        *,
        type: Global___WeatherType.ValueType = ...,
        temperature_c: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["from", b"from"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["from", b"from", "temperature_c", b"temperature_c", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WeatherScheduleEntry: _TypeAlias = WeatherScheduleEntry  # noqa: Y015

@_typing.final
class GetWeatherScheduleRequest(_message.Message):
    """Admin request to read persisted global schedule."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetWeatherScheduleRequest: _TypeAlias = GetWeatherScheduleRequest  # noqa: Y015

@_typing.final
class GetWeatherScheduleResponse(_message.Message):
    """Admin response with persisted global schedule."""

    DESCRIPTOR: _descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___WeatherScheduleEntry]:
        """Entries must be sorted by "from" ascending and contain no duplicate timestamps."""

    def __init__(
        self,
        *,
        entries: _abc.Iterable[Global___WeatherScheduleEntry] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetWeatherScheduleResponse: _TypeAlias = GetWeatherScheduleResponse  # noqa: Y015

@_typing.final
class ReplaceWeatherScheduleRequest(_message.Message):
    """Full replacement of schedule data."""

    DESCRIPTOR: _descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___WeatherScheduleEntry]:
        """Full replacement payload. Entries must be sorted by "from" ascending and contain no duplicate timestamps."""

    def __init__(
        self,
        *,
        entries: _abc.Iterable[Global___WeatherScheduleEntry] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ReplaceWeatherScheduleRequest: _TypeAlias = ReplaceWeatherScheduleRequest  # noqa: Y015

@_typing.final
class ReplaceWeatherScheduleResponse(_message.Message):
    """Empty admin response returned after successful schedule replacement."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ReplaceWeatherScheduleResponse: _TypeAlias = ReplaceWeatherScheduleResponse  # noqa: Y015

@_typing.final
class SimulateForecastRequest(_message.Message):
    """Simulate forecast for temporary schedule sent by frontend without persisting it."""

    DESCRIPTOR: _descriptor.Descriptor

    DRAFT_ENTRIES_FIELD_NUMBER: _builtins.int
    SPEC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def draft_entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___WeatherScheduleEntry]:
        """Temporary schedule. Must follow the same ordering and uniqueness rules as persisted entries."""

    @_builtins.property
    def spec(self) -> Global___ForecastSpecAtTime:
        """Simulation spec with explicit start time."""

    def __init__(
        self,
        *,
        draft_entries: _abc.Iterable[Global___WeatherScheduleEntry] | None = ...,
        spec: Global___ForecastSpecAtTime | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["spec", b"spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["draft_entries", b"draft_entries", "spec", b"spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SimulateForecastRequest: _TypeAlias = SimulateForecastRequest  # noqa: Y015

@_typing.final
class SimulateForecastResponse(_message.Message):
    """Admin simulation response. No persisted data is modified."""

    DESCRIPTOR: _descriptor.Descriptor

    POINTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def points(self) -> _containers.RepeatedCompositeFieldContainer[Global___ForecastPoint]: ...
    def __init__(
        self,
        *,
        points: _abc.Iterable[Global___ForecastPoint] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["points", b"points"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SimulateForecastResponse: _TypeAlias = SimulateForecastResponse  # noqa: Y015
