# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hackarena/submission/v1/common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'hackarena/submission/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$hackarena/submission/v1/common.proto\x12\x17hackarena.submission.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n\x0c\x42uildFailure\x12\x44\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32(.hackarena.submission.v1.FailureCategoryR\x08\x63\x61tegory\x12\x12\n\x04\x63ode\x18\x02 \x01(\tR\x04\x63ode\x12\x18\n\x07message\x18\x03 \x01(\tR\x07message\"\xa1\x03\n\x0c\x42uildSummary\x12\x19\n\x08\x62uild_id\x18\x01 \x01(\tR\x07\x62uildId\x12\x1b\n\tupload_id\x18\x02 \x01(\tR\x08uploadId\x12<\n\x06status\x18\x03 \x01(\x0e\x32$.hackarena.submission.v1.BuildStatusR\x06status\x12?\n\x07\x66\x61ilure\x18\x04 \x01(\x0b\x32%.hackarena.submission.v1.BuildFailureR\x07\x66\x61ilure\x12\'\n\x0fimage_reference\x18\x05 \x01(\tR\x0eimageReference\x12\x39\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x39\n\nstarted_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n\x0b\x66inished_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\nfinishedAt*\xcb\x01\n\x0b\x42uildStatus\x12\x1c\n\x18\x42UILD_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13\x42UILD_STATUS_QUEUED\x10\x01\x12\x18\n\x14\x42UILD_STATUS_RUNNING\x10\x02\x12\x1a\n\x16\x42UILD_STATUS_SUCCEEDED\x10\x03\x12\x17\n\x13\x42UILD_STATUS_FAILED\x10\x04\x12\x1a\n\x16\x42UILD_STATUS_CANCELLED\x10\x05\x12\x1a\n\x16\x42UILD_STATUS_TIMED_OUT\x10\x06*\xc3\x01\n\x0f\x46\x61ilureCategory\x12 \n\x1c\x46\x41ILURE_CATEGORY_UNSPECIFIED\x10\x00\x12\x1a\n\x16\x46\x41ILURE_CATEGORY_INPUT\x10\x01\x12\x1a\n\x16\x46\x41ILURE_CATEGORY_BUILD\x10\x02\x12\x19\n\x15\x46\x41ILURE_CATEGORY_PUSH\x10\x03\x12\x1c\n\x18\x46\x41ILURE_CATEGORY_TIMEOUT\x10\x04\x12\x1d\n\x19\x46\x41ILURE_CATEGORY_INTERNAL\x10\x05\x42\x1a\xaa\x02\x17HackArena.Submission.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hackarena.submission.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027HackArena.Submission.V1'
  _globals['_BUILDSTATUS']._serialized_start=652
  _globals['_BUILDSTATUS']._serialized_end=855
  _globals['_FAILURECATEGORY']._serialized_start=858
  _globals['_FAILURECATEGORY']._serialized_end=1053
  _globals['_BUILDFAILURE']._serialized_start=99
  _globals['_BUILDFAILURE']._serialized_end=229
  _globals['_BUILDSUMMARY']._serialized_start=232
  _globals['_BUILDSUMMARY']._serialized_end=649
# @@protoc_insertion_point(module_scope)
