"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UploadSourceMetadata(_message.Message):
    """Metadata sent as first upload frame."""

    DESCRIPTOR: _descriptor.Descriptor

    FILE_NAME_FIELD_NUMBER: _builtins.int
    file_name: _builtins.str
    """Original file name from CLI."""
    def __init__(
        self,
        *,
        file_name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file_name", b"file_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UploadSourceMetadata: _TypeAlias = UploadSourceMetadata  # noqa: Y015

@_typing.final
class UploadSourceRequest(_message.Message):
    """Streaming request for source upload."""

    DESCRIPTOR: _descriptor.Descriptor

    METADATA_FIELD_NUMBER: _builtins.int
    CHUNK_FIELD_NUMBER: _builtins.int
    chunk: _builtins.bytes
    """Binary chunk frame."""
    @_builtins.property
    def metadata(self) -> Global___UploadSourceMetadata:
        """Upload metadata frame."""

    def __init__(
        self,
        *,
        metadata: Global___UploadSourceMetadata | None = ...,
        chunk: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk", "metadata", b"metadata", "payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk", "metadata", b"metadata", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["metadata", "chunk"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___UploadSourceRequest: _TypeAlias = UploadSourceRequest  # noqa: Y015

@_typing.final
class UploadSourceResponse(_message.Message):
    """Upload result returned after stream completion."""

    DESCRIPTOR: _descriptor.Descriptor

    UPLOAD_ID_FIELD_NUMBER: _builtins.int
    SIZE_BYTES_FIELD_NUMBER: _builtins.int
    SHA256_FIELD_NUMBER: _builtins.int
    upload_id: _builtins.str
    """Stable identifier for uploaded source archive."""
    size_bytes: _builtins.int
    """Uploaded size in bytes."""
    sha256: _builtins.str
    """SHA-256 digest of uploaded content."""
    def __init__(
        self,
        *,
        upload_id: _builtins.str = ...,
        size_bytes: _builtins.int = ...,
        sha256: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sha256", b"sha256", "size_bytes", b"size_bytes", "upload_id", b"upload_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UploadSourceResponse: _TypeAlias = UploadSourceResponse  # noqa: Y015
