# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hackarena/submission/v1/upload.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'hackarena/submission/v1/upload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$hackarena/submission/v1/upload.proto\x12\x17hackarena.submission.v1\"3\n\x14UploadSourceMetadata\x12\x1b\n\tfile_name\x18\x01 \x01(\tR\x08\x66ileName\"\x85\x01\n\x13UploadSourceRequest\x12K\n\x08metadata\x18\x01 \x01(\x0b\x32-.hackarena.submission.v1.UploadSourceMetadataH\x00R\x08metadata\x12\x16\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00R\x05\x63hunkB\t\n\x07payload\"j\n\x14UploadSourceResponse\x12\x1b\n\tupload_id\x18\x01 \x01(\tR\x08uploadId\x12\x1d\n\nsize_bytes\x18\x02 \x01(\x04R\tsizeBytes\x12\x16\n\x06sha256\x18\x03 \x01(\tR\x06sha256B\x1a\xaa\x02\x17HackArena.Submission.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hackarena.submission.v1.upload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027HackArena.Submission.V1'
  _globals['_UPLOADSOURCEMETADATA']._serialized_start=65
  _globals['_UPLOADSOURCEMETADATA']._serialized_end=116
  _globals['_UPLOADSOURCEREQUEST']._serialized_start=119
  _globals['_UPLOADSOURCEREQUEST']._serialized_end=252
  _globals['_UPLOADSOURCERESPONSE']._serialized_start=254
  _globals['_UPLOADSOURCERESPONSE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
