# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hackarena3.proto.hackarena.platform.teams.v1 import teams_pb2 as hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2


class TeamsServiceStub(object):
    """Team read operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTeam = channel.unary_unary(
                '/hackarena.platform.teams.v1.TeamsService/GetTeam',
                request_serializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamRequest.SerializeToString,
                response_deserializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamResponse.FromString,
                _registered_method=True)
        self.GetTeamByUser = channel.unary_unary(
                '/hackarena.platform.teams.v1.TeamsService/GetTeamByUser',
                request_serializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamByUserRequest.SerializeToString,
                response_deserializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamByUserResponse.FromString,
                _registered_method=True)
        self.ListTeams = channel.unary_unary(
                '/hackarena.platform.teams.v1.TeamsService/ListTeams',
                request_serializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.ListTeamsRequest.SerializeToString,
                response_deserializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.ListTeamsResponse.FromString,
                _registered_method=True)
        self.GetMyTeam = channel.unary_unary(
                '/hackarena.platform.teams.v1.TeamsService/GetMyTeam',
                request_serializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetMyTeamRequest.SerializeToString,
                response_deserializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetMyTeamResponse.FromString,
                _registered_method=True)


class TeamsServiceServicer(object):
    """Team read operations.
    """

    def GetTeam(self, request, context):
        """Get a team by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeamByUser(self, request, context):
        """Get team of a given user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeams(self, request, context):
        """List teams with filters and pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyTeam(self, request, context):
        """Get the caller's team.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeamsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeam,
                    request_deserializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamRequest.FromString,
                    response_serializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamResponse.SerializeToString,
            ),
            'GetTeamByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeamByUser,
                    request_deserializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamByUserRequest.FromString,
                    response_serializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamByUserResponse.SerializeToString,
            ),
            'ListTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTeams,
                    request_deserializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.ListTeamsRequest.FromString,
                    response_serializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.ListTeamsResponse.SerializeToString,
            ),
            'GetMyTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyTeam,
                    request_deserializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetMyTeamRequest.FromString,
                    response_serializer=hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetMyTeamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hackarena.platform.teams.v1.TeamsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hackarena.platform.teams.v1.TeamsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TeamsService(object):
    """Team read operations.
    """

    @staticmethod
    def GetTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hackarena.platform.teams.v1.TeamsService/GetTeam',
            hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamRequest.SerializeToString,
            hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeamByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hackarena.platform.teams.v1.TeamsService/GetTeamByUser',
            hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamByUserRequest.SerializeToString,
            hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetTeamByUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hackarena.platform.teams.v1.TeamsService/ListTeams',
            hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.ListTeamsRequest.SerializeToString,
            hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.ListTeamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hackarena.platform.teams.v1.TeamsService/GetMyTeam',
            hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetMyTeamRequest.SerializeToString,
            hackarena_dot_platform_dot_teams_dot_v1_dot_teams__pb2.GetMyTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
