"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from hackarena3.proto.hackarena.platform.common.v1 import types_pb2 as _types_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _TeamMemberStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TeamMemberStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TeamMemberStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TEAM_MEMBER_STATUS_UNSPECIFIED: _TeamMemberStatus.ValueType  # 0
    """Default value."""
    TEAM_MEMBER_STATUS_INVITED: _TeamMemberStatus.ValueType  # 1
    """Invited, not yet accepted."""
    TEAM_MEMBER_STATUS_ACCEPTED: _TeamMemberStatus.ValueType  # 2
    """Active member."""
    TEAM_MEMBER_STATUS_REMOVED: _TeamMemberStatus.ValueType  # 3
    """Removed or left."""

class TeamMemberStatus(_TeamMemberStatus, metaclass=_TeamMemberStatusEnumTypeWrapper):
    """Membership lifecycle status."""

TEAM_MEMBER_STATUS_UNSPECIFIED: TeamMemberStatus.ValueType  # 0
"""Default value."""
TEAM_MEMBER_STATUS_INVITED: TeamMemberStatus.ValueType  # 1
"""Invited, not yet accepted."""
TEAM_MEMBER_STATUS_ACCEPTED: TeamMemberStatus.ValueType  # 2
"""Active member."""
TEAM_MEMBER_STATUS_REMOVED: TeamMemberStatus.ValueType  # 3
"""Removed or left."""
Global___TeamMemberStatus: _TypeAlias = TeamMemberStatus  # noqa: Y015

@_typing.final
class Team(_message.Message):
    """Team registered in HackArena."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    EDITIONS_FIELD_NUMBER: _builtins.int
    MEMBERS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Display name."""
    @_builtins.property
    def id(self) -> _types_pb2.Uuid:
        """Team identifier."""

    @_builtins.property
    def editions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Edition identifiers (e.g., "1", "2.5")."""

    @_builtins.property
    def members(self) -> _containers.RepeatedCompositeFieldContainer[Global___TeamMember]:
        """Members of the team."""

    def __init__(
        self,
        *,
        id: _types_pb2.Uuid | None = ...,
        name: _builtins.str = ...,
        editions: _abc.Iterable[_builtins.str] | None = ...,
        members: _abc.Iterable[Global___TeamMember] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["editions", b"editions", "id", b"id", "members", b"members", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Team: _TypeAlias = Team  # noqa: Y015

@_typing.final
class TeamMember(_message.Message):
    """Membership of a user in a team."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    IS_LEADER_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    is_leader: _builtins.bool
    """Leader flag."""
    status: Global___TeamMemberStatus.ValueType
    """Membership status."""
    @_builtins.property
    def id(self) -> _types_pb2.Uuid:
        """User identifier."""

    def __init__(
        self,
        *,
        id: _types_pb2.Uuid | None = ...,
        is_leader: _builtins.bool = ...,
        status: Global___TeamMemberStatus.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "is_leader", b"is_leader", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TeamMember: _TypeAlias = TeamMember  # noqa: Y015

@_typing.final
class TeamEvent(_message.Message):
    """Teamk details for an event"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    COLOR_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Display name"""
    code: _builtins.str
    """Short code"""
    color: _builtins.str
    """Color (hex / name)"""
    @_builtins.property
    def id(self) -> _types_pb2.Uuid:
        """Team identifier"""

    def __init__(
        self,
        *,
        id: _types_pb2.Uuid | None = ...,
        name: _builtins.str = ...,
        code: _builtins.str | None = ...,
        color: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_code", b"_code", "_color", b"_color", "code", b"code", "color", b"color", "id", b"id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_code", b"_code", "_color", b"_color", "code", b"code", "color", b"color", "id", b"id", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__code: _TypeAlias = _typing.Literal["code"]  # noqa: Y015
    _WhichOneofArgType__code: _TypeAlias = _typing.Literal["_code", b"_code"]  # noqa: Y015
    _WhichOneofReturnType__color: _TypeAlias = _typing.Literal["color"]  # noqa: Y015
    _WhichOneofArgType__color: _TypeAlias = _typing.Literal["_color", b"_color"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__code) -> _WhichOneofReturnType__code | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__color) -> _WhichOneofReturnType__color | None: ...

Global___TeamEvent: _TypeAlias = TeamEvent  # noqa: Y015

@_typing.final
class GetTeamRequest(_message.Message):
    """Get a team by id."""

    DESCRIPTOR: _descriptor.Descriptor

    TEAM_ID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def team_id(self) -> _types_pb2.Uuid:
        """Team identifier."""

    def __init__(
        self,
        *,
        team_id: _types_pb2.Uuid | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["team_id", b"team_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["team_id", b"team_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTeamRequest: _TypeAlias = GetTeamRequest  # noqa: Y015

@_typing.final
class GetTeamResponse(_message.Message):
    """GetTeam response."""

    DESCRIPTOR: _descriptor.Descriptor

    TEAM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def team(self) -> Global___Team:
        """Requested team."""

    def __init__(
        self,
        *,
        team: Global___Team | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["team", b"team"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["team", b"team"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTeamResponse: _TypeAlias = GetTeamResponse  # noqa: Y015

@_typing.final
class GetTeamByUserRequest(_message.Message):
    """Get a team by user id."""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    EDITION_FIELD_NUMBER: _builtins.int
    edition: _builtins.str
    """Optional edition filter."""
    @_builtins.property
    def user_id(self) -> _types_pb2.Uuid:
        """User identifier."""

    def __init__(
        self,
        *,
        user_id: _types_pb2.Uuid | None = ...,
        edition: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["user_id", b"user_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["edition", b"edition", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTeamByUserRequest: _TypeAlias = GetTeamByUserRequest  # noqa: Y015

@_typing.final
class GetTeamByUserResponse(_message.Message):
    """GetTeamByUser response."""

    DESCRIPTOR: _descriptor.Descriptor

    TEAM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def team(self) -> Global___Team:
        """Team of the requested user, if any."""

    def __init__(
        self,
        *,
        team: Global___Team | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["team", b"team"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["team", b"team"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTeamByUserResponse: _TypeAlias = GetTeamByUserResponse  # noqa: Y015

@_typing.final
class ListTeamsRequest(_message.Message):
    """List teams with optional filters."""

    DESCRIPTOR: _descriptor.Descriptor

    EDITIONS_FIELD_NUMBER: _builtins.int
    NAME_QUERY_FIELD_NUMBER: _builtins.int
    PAGE_FIELD_NUMBER: _builtins.int
    name_query: _builtins.str
    """Case-insensitive name substring query."""
    @_builtins.property
    def editions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Filter by editions."""

    @_builtins.property
    def page(self) -> _types_pb2.PageRequest:
        """Pagination."""

    def __init__(
        self,
        *,
        editions: _abc.Iterable[_builtins.str] | None = ...,
        name_query: _builtins.str = ...,
        page: _types_pb2.PageRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page", b"page"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["editions", b"editions", "name_query", b"name_query", "page", b"page"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListTeamsRequest: _TypeAlias = ListTeamsRequest  # noqa: Y015

@_typing.final
class ListTeamsResponse(_message.Message):
    """ListTeams response."""

    DESCRIPTOR: _descriptor.Descriptor

    TEAMS_FIELD_NUMBER: _builtins.int
    PAGE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def teams(self) -> _containers.RepeatedCompositeFieldContainer[Global___Team]:
        """Teams page."""

    @_builtins.property
    def page(self) -> _types_pb2.PageResponse:
        """Pagination metadata."""

    def __init__(
        self,
        *,
        teams: _abc.Iterable[Global___Team] | None = ...,
        page: _types_pb2.PageResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page", b"page"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page", b"page", "teams", b"teams"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListTeamsResponse: _TypeAlias = ListTeamsResponse  # noqa: Y015

@_typing.final
class GetMyTeamRequest(_message.Message):
    """Get team of the authenticated user."""

    DESCRIPTOR: _descriptor.Descriptor

    EDITION_FIELD_NUMBER: _builtins.int
    edition: _builtins.str
    """Optional edition filter."""
    def __init__(
        self,
        *,
        edition: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["edition", b"edition"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetMyTeamRequest: _TypeAlias = GetMyTeamRequest  # noqa: Y015

@_typing.final
class GetMyTeamResponse(_message.Message):
    """GetMyTeam response."""

    DESCRIPTOR: _descriptor.Descriptor

    TEAM_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def team(self) -> Global___Team:
        """The caller's team, if any."""

    def __init__(
        self,
        *,
        team: Global___Team | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["team", b"team"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["team", b"team"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetMyTeamResponse: _TypeAlias = GetMyTeamResponse  # noqa: Y015

@_typing.final
class GetEventTeamsRequest(_message.Message):
    """GetEventTeams request"""

    DESCRIPTOR: _descriptor.Descriptor

    EDITION_FIELD_NUMBER: _builtins.int
    edition: _builtins.str
    """Edition identifier (e.g., "1", "2.5")."""
    def __init__(
        self,
        *,
        edition: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["edition", b"edition"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetEventTeamsRequest: _TypeAlias = GetEventTeamsRequest  # noqa: Y015

@_typing.final
class GetEventTeamsResponse(_message.Message):
    """GetEventTeams response"""

    DESCRIPTOR: _descriptor.Descriptor

    TEAMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def teams(self) -> _containers.RepeatedCompositeFieldContainer[Global___TeamEvent]: ...
    def __init__(
        self,
        *,
        teams: _abc.Iterable[Global___TeamEvent] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["teams", b"teams"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetEventTeamsResponse: _TypeAlias = GetEventTeamsResponse  # noqa: Y015

@_typing.final
class GetTeamImageRequest(_message.Message):
    """Get image for team"""

    DESCRIPTOR: _descriptor.Descriptor

    TEAM_ID_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def team_id(self) -> _types_pb2.Uuid: ...
    def __init__(
        self,
        *,
        team_id: _types_pb2.Uuid | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["team_id", b"team_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["team_id", b"team_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTeamImageRequest: _TypeAlias = GetTeamImageRequest  # noqa: Y015

@_typing.final
class GetTeamImageResponse(_message.Message):
    """GetTeamImage response."""

    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    CONTENT_TYPE_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    """Raw image bytes.
    Note: Entire file is returned in-memory (no streaming).
    """
    content_type: _builtins.str
    """MIME type of the image (e.g., "image/png", "image/jpeg")."""
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        content_type: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content_type", b"content_type", "data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTeamImageResponse: _TypeAlias = GetTeamImageResponse  # noqa: Y015
