# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hackarena3.proto.hackarena.broker.v1 import broker_pb2 as hackarena_dot_broker_dot_v1_dot_broker__pb2


class BrokerServiceStub(object):
    """Service responsible for backend discovery between teammates.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterBackend = channel.unary_unary(
                '/hackarena.broker.v1.BrokerService/RegisterBackend',
                request_serializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.RegisterBackendRequest.SerializeToString,
                response_deserializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.RegisterBackendResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/hackarena.broker.v1.BrokerService/Heartbeat',
                request_serializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetTeamBackends = channel.unary_unary(
                '/hackarena.broker.v1.BrokerService/GetTeamBackends',
                request_serializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.GetTeamBackendsRequest.SerializeToString,
                response_deserializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.GetTeamBackendsResponse.FromString,
                _registered_method=True)
        self.WatchTeamBackends = channel.unary_stream(
                '/hackarena.broker.v1.BrokerService/WatchTeamBackends',
                request_serializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.WatchTeamBackendsRequest.SerializeToString,
                response_deserializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.WatchTeamBackendsResponse.FromString,
                _registered_method=True)


class BrokerServiceServicer(object):
    """Service responsible for backend discovery between teammates.
    """

    def RegisterBackend(self, request, context):
        """Registers a locally hosted backend.
        If the caller already has a backend in the team, it is replaced.
        local_ipv4_endpoints allows multiple candidate IPv4 addresses.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Keeps backend entry alive and validates backend_id/backend_secret pair.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeamBackends(self, request, context):
        """Returns alive teammate backends excluding caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchTeamBackends(self, request, context):
        """Streams full snapshots of alive teammate backends excluding caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterBackend': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterBackend,
                    request_deserializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.RegisterBackendRequest.FromString,
                    response_serializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.RegisterBackendResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.HeartbeatRequest.FromString,
                    response_serializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetTeamBackends': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeamBackends,
                    request_deserializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.GetTeamBackendsRequest.FromString,
                    response_serializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.GetTeamBackendsResponse.SerializeToString,
            ),
            'WatchTeamBackends': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTeamBackends,
                    request_deserializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.WatchTeamBackendsRequest.FromString,
                    response_serializer=hackarena_dot_broker_dot_v1_dot_broker__pb2.WatchTeamBackendsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hackarena.broker.v1.BrokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hackarena.broker.v1.BrokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrokerService(object):
    """Service responsible for backend discovery between teammates.
    """

    @staticmethod
    def RegisterBackend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hackarena.broker.v1.BrokerService/RegisterBackend',
            hackarena_dot_broker_dot_v1_dot_broker__pb2.RegisterBackendRequest.SerializeToString,
            hackarena_dot_broker_dot_v1_dot_broker__pb2.RegisterBackendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hackarena.broker.v1.BrokerService/Heartbeat',
            hackarena_dot_broker_dot_v1_dot_broker__pb2.HeartbeatRequest.SerializeToString,
            hackarena_dot_broker_dot_v1_dot_broker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeamBackends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hackarena.broker.v1.BrokerService/GetTeamBackends',
            hackarena_dot_broker_dot_v1_dot_broker__pb2.GetTeamBackendsRequest.SerializeToString,
            hackarena_dot_broker_dot_v1_dot_broker__pb2.GetTeamBackendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchTeamBackends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hackarena.broker.v1.BrokerService/WatchTeamBackends',
            hackarena_dot_broker_dot_v1_dot_broker__pb2.WatchTeamBackendsRequest.SerializeToString,
            hackarena_dot_broker_dot_v1_dot_broker__pb2.WatchTeamBackendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
