"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Vector3(_message.Message):
    """3D vector in meters."""

    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    Z_FIELD_NUMBER: _builtins.int
    x: _builtins.float
    y: _builtins.float
    z: _builtins.float
    def __init__(
        self,
        *,
        x: _builtins.float = ...,
        y: _builtins.float = ...,
        z: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["x", b"x", "y", b"y", "z", b"z"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Vector3: _TypeAlias = Vector3  # noqa: Y015

@_typing.final
class Quaternion(_message.Message):
    """Unit quaternion representing orientation."""

    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    Z_FIELD_NUMBER: _builtins.int
    W_FIELD_NUMBER: _builtins.int
    x: _builtins.float
    y: _builtins.float
    z: _builtins.float
    w: _builtins.float
    def __init__(
        self,
        *,
        x: _builtins.float = ...,
        y: _builtins.float = ...,
        z: _builtins.float = ...,
        w: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["w", b"w", "x", b"x", "y", b"y", "z", b"z"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Quaternion: _TypeAlias = Quaternion  # noqa: Y015

@_typing.final
class WheelAngles(_message.Message):
    """Front wheel steering angles in radians."""

    DESCRIPTOR: _descriptor.Descriptor

    FRONT_LEFT_RAD_FIELD_NUMBER: _builtins.int
    FRONT_RIGHT_RAD_FIELD_NUMBER: _builtins.int
    front_left_rad: _builtins.float
    front_right_rad: _builtins.float
    def __init__(
        self,
        *,
        front_left_rad: _builtins.float = ...,
        front_right_rad: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["front_left_rad", b"front_left_rad", "front_right_rad", b"front_right_rad"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WheelAngles: _TypeAlias = WheelAngles  # noqa: Y015

@_typing.final
class WheelSpeeds(_message.Message):
    """Wheel angular speeds in radians per second."""

    DESCRIPTOR: _descriptor.Descriptor

    FRONT_LEFT_RADPS_FIELD_NUMBER: _builtins.int
    FRONT_RIGHT_RADPS_FIELD_NUMBER: _builtins.int
    REAR_LEFT_RADPS_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_RADPS_FIELD_NUMBER: _builtins.int
    front_left_radps: _builtins.float
    front_right_radps: _builtins.float
    rear_left_radps: _builtins.float
    rear_right_radps: _builtins.float
    def __init__(
        self,
        *,
        front_left_radps: _builtins.float = ...,
        front_right_radps: _builtins.float = ...,
        rear_left_radps: _builtins.float = ...,
        rear_right_radps: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["front_left_radps", b"front_left_radps", "front_right_radps", b"front_right_radps", "rear_left_radps", b"rear_left_radps", "rear_right_radps", b"rear_right_radps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WheelSpeeds: _TypeAlias = WheelSpeeds  # noqa: Y015
