"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _RaceTableEntryStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RaceTableEntryStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RaceTableEntryStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RACE_TABLE_ENTRY_STATUS_UNSPECIFIED: _RaceTableEntryStatus.ValueType  # 0
    RACE_TABLE_ENTRY_STATUS_ACTIVE: _RaceTableEntryStatus.ValueType  # 1
    RACE_TABLE_ENTRY_STATUS_DNF: _RaceTableEntryStatus.ValueType  # 2

class RaceTableEntryStatus(_RaceTableEntryStatus, metaclass=_RaceTableEntryStatusEnumTypeWrapper):
    """Race table row status."""

RACE_TABLE_ENTRY_STATUS_UNSPECIFIED: RaceTableEntryStatus.ValueType  # 0
RACE_TABLE_ENTRY_STATUS_ACTIVE: RaceTableEntryStatus.ValueType  # 1
RACE_TABLE_ENTRY_STATUS_DNF: RaceTableEntryStatus.ValueType  # 2
Global___RaceTableEntryStatus: _TypeAlias = RaceTableEntryStatus  # noqa: Y015

@_typing.final
class SandboxRaceTableTarget(_message.Message):
    """Running sandbox target for race table query."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    sandbox_id: _builtins.str
    """Target active sandbox identifier."""
    def __init__(
        self,
        *,
        sandbox_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SandboxRaceTableTarget: _TypeAlias = SandboxRaceTableTarget  # noqa: Y015

@_typing.final
class OfficialRaceTableTarget(_message.Message):
    """Official race target for race table query."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___OfficialRaceTableTarget: _TypeAlias = OfficialRaceTableTarget  # noqa: Y015

@_typing.final
class RaceTableTarget(_message.Message):
    """Explicit race-table source target."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_FIELD_NUMBER: _builtins.int
    OFFICIAL_RACE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sandbox(self) -> Global___SandboxRaceTableTarget: ...
    @_builtins.property
    def official_race(self) -> Global___OfficialRaceTableTarget: ...
    def __init__(
        self,
        *,
        sandbox: Global___SandboxRaceTableTarget | None = ...,
        official_race: Global___OfficialRaceTableTarget | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["official_race", b"official_race", "sandbox", b"sandbox", "target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["official_race", b"official_race", "sandbox", b"sandbox", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_target: _TypeAlias = _typing.Literal["sandbox", "official_race"]  # noqa: Y015
    _WhichOneofArgType_target: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_target) -> _WhichOneofReturnType_target | None: ...

Global___RaceTableTarget: _TypeAlias = RaceTableTarget  # noqa: Y015

@_typing.final
class LocalBotIdentity(_message.Message):
    """Identity for bots in running sandbox tables."""

    DESCRIPTOR: _descriptor.Descriptor

    USER_ID_FIELD_NUMBER: _builtins.int
    USERNAME_FIELD_NUMBER: _builtins.int
    BOT_INDEX_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    """Stable local user identifier."""
    username: _builtins.str
    """Display username of participant who runs the bot."""
    bot_index: _builtins.int
    """Stable bot ordinal index in sandbox context."""
    def __init__(
        self,
        *,
        user_id: _builtins.str = ...,
        username: _builtins.str = ...,
        bot_index: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bot_index", b"bot_index", "user_id", b"user_id", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalBotIdentity: _TypeAlias = LocalBotIdentity  # noqa: Y015

@_typing.final
class TeamIdentity(_message.Message):
    """Identity for official race team entries."""

    DESCRIPTOR: _descriptor.Descriptor

    TEAM_ID_FIELD_NUMBER: _builtins.int
    TEAM_NAME_FIELD_NUMBER: _builtins.int
    team_id: _builtins.str
    """Stable team identifier."""
    team_name: _builtins.str
    """Display team name."""
    def __init__(
        self,
        *,
        team_id: _builtins.str = ...,
        team_name: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["team_id", b"team_id", "team_name", b"team_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TeamIdentity: _TypeAlias = TeamIdentity  # noqa: Y015

@_typing.final
class SandboxRaceTableEntry(_message.Message):
    """Single sandbox race table row."""

    DESCRIPTOR: _descriptor.Descriptor

    CAR_ID_FIELD_NUMBER: _builtins.int
    LOCAL_BOT_FIELD_NUMBER: _builtins.int
    TEAM_FIELD_NUMBER: _builtins.int
    car_id: _builtins.int
    """Vehicle identifier represented by this table row."""
    @_builtins.property
    def local_bot(self) -> Global___LocalBotIdentity: ...
    @_builtins.property
    def team(self) -> Global___TeamIdentity: ...
    def __init__(
        self,
        *,
        car_id: _builtins.int = ...,
        local_bot: Global___LocalBotIdentity | None = ...,
        team: Global___TeamIdentity | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["identity", b"identity", "local_bot", b"local_bot", "team", b"team"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["car_id", b"car_id", "identity", b"identity", "local_bot", b"local_bot", "team", b"team"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_identity: _TypeAlias = _typing.Literal["local_bot", "team"]  # noqa: Y015
    _WhichOneofArgType_identity: _TypeAlias = _typing.Literal["identity", b"identity"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_identity) -> _WhichOneofReturnType_identity | None: ...

Global___SandboxRaceTableEntry: _TypeAlias = SandboxRaceTableEntry  # noqa: Y015

@_typing.final
class OfficialRaceTableEntry(_message.Message):
    """Single official race table row."""

    DESCRIPTOR: _descriptor.Descriptor

    CAR_ID_FIELD_NUMBER: _builtins.int
    TEAM_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    GAP_TO_LEADER_MS_FIELD_NUMBER: _builtins.int
    LAPS_BEHIND_FIELD_NUMBER: _builtins.int
    IN_PIT_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    car_id: _builtins.int
    """Vehicle identifier represented by this table row."""
    position: _builtins.int
    """1-based position in table ordering."""
    gap_to_leader_ms: _builtins.int
    """Time gap to current leader in milliseconds."""
    laps_behind: _builtins.int
    """Number of laps behind leader."""
    in_pit: _builtins.bool
    """True when entry vehicle is currently in pit."""
    status: Global___RaceTableEntryStatus.ValueType
    """Official race row status."""
    @_builtins.property
    def team(self) -> Global___TeamIdentity:
        """Official race rows always use team identity."""

    def __init__(
        self,
        *,
        car_id: _builtins.int = ...,
        team: Global___TeamIdentity | None = ...,
        position: _builtins.int = ...,
        gap_to_leader_ms: _builtins.int | None = ...,
        laps_behind: _builtins.int = ...,
        in_pit: _builtins.bool = ...,
        status: Global___RaceTableEntryStatus.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_gap_to_leader_ms", b"_gap_to_leader_ms", "gap_to_leader_ms", b"gap_to_leader_ms", "team", b"team"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_gap_to_leader_ms", b"_gap_to_leader_ms", "car_id", b"car_id", "gap_to_leader_ms", b"gap_to_leader_ms", "in_pit", b"in_pit", "laps_behind", b"laps_behind", "position", b"position", "status", b"status", "team", b"team"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__gap_to_leader_ms: _TypeAlias = _typing.Literal["gap_to_leader_ms"]  # noqa: Y015
    _WhichOneofArgType__gap_to_leader_ms: _TypeAlias = _typing.Literal["_gap_to_leader_ms", b"_gap_to_leader_ms"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__gap_to_leader_ms) -> _WhichOneofReturnType__gap_to_leader_ms | None: ...

Global___OfficialRaceTableEntry: _TypeAlias = OfficialRaceTableEntry  # noqa: Y015

@_typing.final
class SandboxRaceTableSnapshot(_message.Message):
    """Full sandbox race table snapshot.
    Rows are sorted by sandbox join time (oldest first).
    """

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_FIELD_NUMBER: _builtins.int
    ENTRIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def target(self) -> Global___SandboxRaceTableTarget:
        """Source target used to produce this snapshot."""

    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___SandboxRaceTableEntry]: ...
    def __init__(
        self,
        *,
        target: Global___SandboxRaceTableTarget | None = ...,
        entries: _abc.Iterable[Global___SandboxRaceTableEntry] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SandboxRaceTableSnapshot: _TypeAlias = SandboxRaceTableSnapshot  # noqa: Y015

@_typing.final
class OfficialRaceTableSnapshot(_message.Message):
    """Full official race table snapshot.
    Rows are sorted by backend classification:
    - ACTIVE rows first (more completed laps first, then farther progress on current lap),
    - then DNF rows.
    Position field must match row order.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_FIELD_NUMBER: _builtins.int
    ENTRIES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def target(self) -> Global___OfficialRaceTableTarget:
        """Source target used to produce this snapshot."""

    @_builtins.property
    def entries(self) -> _containers.RepeatedCompositeFieldContainer[Global___OfficialRaceTableEntry]: ...
    def __init__(
        self,
        *,
        target: Global___OfficialRaceTableTarget | None = ...,
        entries: _abc.Iterable[Global___OfficialRaceTableEntry] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["entries", b"entries", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OfficialRaceTableSnapshot: _TypeAlias = OfficialRaceTableSnapshot  # noqa: Y015

@_typing.final
class RaceTableSnapshot(_message.Message):
    """Full race table snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_FIELD_NUMBER: _builtins.int
    OFFICIAL_RACE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sandbox(self) -> Global___SandboxRaceTableSnapshot: ...
    @_builtins.property
    def official_race(self) -> Global___OfficialRaceTableSnapshot: ...
    def __init__(
        self,
        *,
        sandbox: Global___SandboxRaceTableSnapshot | None = ...,
        official_race: Global___OfficialRaceTableSnapshot | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["official_race", b"official_race", "sandbox", b"sandbox", "snapshot", b"snapshot"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["official_race", b"official_race", "sandbox", b"sandbox", "snapshot", b"snapshot"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_snapshot: _TypeAlias = _typing.Literal["sandbox", "official_race"]  # noqa: Y015
    _WhichOneofArgType_snapshot: _TypeAlias = _typing.Literal["snapshot", b"snapshot"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_snapshot) -> _WhichOneofReturnType_snapshot | None: ...

Global___RaceTableSnapshot: _TypeAlias = RaceTableSnapshot  # noqa: Y015

@_typing.final
class GetRaceTableRequest(_message.Message):
    """Request for current race table snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def target(self) -> Global___RaceTableTarget:
        """Required source target."""

    def __init__(
        self,
        *,
        target: Global___RaceTableTarget | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRaceTableRequest: _TypeAlias = GetRaceTableRequest  # noqa: Y015

@_typing.final
class GetRaceTableResponse(_message.Message):
    """Response with current race table snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    SNAPSHOT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def snapshot(self) -> Global___RaceTableSnapshot: ...
    def __init__(
        self,
        *,
        snapshot: Global___RaceTableSnapshot | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["snapshot", b"snapshot"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["snapshot", b"snapshot"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRaceTableResponse: _TypeAlias = GetRaceTableResponse  # noqa: Y015

@_typing.final
class StreamRaceTableRequest(_message.Message):
    """Stream request for race table updates."""

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def target(self) -> Global___RaceTableTarget:
        """Required source target."""

    def __init__(
        self,
        *,
        target: Global___RaceTableTarget | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamRaceTableRequest: _TypeAlias = StreamRaceTableRequest  # noqa: Y015

@_typing.final
class RaceTableEvent(_message.Message):
    """Stream event carrying a full race table snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    SNAPSHOT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def snapshot(self) -> Global___RaceTableSnapshot: ...
    def __init__(
        self,
        *,
        snapshot: Global___RaceTableSnapshot | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["snapshot", b"snapshot"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["snapshot", b"snapshot"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RaceTableEvent: _TypeAlias = RaceTableEvent  # noqa: Y015

@_typing.final
class StreamRaceTableResponse(_message.Message):
    """Response envelope for race table stream updates."""

    DESCRIPTOR: _descriptor.Descriptor

    EVENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def event(self) -> Global___RaceTableEvent: ...
    def __init__(
        self,
        *,
        event: Global___RaceTableEvent | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamRaceTableResponse: _TypeAlias = StreamRaceTableResponse  # noqa: Y015
