"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from hackarena3.proto.race.v1 import runtime_settings_pb2 as _runtime_settings_pb2
from hackarena3.proto.weather.v1 import weather_pb2 as _weather_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _LocalTimeOfDayMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LocalTimeOfDayModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LocalTimeOfDayMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LOCAL_TIME_OF_DAY_MODE_UNSPECIFIED: _LocalTimeOfDayMode.ValueType  # 0
    LOCAL_TIME_OF_DAY_MODE_FIXED_PRESET: _LocalTimeOfDayMode.ValueType  # 1
    """Use fixed_preset from LocalTimeOfDaySettings."""
    LOCAL_TIME_OF_DAY_MODE_AUTO_BY_LOCAL_TIME: _LocalTimeOfDayMode.ValueType  # 2
    """Resolve preset from backend local system time."""

class LocalTimeOfDayMode(_LocalTimeOfDayMode, metaclass=_LocalTimeOfDayModeEnumTypeWrapper):
    """Local runtime time-of-day resolution mode."""

LOCAL_TIME_OF_DAY_MODE_UNSPECIFIED: LocalTimeOfDayMode.ValueType  # 0
LOCAL_TIME_OF_DAY_MODE_FIXED_PRESET: LocalTimeOfDayMode.ValueType  # 1
"""Use fixed_preset from LocalTimeOfDaySettings."""
LOCAL_TIME_OF_DAY_MODE_AUTO_BY_LOCAL_TIME: LocalTimeOfDayMode.ValueType  # 2
"""Resolve preset from backend local system time."""
Global___LocalTimeOfDayMode: _TypeAlias = LocalTimeOfDayMode  # noqa: Y015

@_typing.final
class LocalTimeOfDaySettings(_message.Message):
    """Local runtime time-of-day settings."""

    DESCRIPTOR: _descriptor.Descriptor

    MODE_FIELD_NUMBER: _builtins.int
    FIXED_PRESET_FIELD_NUMBER: _builtins.int
    mode: Global___LocalTimeOfDayMode.ValueType
    fixed_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType
    """Used when mode is LOCAL_TIME_OF_DAY_MODE_FIXED_PRESET."""
    def __init__(
        self,
        *,
        mode: Global___LocalTimeOfDayMode.ValueType = ...,
        fixed_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fixed_preset", b"fixed_preset", "mode", b"mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalTimeOfDaySettings: _TypeAlias = LocalTimeOfDaySettings  # noqa: Y015

@_typing.final
class LocalWeatherSettings(_message.Message):
    """Local runtime weather settings."""

    DESCRIPTOR: _descriptor.Descriptor

    WEATHER_TYPE_FIELD_NUMBER: _builtins.int
    TEMPERATURE_C_FIELD_NUMBER: _builtins.int
    weather_type: _weather_pb2.WeatherType.ValueType
    temperature_c: _builtins.int
    """Air temperature in Celsius degrees."""
    def __init__(
        self,
        *,
        weather_type: _weather_pb2.WeatherType.ValueType = ...,
        temperature_c: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["temperature_c", b"temperature_c", "weather_type", b"weather_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalWeatherSettings: _TypeAlias = LocalWeatherSettings  # noqa: Y015
