"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from hackarena3.proto.race.v1 import runtime_settings_pb2 as _runtime_settings_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ScheduleSandboxActivationRequest(_message.Message):
    """Admin request to schedule sandbox activation/deactivation."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    ACTIVATE_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    EFFECTIVE_AT_UTC_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    activate: _builtins.bool
    """true = activate target sandbox, false = deactivate target sandbox."""
    sandbox_id: _builtins.str
    """Target sandbox identifier for activation/deactivation operation."""
    @_builtins.property
    def effective_at_utc(self) -> _timestamp_pb2.Timestamp:
        """Optional execution time in UTC.
        If unset, change is applied immediately.
        At most one pending operation can exist per sandbox_id.
        Scheduling again for same sandbox_id replaces previous pending operation.
        """

    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        activate: _builtins.bool = ...,
        sandbox_id: _builtins.str = ...,
        effective_at_utc: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["effective_at_utc", b"effective_at_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activate", b"activate", "effective_at_utc", b"effective_at_utc", "expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScheduleSandboxActivationRequest: _TypeAlias = ScheduleSandboxActivationRequest  # noqa: Y015

@_typing.final
class ScheduleSandboxActivationResponse(_message.Message):
    """Scheduled activation/deactivation response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    ACTIVATE_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    EFFECTIVE_AT_UTC_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    activate: _builtins.bool
    """true = target sandbox will be active, false = target sandbox will be inactive."""
    sandbox_id: _builtins.str
    """Target sandbox identifier for activation/deactivation operation."""
    @_builtins.property
    def effective_at_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp when change becomes effective."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        activate: _builtins.bool = ...,
        sandbox_id: _builtins.str = ...,
        effective_at_utc: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["effective_at_utc", b"effective_at_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activate", b"activate", "effective_at_utc", b"effective_at_utc", "revision", b"revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ScheduleSandboxActivationResponse: _TypeAlias = ScheduleSandboxActivationResponse  # noqa: Y015

@_typing.final
class CancelSandboxActivationScheduleRequest(_message.Message):
    """Admin request to cancel pending sandbox activation/deactivation schedule."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    sandbox_id: _builtins.str
    """Target sandbox identifier whose pending operation should be canceled."""
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CancelSandboxActivationScheduleRequest: _TypeAlias = CancelSandboxActivationScheduleRequest  # noqa: Y015

@_typing.final
class CancelSandboxActivationScheduleResponse(_message.Message):
    """Cancel pending sandbox activation/deactivation schedule response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    CANCELED_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    sandbox_id: _builtins.str
    """Target sandbox identifier."""
    canceled: _builtins.bool
    """true if a pending operation existed and was canceled."""
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        canceled: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["canceled", b"canceled", "revision", b"revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CancelSandboxActivationScheduleResponse: _TypeAlias = CancelSandboxActivationScheduleResponse  # noqa: Y015

@_typing.final
class AdminSandboxRuntimeInfo(_message.Message):
    """Active sandbox runtime details (admin view)."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    SANDBOX_NAME_FIELD_NUMBER: _builtins.int
    MAP_ID_FIELD_NUMBER: _builtins.int
    ACTIVE_TIME_OF_DAY_PRESET_FIELD_NUMBER: _builtins.int
    GHOST_MODE_FIELD_NUMBER: _builtins.int
    STARTED_AT_UTC_FIELD_NUMBER: _builtins.int
    CLOSES_AT_UTC_FIELD_NUMBER: _builtins.int
    sandbox_id: _builtins.str
    """Active sandbox identifier."""
    sandbox_name: _builtins.str
    """Active sandbox display name."""
    map_id: _builtins.str
    """Active sandbox map identifier."""
    active_time_of_day_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType
    """Active in-session time-of-day preset."""
    @_builtins.property
    def ghost_mode(self) -> _runtime_settings_pb2.GhostModeSettings:
        """Active ghost mode behavior."""

    @_builtins.property
    def started_at_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp when sandbox session started."""

    @_builtins.property
    def closes_at_utc(self) -> _timestamp_pb2.Timestamp:
        """Planned close timestamp if shutdown is scheduled."""

    def __init__(
        self,
        *,
        sandbox_id: _builtins.str = ...,
        sandbox_name: _builtins.str = ...,
        map_id: _builtins.str = ...,
        active_time_of_day_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType = ...,
        ghost_mode: _runtime_settings_pb2.GhostModeSettings | None = ...,
        started_at_utc: _timestamp_pb2.Timestamp | None = ...,
        closes_at_utc: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["closes_at_utc", b"closes_at_utc", "ghost_mode", b"ghost_mode", "started_at_utc", b"started_at_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_time_of_day_preset", b"active_time_of_day_preset", "closes_at_utc", b"closes_at_utc", "ghost_mode", b"ghost_mode", "map_id", b"map_id", "sandbox_id", b"sandbox_id", "sandbox_name", b"sandbox_name", "started_at_utc", b"started_at_utc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AdminSandboxRuntimeInfo: _TypeAlias = AdminSandboxRuntimeInfo  # noqa: Y015

@_typing.final
class AdminPendingSandboxOperation(_message.Message):
    """Pending sandbox activation/deactivation operation (admin view)."""

    DESCRIPTOR: _descriptor.Descriptor

    ACTIVATE_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    EXECUTE_AT_UTC_FIELD_NUMBER: _builtins.int
    activate: _builtins.bool
    """At most one pending entry can exist for each sandbox_id.
    true = activate sandbox, false = deactivate sandbox.
    """
    sandbox_id: _builtins.str
    """Target sandbox identifier for activation operation."""
    @_builtins.property
    def execute_at_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp when pending operation will execute."""

    def __init__(
        self,
        *,
        activate: _builtins.bool = ...,
        sandbox_id: _builtins.str = ...,
        execute_at_utc: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["execute_at_utc", b"execute_at_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activate", b"activate", "execute_at_utc", b"execute_at_utc", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AdminPendingSandboxOperation: _TypeAlias = AdminPendingSandboxOperation  # noqa: Y015

@_typing.final
class AdminSandboxRuntimeMode(_message.Message):
    """Admin runtime data for sandbox activity mode."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOXES_FIELD_NUMBER: _builtins.int
    PENDING_SANDBOX_OPERATIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sandboxes(self) -> _containers.RepeatedCompositeFieldContainer[Global___AdminSandboxRuntimeInfo]:
        """Active sandboxes for sandbox activity mode."""

    @_builtins.property
    def pending_sandbox_operations(self) -> _containers.RepeatedCompositeFieldContainer[Global___AdminPendingSandboxOperation]:
        """Pending sandbox activation/deactivation operations.
        Max one entry per sandbox_id.
        """

    def __init__(
        self,
        *,
        sandboxes: _abc.Iterable[Global___AdminSandboxRuntimeInfo] | None = ...,
        pending_sandbox_operations: _abc.Iterable[Global___AdminPendingSandboxOperation] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pending_sandbox_operations", b"pending_sandbox_operations", "sandboxes", b"sandboxes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AdminSandboxRuntimeMode: _TypeAlias = AdminSandboxRuntimeMode  # noqa: Y015

@_typing.final
class AdminOfficialRaceStagingState(_message.Message):
    """Admin view of official race staging phase."""

    DESCRIPTOR: _descriptor.Descriptor

    READY_PLAYER_COUNT_FIELD_NUMBER: _builtins.int
    EXPECTED_PLAYER_COUNT_FIELD_NUMBER: _builtins.int
    ready_player_count: _builtins.int
    """Number of participants ready to start."""
    expected_player_count: _builtins.int
    """Total number of participants expected to join this race."""
    def __init__(
        self,
        *,
        ready_player_count: _builtins.int = ...,
        expected_player_count: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_player_count", b"expected_player_count", "ready_player_count", b"ready_player_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AdminOfficialRaceStagingState: _TypeAlias = AdminOfficialRaceStagingState  # noqa: Y015

@_typing.final
class AdminOfficialRaceCountdownState(_message.Message):
    """Admin view of official race countdown phase."""

    DESCRIPTOR: _descriptor.Descriptor

    COUNTDOWN_END_AT_UTC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def countdown_end_at_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp when countdown ends and race enters running phase."""

    def __init__(
        self,
        *,
        countdown_end_at_utc: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["countdown_end_at_utc", b"countdown_end_at_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["countdown_end_at_utc", b"countdown_end_at_utc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AdminOfficialRaceCountdownState: _TypeAlias = AdminOfficialRaceCountdownState  # noqa: Y015

@_typing.final
class AdminOfficialRaceRunningState(_message.Message):
    """Admin view of official race running phase."""

    DESCRIPTOR: _descriptor.Descriptor

    PLANNED_END_AT_UTC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def planned_end_at_utc(self) -> _timestamp_pb2.Timestamp:
        """Planned UTC datetime when running phase should end."""

    def __init__(
        self,
        *,
        planned_end_at_utc: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["planned_end_at_utc", b"planned_end_at_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["planned_end_at_utc", b"planned_end_at_utc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AdminOfficialRaceRunningState: _TypeAlias = AdminOfficialRaceRunningState  # noqa: Y015

@_typing.final
class AdminOfficialRaceFinishedState(_message.Message):
    """Admin view of official race finished phase."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___AdminOfficialRaceFinishedState: _TypeAlias = AdminOfficialRaceFinishedState  # noqa: Y015

@_typing.final
class AdminOfficialRaceAbortedState(_message.Message):
    """Admin view of official race aborted phase."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___AdminOfficialRaceAbortedState: _TypeAlias = AdminOfficialRaceAbortedState  # noqa: Y015

@_typing.final
class AdminOfficialRaceRuntimeInfo(_message.Message):
    """Active official race runtime details (admin view)."""

    DESCRIPTOR: _descriptor.Descriptor

    RACE_ID_FIELD_NUMBER: _builtins.int
    RACE_NAME_FIELD_NUMBER: _builtins.int
    MAP_ID_FIELD_NUMBER: _builtins.int
    START_TIME_UTC_FIELD_NUMBER: _builtins.int
    RACE_DURATION_SEC_FIELD_NUMBER: _builtins.int
    STAGING_FIELD_NUMBER: _builtins.int
    COUNTDOWN_FIELD_NUMBER: _builtins.int
    RUNNING_FIELD_NUMBER: _builtins.int
    FINISHED_FIELD_NUMBER: _builtins.int
    ABORTED_FIELD_NUMBER: _builtins.int
    race_id: _builtins.str
    """Active official race identifier."""
    race_name: _builtins.str
    """Active official race display name."""
    map_id: _builtins.str
    """Active official race map identifier."""
    race_duration_sec: _builtins.int
    """Configured race duration in seconds, counted from running phase start."""
    @_builtins.property
    def start_time_utc(self) -> _timestamp_pb2.Timestamp:
        """Scheduled UTC datetime when this race entered staging phase."""

    @_builtins.property
    def staging(self) -> Global___AdminOfficialRaceStagingState:
        """Staging phase details."""

    @_builtins.property
    def countdown(self) -> Global___AdminOfficialRaceCountdownState:
        """Countdown phase details."""

    @_builtins.property
    def running(self) -> Global___AdminOfficialRaceRunningState:
        """Running phase details."""

    @_builtins.property
    def finished(self) -> Global___AdminOfficialRaceFinishedState:
        """Finished phase details."""

    @_builtins.property
    def aborted(self) -> Global___AdminOfficialRaceAbortedState:
        """Aborted phase details."""

    def __init__(
        self,
        *,
        race_id: _builtins.str = ...,
        race_name: _builtins.str = ...,
        map_id: _builtins.str = ...,
        start_time_utc: _timestamp_pb2.Timestamp | None = ...,
        race_duration_sec: _builtins.int = ...,
        staging: Global___AdminOfficialRaceStagingState | None = ...,
        countdown: Global___AdminOfficialRaceCountdownState | None = ...,
        running: Global___AdminOfficialRaceRunningState | None = ...,
        finished: Global___AdminOfficialRaceFinishedState | None = ...,
        aborted: Global___AdminOfficialRaceAbortedState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["aborted", b"aborted", "countdown", b"countdown", "finished", b"finished", "phase_state", b"phase_state", "running", b"running", "staging", b"staging", "start_time_utc", b"start_time_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aborted", b"aborted", "countdown", b"countdown", "finished", b"finished", "map_id", b"map_id", "phase_state", b"phase_state", "race_duration_sec", b"race_duration_sec", "race_id", b"race_id", "race_name", b"race_name", "running", b"running", "staging", b"staging", "start_time_utc", b"start_time_utc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_phase_state: _TypeAlias = _typing.Literal["staging", "countdown", "running", "finished", "aborted"]  # noqa: Y015
    _WhichOneofArgType_phase_state: _TypeAlias = _typing.Literal["phase_state", b"phase_state"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_phase_state) -> _WhichOneofReturnType_phase_state | None: ...

Global___AdminOfficialRaceRuntimeInfo: _TypeAlias = AdminOfficialRaceRuntimeInfo  # noqa: Y015

@_typing.final
class AdminRuntimeState(_message.Message):
    """Runtime state of activity mode and active sandboxes (admin view)."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SERVER_TIME_UTC_FIELD_NUMBER: _builtins.int
    OFFICIAL_RACE_FIELD_NUMBER: _builtins.int
    SANDBOX_MODE_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    @_builtins.property
    def server_time_utc(self) -> _timestamp_pb2.Timestamp:
        """Server UTC timestamp."""

    @_builtins.property
    def official_race(self) -> Global___AdminOfficialRaceRuntimeInfo:
        """Official race runtime mode."""

    @_builtins.property
    def sandbox_mode(self) -> Global___AdminSandboxRuntimeMode:
        """Sandbox runtime mode."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        server_time_utc: _timestamp_pb2.Timestamp | None = ...,
        official_race: Global___AdminOfficialRaceRuntimeInfo | None = ...,
        sandbox_mode: Global___AdminSandboxRuntimeMode | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["active_mode", b"active_mode", "official_race", b"official_race", "sandbox_mode", b"sandbox_mode", "server_time_utc", b"server_time_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_mode", b"active_mode", "official_race", b"official_race", "revision", b"revision", "sandbox_mode", b"sandbox_mode", "server_time_utc", b"server_time_utc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_active_mode: _TypeAlias = _typing.Literal["official_race", "sandbox_mode"]  # noqa: Y015
    _WhichOneofArgType_active_mode: _TypeAlias = _typing.Literal["active_mode", b"active_mode"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_active_mode) -> _WhichOneofReturnType_active_mode | None: ...

Global___AdminRuntimeState: _TypeAlias = AdminRuntimeState  # noqa: Y015

@_typing.final
class GetAdminRuntimeStateRequest(_message.Message):
    """Request current runtime state (admin/internal)."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetAdminRuntimeStateRequest: _TypeAlias = GetAdminRuntimeStateRequest  # noqa: Y015

@_typing.final
class GetAdminRuntimeStateResponse(_message.Message):
    """Response with current runtime state (admin/internal)."""

    DESCRIPTOR: _descriptor.Descriptor

    STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def state(self) -> Global___AdminRuntimeState:
        """Current runtime state snapshot."""

    def __init__(
        self,
        *,
        state: Global___AdminRuntimeState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetAdminRuntimeStateResponse: _TypeAlias = GetAdminRuntimeStateResponse  # noqa: Y015

@_typing.final
class StartOfficialRaceCountdownRequest(_message.Message):
    """Admin request to start official race countdown."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    COUNTDOWN_SECONDS_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    race_id: _builtins.str
    """Target active official race identifier."""
    countdown_seconds: _builtins.int
    """Countdown duration in seconds.
    Can be used only when active race state is staging.
    """
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
        countdown_seconds: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["countdown_seconds", b"countdown_seconds", "expected_revision", b"expected_revision", "race_id", b"race_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StartOfficialRaceCountdownRequest: _TypeAlias = StartOfficialRaceCountdownRequest  # noqa: Y015

@_typing.final
class StartOfficialRaceCountdownResponse(_message.Message):
    """Official race countdown start response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    COUNTDOWN_END_AT_UTC_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    race_id: _builtins.str
    """Target active official race identifier."""
    @_builtins.property
    def countdown_end_at_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp when countdown ends and race enters running phase."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
        countdown_end_at_utc: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["countdown_end_at_utc", b"countdown_end_at_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["countdown_end_at_utc", b"countdown_end_at_utc", "race_id", b"race_id", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StartOfficialRaceCountdownResponse: _TypeAlias = StartOfficialRaceCountdownResponse  # noqa: Y015

@_typing.final
class CloseOfficialRaceSessionRequest(_message.Message):
    """Admin request to close ended official race session."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    race_id: _builtins.str
    """Target active official race identifier.
    Can be used only when active race state is finished or aborted.
    """
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "race_id", b"race_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CloseOfficialRaceSessionRequest: _TypeAlias = CloseOfficialRaceSessionRequest  # noqa: Y015

@_typing.final
class CloseOfficialRaceSessionResponse(_message.Message):
    """Official race session close response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    race_id: _builtins.str
    """Closed official race identifier."""
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["race_id", b"race_id", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CloseOfficialRaceSessionResponse: _TypeAlias = CloseOfficialRaceSessionResponse  # noqa: Y015

@_typing.final
class AbortOfficialRaceRequest(_message.Message):
    """Admin request to abort running official race session."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    race_id: _builtins.str
    """Target active official race identifier.
    Can be used only when active race state is running.
    """
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "race_id", b"race_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AbortOfficialRaceRequest: _TypeAlias = AbortOfficialRaceRequest  # noqa: Y015

@_typing.final
class AbortOfficialRaceResponse(_message.Message):
    """Official race abort response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    race_id: _builtins.str
    """Aborted official race identifier."""
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["race_id", b"race_id", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AbortOfficialRaceResponse: _TypeAlias = AbortOfficialRaceResponse  # noqa: Y015
