# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: race/v1/runtime_local_common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'race/v1/runtime_local_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hackarena3.proto.race.v1 import runtime_settings_pb2 as race_dot_v1_dot_runtime__settings__pb2
from hackarena3.proto.weather.v1 import weather_pb2 as weather_dot_v1_dot_weather__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"race/v1/runtime_local_common.proto\x12\x07race.v1\x1a\x1erace/v1/runtime_settings.proto\x1a\x18weather/v1/weather.proto\"\x8d\x01\n\x16LocalTimeOfDaySettings\x12/\n\x04mode\x18\x01 \x01(\x0e\x32\x1b.race.v1.LocalTimeOfDayModeR\x04mode\x12\x42\n\x0c\x66ixed_preset\x18\x02 \x01(\x0e\x32\x1f.race.v1.RuntimeTimeOfDayPresetR\x0b\x66ixedPreset\"w\n\x14LocalWeatherSettings\x12:\n\x0cweather_type\x18\x01 \x01(\x0e\x32\x17.weather.v1.WeatherTypeR\x0bweatherType\x12#\n\rtemperature_c\x18\x02 \x01(\x05R\x0ctemperatureC*\x94\x01\n\x12LocalTimeOfDayMode\x12&\n\"LOCAL_TIME_OF_DAY_MODE_UNSPECIFIED\x10\x00\x12\'\n#LOCAL_TIME_OF_DAY_MODE_FIXED_PRESET\x10\x01\x12-\n)LOCAL_TIME_OF_DAY_MODE_AUTO_BY_LOCAL_TIME\x10\x02\x42\x14\xaa\x02\x11HA3.Proto.Race.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'race.v1.runtime_local_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\021HA3.Proto.Race.V1'
  _globals['_LOCALTIMEOFDAYMODE']._serialized_start=371
  _globals['_LOCALTIMEOFDAYMODE']._serialized_end=519
  _globals['_LOCALTIMEOFDAYSETTINGS']._serialized_start=106
  _globals['_LOCALTIMEOFDAYSETTINGS']._serialized_end=247
  _globals['_LOCALWEATHERSETTINGS']._serialized_start=249
  _globals['_LOCALWEATHERSETTINGS']._serialized_end=368
# @@protoc_insertion_point(module_scope)
