# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hackarena3.proto.race.v1 import runtime_admin_pb2 as race_dot_v1_dot_runtime__admin__pb2


class RuntimeAdminServiceStub(object):
    """Admin API for runtime controls.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScheduleSandboxActivation = channel.unary_unary(
                '/race.v1.RuntimeAdminService/ScheduleSandboxActivation',
                request_serializer=race_dot_v1_dot_runtime__admin__pb2.ScheduleSandboxActivationRequest.SerializeToString,
                response_deserializer=race_dot_v1_dot_runtime__admin__pb2.ScheduleSandboxActivationResponse.FromString,
                _registered_method=True)
        self.CancelSandboxActivationSchedule = channel.unary_unary(
                '/race.v1.RuntimeAdminService/CancelSandboxActivationSchedule',
                request_serializer=race_dot_v1_dot_runtime__admin__pb2.CancelSandboxActivationScheduleRequest.SerializeToString,
                response_deserializer=race_dot_v1_dot_runtime__admin__pb2.CancelSandboxActivationScheduleResponse.FromString,
                _registered_method=True)
        self.StartOfficialRaceCountdown = channel.unary_unary(
                '/race.v1.RuntimeAdminService/StartOfficialRaceCountdown',
                request_serializer=race_dot_v1_dot_runtime__admin__pb2.StartOfficialRaceCountdownRequest.SerializeToString,
                response_deserializer=race_dot_v1_dot_runtime__admin__pb2.StartOfficialRaceCountdownResponse.FromString,
                _registered_method=True)
        self.AbortOfficialRace = channel.unary_unary(
                '/race.v1.RuntimeAdminService/AbortOfficialRace',
                request_serializer=race_dot_v1_dot_runtime__admin__pb2.AbortOfficialRaceRequest.SerializeToString,
                response_deserializer=race_dot_v1_dot_runtime__admin__pb2.AbortOfficialRaceResponse.FromString,
                _registered_method=True)
        self.CloseOfficialRaceSession = channel.unary_unary(
                '/race.v1.RuntimeAdminService/CloseOfficialRaceSession',
                request_serializer=race_dot_v1_dot_runtime__admin__pb2.CloseOfficialRaceSessionRequest.SerializeToString,
                response_deserializer=race_dot_v1_dot_runtime__admin__pb2.CloseOfficialRaceSessionResponse.FromString,
                _registered_method=True)
        self.GetAdminRuntimeState = channel.unary_unary(
                '/race.v1.RuntimeAdminService/GetAdminRuntimeState',
                request_serializer=race_dot_v1_dot_runtime__admin__pb2.GetAdminRuntimeStateRequest.SerializeToString,
                response_deserializer=race_dot_v1_dot_runtime__admin__pb2.GetAdminRuntimeStateResponse.FromString,
                _registered_method=True)


class RuntimeAdminServiceServicer(object):
    """Admin API for runtime controls.
    """

    def ScheduleSandboxActivation(self, request, context):
        """Schedules sandbox activation/deactivation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSandboxActivationSchedule(self, request, context):
        """Cancels pending activation/deactivation schedule for target sandbox.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartOfficialRaceCountdown(self, request, context):
        """Starts countdown for active official race in staging phase.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortOfficialRace(self, request, context):
        """Aborts running official race session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseOfficialRaceSession(self, request, context):
        """Closes ended official race session (finished or aborted).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAdminRuntimeState(self, request, context):
        """Returns current runtime activity state (admin/internal).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScheduleSandboxActivation': grpc.unary_unary_rpc_method_handler(
                    servicer.ScheduleSandboxActivation,
                    request_deserializer=race_dot_v1_dot_runtime__admin__pb2.ScheduleSandboxActivationRequest.FromString,
                    response_serializer=race_dot_v1_dot_runtime__admin__pb2.ScheduleSandboxActivationResponse.SerializeToString,
            ),
            'CancelSandboxActivationSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSandboxActivationSchedule,
                    request_deserializer=race_dot_v1_dot_runtime__admin__pb2.CancelSandboxActivationScheduleRequest.FromString,
                    response_serializer=race_dot_v1_dot_runtime__admin__pb2.CancelSandboxActivationScheduleResponse.SerializeToString,
            ),
            'StartOfficialRaceCountdown': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOfficialRaceCountdown,
                    request_deserializer=race_dot_v1_dot_runtime__admin__pb2.StartOfficialRaceCountdownRequest.FromString,
                    response_serializer=race_dot_v1_dot_runtime__admin__pb2.StartOfficialRaceCountdownResponse.SerializeToString,
            ),
            'AbortOfficialRace': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortOfficialRace,
                    request_deserializer=race_dot_v1_dot_runtime__admin__pb2.AbortOfficialRaceRequest.FromString,
                    response_serializer=race_dot_v1_dot_runtime__admin__pb2.AbortOfficialRaceResponse.SerializeToString,
            ),
            'CloseOfficialRaceSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseOfficialRaceSession,
                    request_deserializer=race_dot_v1_dot_runtime__admin__pb2.CloseOfficialRaceSessionRequest.FromString,
                    response_serializer=race_dot_v1_dot_runtime__admin__pb2.CloseOfficialRaceSessionResponse.SerializeToString,
            ),
            'GetAdminRuntimeState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAdminRuntimeState,
                    request_deserializer=race_dot_v1_dot_runtime__admin__pb2.GetAdminRuntimeStateRequest.FromString,
                    response_serializer=race_dot_v1_dot_runtime__admin__pb2.GetAdminRuntimeStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'race.v1.RuntimeAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('race.v1.RuntimeAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeAdminService(object):
    """Admin API for runtime controls.
    """

    @staticmethod
    def ScheduleSandboxActivation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/race.v1.RuntimeAdminService/ScheduleSandboxActivation',
            race_dot_v1_dot_runtime__admin__pb2.ScheduleSandboxActivationRequest.SerializeToString,
            race_dot_v1_dot_runtime__admin__pb2.ScheduleSandboxActivationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSandboxActivationSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/race.v1.RuntimeAdminService/CancelSandboxActivationSchedule',
            race_dot_v1_dot_runtime__admin__pb2.CancelSandboxActivationScheduleRequest.SerializeToString,
            race_dot_v1_dot_runtime__admin__pb2.CancelSandboxActivationScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartOfficialRaceCountdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/race.v1.RuntimeAdminService/StartOfficialRaceCountdown',
            race_dot_v1_dot_runtime__admin__pb2.StartOfficialRaceCountdownRequest.SerializeToString,
            race_dot_v1_dot_runtime__admin__pb2.StartOfficialRaceCountdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortOfficialRace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/race.v1.RuntimeAdminService/AbortOfficialRace',
            race_dot_v1_dot_runtime__admin__pb2.AbortOfficialRaceRequest.SerializeToString,
            race_dot_v1_dot_runtime__admin__pb2.AbortOfficialRaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseOfficialRaceSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/race.v1.RuntimeAdminService/CloseOfficialRaceSession',
            race_dot_v1_dot_runtime__admin__pb2.CloseOfficialRaceSessionRequest.SerializeToString,
            race_dot_v1_dot_runtime__admin__pb2.CloseOfficialRaceSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAdminRuntimeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/race.v1.RuntimeAdminService/GetAdminRuntimeState',
            race_dot_v1_dot_runtime__admin__pb2.GetAdminRuntimeStateRequest.SerializeToString,
            race_dot_v1_dot_runtime__admin__pb2.GetAdminRuntimeStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
