"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from hackarena3.proto.race.v1 import runtime_local_common_pb2 as _runtime_local_common_pb2
from hackarena3.proto.race.v1 import runtime_settings_pb2 as _runtime_settings_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _LocalRacePhase:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LocalRacePhaseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LocalRacePhase.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LOCAL_RACE_PHASE_UNSPECIFIED: _LocalRacePhase.ValueType  # 0
    LOCAL_RACE_PHASE_STAGING: _LocalRacePhase.ValueType  # 1
    LOCAL_RACE_PHASE_COUNTDOWN: _LocalRacePhase.ValueType  # 2
    LOCAL_RACE_PHASE_RUNNING: _LocalRacePhase.ValueType  # 3
    LOCAL_RACE_PHASE_FINISHED: _LocalRacePhase.ValueType  # 4
    LOCAL_RACE_PHASE_ABORTED: _LocalRacePhase.ValueType  # 5

class LocalRacePhase(_LocalRacePhase, metaclass=_LocalRacePhaseEnumTypeWrapper):
    """Lifecycle phase of a standalone local race."""

LOCAL_RACE_PHASE_UNSPECIFIED: LocalRacePhase.ValueType  # 0
LOCAL_RACE_PHASE_STAGING: LocalRacePhase.ValueType  # 1
LOCAL_RACE_PHASE_COUNTDOWN: LocalRacePhase.ValueType  # 2
LOCAL_RACE_PHASE_RUNNING: LocalRacePhase.ValueType  # 3
LOCAL_RACE_PHASE_FINISHED: LocalRacePhase.ValueType  # 4
LOCAL_RACE_PHASE_ABORTED: LocalRacePhase.ValueType  # 5
Global___LocalRacePhase: _TypeAlias = LocalRacePhase  # noqa: Y015

@_typing.final
class LocalRaceConfigInput(_message.Message):
    """Local race configuration payload."""

    DESCRIPTOR: _descriptor.Descriptor

    RACE_NAME_FIELD_NUMBER: _builtins.int
    MAP_ID_FIELD_NUMBER: _builtins.int
    RACE_DURATION_SEC_FIELD_NUMBER: _builtins.int
    TIME_OF_DAY_FIELD_NUMBER: _builtins.int
    GHOST_MODE_FIELD_NUMBER: _builtins.int
    WEATHER_FIELD_NUMBER: _builtins.int
    MAX_PARTICIPANTS_FIELD_NUMBER: _builtins.int
    race_name: _builtins.str
    """Human-readable race name shown in frontend."""
    map_id: _builtins.str
    """Track/map identifier used by race simulation."""
    race_duration_sec: _builtins.int
    """Race duration in seconds, counted from running phase start."""
    max_participants: _builtins.int
    """Maximum number of joined participants."""
    @_builtins.property
    def time_of_day(self) -> _runtime_local_common_pb2.LocalTimeOfDaySettings: ...
    @_builtins.property
    def ghost_mode(self) -> _runtime_settings_pb2.GhostModeSettings: ...
    @_builtins.property
    def weather(self) -> _runtime_local_common_pb2.LocalWeatherSettings: ...
    def __init__(
        self,
        *,
        race_name: _builtins.str = ...,
        map_id: _builtins.str = ...,
        race_duration_sec: _builtins.int = ...,
        time_of_day: _runtime_local_common_pb2.LocalTimeOfDaySettings | None = ...,
        ghost_mode: _runtime_settings_pb2.GhostModeSettings | None = ...,
        weather: _runtime_local_common_pb2.LocalWeatherSettings | None = ...,
        max_participants: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ghost_mode", b"ghost_mode", "time_of_day", b"time_of_day", "weather", b"weather"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ghost_mode", b"ghost_mode", "map_id", b"map_id", "max_participants", b"max_participants", "race_duration_sec", b"race_duration_sec", "race_name", b"race_name", "time_of_day", b"time_of_day", "weather", b"weather"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalRaceConfigInput: _TypeAlias = LocalRaceConfigInput  # noqa: Y015

@_typing.final
class LocalRaceRuntimeInfo(_message.Message):
    """Active local race runtime details."""

    DESCRIPTOR: _descriptor.Descriptor

    RACE_ID_FIELD_NUMBER: _builtins.int
    RACE_NAME_FIELD_NUMBER: _builtins.int
    MAP_ID_FIELD_NUMBER: _builtins.int
    RACE_DURATION_SEC_FIELD_NUMBER: _builtins.int
    TIME_OF_DAY_FIELD_NUMBER: _builtins.int
    ACTIVE_TIME_OF_DAY_PRESET_FIELD_NUMBER: _builtins.int
    GHOST_MODE_FIELD_NUMBER: _builtins.int
    WEATHER_FIELD_NUMBER: _builtins.int
    PHASE_FIELD_NUMBER: _builtins.int
    CREATED_AT_UTC_FIELD_NUMBER: _builtins.int
    COUNTDOWN_END_AT_UTC_FIELD_NUMBER: _builtins.int
    RUNNING_STARTED_AT_UTC_FIELD_NUMBER: _builtins.int
    PLANNED_END_AT_UTC_FIELD_NUMBER: _builtins.int
    JOINED_PARTICIPANT_COUNT_FIELD_NUMBER: _builtins.int
    MAX_PARTICIPANTS_FIELD_NUMBER: _builtins.int
    race_id: _builtins.str
    """Active local race identifier."""
    race_name: _builtins.str
    """Active local race display name."""
    map_id: _builtins.str
    """Active local race map identifier."""
    race_duration_sec: _builtins.int
    """Race duration in seconds, counted from running phase start."""
    active_time_of_day_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType
    """Currently resolved in-session time-of-day preset."""
    phase: Global___LocalRacePhase.ValueType
    joined_participant_count: _builtins.int
    """Number of currently joined participants."""
    max_participants: _builtins.int
    """Maximum number of joined participants."""
    @_builtins.property
    def time_of_day(self) -> _runtime_local_common_pb2.LocalTimeOfDaySettings: ...
    @_builtins.property
    def ghost_mode(self) -> _runtime_settings_pb2.GhostModeSettings: ...
    @_builtins.property
    def weather(self) -> _runtime_local_common_pb2.LocalWeatherSettings: ...
    @_builtins.property
    def created_at_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp when local race runtime was created."""

    @_builtins.property
    def countdown_end_at_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp when countdown ends and race enters running phase."""

    @_builtins.property
    def running_started_at_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp when race entered running phase."""

    @_builtins.property
    def planned_end_at_utc(self) -> _timestamp_pb2.Timestamp:
        """Planned UTC timestamp when running phase should end."""

    def __init__(
        self,
        *,
        race_id: _builtins.str = ...,
        race_name: _builtins.str = ...,
        map_id: _builtins.str = ...,
        race_duration_sec: _builtins.int = ...,
        time_of_day: _runtime_local_common_pb2.LocalTimeOfDaySettings | None = ...,
        active_time_of_day_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType = ...,
        ghost_mode: _runtime_settings_pb2.GhostModeSettings | None = ...,
        weather: _runtime_local_common_pb2.LocalWeatherSettings | None = ...,
        phase: Global___LocalRacePhase.ValueType = ...,
        created_at_utc: _timestamp_pb2.Timestamp | None = ...,
        countdown_end_at_utc: _timestamp_pb2.Timestamp | None = ...,
        running_started_at_utc: _timestamp_pb2.Timestamp | None = ...,
        planned_end_at_utc: _timestamp_pb2.Timestamp | None = ...,
        joined_participant_count: _builtins.int = ...,
        max_participants: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["countdown_end_at_utc", b"countdown_end_at_utc", "created_at_utc", b"created_at_utc", "ghost_mode", b"ghost_mode", "planned_end_at_utc", b"planned_end_at_utc", "running_started_at_utc", b"running_started_at_utc", "time_of_day", b"time_of_day", "weather", b"weather"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_time_of_day_preset", b"active_time_of_day_preset", "countdown_end_at_utc", b"countdown_end_at_utc", "created_at_utc", b"created_at_utc", "ghost_mode", b"ghost_mode", "joined_participant_count", b"joined_participant_count", "map_id", b"map_id", "max_participants", b"max_participants", "phase", b"phase", "planned_end_at_utc", b"planned_end_at_utc", "race_duration_sec", b"race_duration_sec", "race_id", b"race_id", "race_name", b"race_name", "running_started_at_utc", b"running_started_at_utc", "time_of_day", b"time_of_day", "weather", b"weather"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalRaceRuntimeInfo: _TypeAlias = LocalRaceRuntimeInfo  # noqa: Y015

@_typing.final
class CreateLocalRaceRequest(_message.Message):
    """Request to create a local race in staging phase."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    @_builtins.property
    def config(self) -> Global___LocalRaceConfigInput: ...
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        config: Global___LocalRaceConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "expected_revision", b"expected_revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateLocalRaceRequest: _TypeAlias = CreateLocalRaceRequest  # noqa: Y015

@_typing.final
class CreateLocalRaceResponse(_message.Message):
    """Response with created local race runtime."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    @_builtins.property
    def race(self) -> Global___LocalRaceRuntimeInfo: ...
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race: Global___LocalRaceRuntimeInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["race", b"race"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["race", b"race", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateLocalRaceResponse: _TypeAlias = CreateLocalRaceResponse  # noqa: Y015

@_typing.final
class StartLocalRaceCountdownRequest(_message.Message):
    """Request to start countdown for a staged local race."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    COUNTDOWN_SECONDS_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    race_id: _builtins.str
    countdown_seconds: _builtins.int
    """Countdown duration in seconds. 0 starts the race immediately."""
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
        countdown_seconds: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["countdown_seconds", b"countdown_seconds", "expected_revision", b"expected_revision", "race_id", b"race_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StartLocalRaceCountdownRequest: _TypeAlias = StartLocalRaceCountdownRequest  # noqa: Y015

@_typing.final
class StartLocalRaceCountdownResponse(_message.Message):
    """Response with countdown start result."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    COUNTDOWN_END_AT_UTC_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    race_id: _builtins.str
    @_builtins.property
    def countdown_end_at_utc(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
        countdown_end_at_utc: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["countdown_end_at_utc", b"countdown_end_at_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["countdown_end_at_utc", b"countdown_end_at_utc", "race_id", b"race_id", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StartLocalRaceCountdownResponse: _TypeAlias = StartLocalRaceCountdownResponse  # noqa: Y015

@_typing.final
class AbortLocalRaceRequest(_message.Message):
    """Request to abort an active local race."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    race_id: _builtins.str
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "race_id", b"race_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AbortLocalRaceRequest: _TypeAlias = AbortLocalRaceRequest  # noqa: Y015

@_typing.final
class AbortLocalRaceResponse(_message.Message):
    """Response confirming local race abort."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    race_id: _builtins.str
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["race_id", b"race_id", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AbortLocalRaceResponse: _TypeAlias = AbortLocalRaceResponse  # noqa: Y015

@_typing.final
class CloseLocalRaceRequest(_message.Message):
    """Request to clear a finished or aborted local race runtime."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    race_id: _builtins.str
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "race_id", b"race_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CloseLocalRaceRequest: _TypeAlias = CloseLocalRaceRequest  # noqa: Y015

@_typing.final
class CloseLocalRaceResponse(_message.Message):
    """Response confirming local race close."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    race_id: _builtins.str
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["race_id", b"race_id", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CloseLocalRaceResponse: _TypeAlias = CloseLocalRaceResponse  # noqa: Y015
