"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from hackarena3.proto.race.v1 import runtime_settings_pb2 as _runtime_settings_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _StartPlacementMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StartPlacementModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_StartPlacementMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    START_PLACEMENT_MODE_UNSPECIFIED: _StartPlacementMode.ValueType  # 0
    """Default/unknown value."""
    START_PLACEMENT_MODE_RANDOM: _StartPlacementMode.ValueType  # 1
    """Randomized start order when race starts."""
    START_PLACEMENT_MODE_SCOREBOARD: _StartPlacementMode.ValueType  # 2
    """Start order follows current scoreboard (higher points first)."""
    START_PLACEMENT_MODE_REVERSED_SCOREBOARD: _StartPlacementMode.ValueType  # 3
    """Start order follows reverse scoreboard (higher points last)."""

class StartPlacementMode(_StartPlacementMode, metaclass=_StartPlacementModeEnumTypeWrapper):
    """Rule used to assign teams to start slots."""

START_PLACEMENT_MODE_UNSPECIFIED: StartPlacementMode.ValueType  # 0
"""Default/unknown value."""
START_PLACEMENT_MODE_RANDOM: StartPlacementMode.ValueType  # 1
"""Randomized start order when race starts."""
START_PLACEMENT_MODE_SCOREBOARD: StartPlacementMode.ValueType  # 2
"""Start order follows current scoreboard (higher points first)."""
START_PLACEMENT_MODE_REVERSED_SCOREBOARD: StartPlacementMode.ValueType  # 3
"""Start order follows reverse scoreboard (higher points last)."""
Global___StartPlacementMode: _TypeAlias = StartPlacementMode  # noqa: Y015

class _RaceTimeOfDayPreset:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RaceTimeOfDayPresetEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RaceTimeOfDayPreset.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RACE_TIME_OF_DAY_PRESET_UNSPECIFIED: _RaceTimeOfDayPreset.ValueType  # 0
    """Default/unknown value."""
    RACE_TIME_OF_DAY_PRESET_MORNING: _RaceTimeOfDayPreset.ValueType  # 1
    """Morning lighting preset."""
    RACE_TIME_OF_DAY_PRESET_NOON: _RaceTimeOfDayPreset.ValueType  # 2
    """Noon lighting preset."""
    RACE_TIME_OF_DAY_PRESET_EVENING: _RaceTimeOfDayPreset.ValueType  # 3
    """Evening lighting preset."""
    RACE_TIME_OF_DAY_PRESET_NIGHT: _RaceTimeOfDayPreset.ValueType  # 4
    """Night lighting preset."""

class RaceTimeOfDayPreset(_RaceTimeOfDayPreset, metaclass=_RaceTimeOfDayPresetEnumTypeWrapper):
    """In-game time-of-day preset used for race configuration."""

RACE_TIME_OF_DAY_PRESET_UNSPECIFIED: RaceTimeOfDayPreset.ValueType  # 0
"""Default/unknown value."""
RACE_TIME_OF_DAY_PRESET_MORNING: RaceTimeOfDayPreset.ValueType  # 1
"""Morning lighting preset."""
RACE_TIME_OF_DAY_PRESET_NOON: RaceTimeOfDayPreset.ValueType  # 2
"""Noon lighting preset."""
RACE_TIME_OF_DAY_PRESET_EVENING: RaceTimeOfDayPreset.ValueType  # 3
"""Evening lighting preset."""
RACE_TIME_OF_DAY_PRESET_NIGHT: RaceTimeOfDayPreset.ValueType  # 4
"""Night lighting preset."""
Global___RaceTimeOfDayPreset: _TypeAlias = RaceTimeOfDayPreset  # noqa: Y015

@_typing.final
class SandboxConfigInput(_message.Message):
    """Admin-provided sandbox configuration payload."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_NAME_FIELD_NUMBER: _builtins.int
    MAP_ID_FIELD_NUMBER: _builtins.int
    TIME_OF_DAY_PRESET_FIELD_NUMBER: _builtins.int
    GHOST_MODE_FIELD_NUMBER: _builtins.int
    sandbox_name: _builtins.str
    """Human-readable sandbox name shown in frontend."""
    map_id: _builtins.str
    """Track/map identifier used by sandbox simulation."""
    time_of_day_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType
    """Default in-game time-of-day preset for this sandbox."""
    @_builtins.property
    def ghost_mode(self) -> _runtime_settings_pb2.GhostModeSettings:
        """Ghost mode behavior."""

    def __init__(
        self,
        *,
        sandbox_name: _builtins.str = ...,
        map_id: _builtins.str = ...,
        time_of_day_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType = ...,
        ghost_mode: _runtime_settings_pb2.GhostModeSettings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ghost_mode", b"ghost_mode"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ghost_mode", b"ghost_mode", "map_id", b"map_id", "sandbox_name", b"sandbox_name", "time_of_day_preset", b"time_of_day_preset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SandboxConfigInput: _TypeAlias = SandboxConfigInput  # noqa: Y015

@_typing.final
class SandboxConfig(_message.Message):
    """Persisted sandbox configuration entry with backend-assigned identifier."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    sandbox_id: _builtins.str
    """Stable sandbox identifier."""
    @_builtins.property
    def config(self) -> Global___SandboxConfigInput:
        """User-provided sandbox configuration fields."""

    def __init__(
        self,
        *,
        sandbox_id: _builtins.str = ...,
        config: Global___SandboxConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SandboxConfig: _TypeAlias = SandboxConfig  # noqa: Y015

@_typing.final
class GetSandboxConfigsRequest(_message.Message):
    """Request for persisted sandbox configuration list."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetSandboxConfigsRequest: _TypeAlias = GetSandboxConfigsRequest  # noqa: Y015

@_typing.final
class GetSandboxConfigsResponse(_message.Message):
    """Response with persisted sandbox configuration list."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOXES_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    @_builtins.property
    def sandboxes(self) -> _containers.RepeatedCompositeFieldContainer[Global___SandboxConfig]:
        """Configured sandboxes."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandboxes: _abc.Iterable[Global___SandboxConfig] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandboxes", b"sandboxes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetSandboxConfigsResponse: _TypeAlias = GetSandboxConfigsResponse  # noqa: Y015

@_typing.final
class CreateSandboxConfigRequest(_message.Message):
    """Create single sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    @_builtins.property
    def config(self) -> Global___SandboxConfigInput:
        """New sandbox configuration payload."""

    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        config: Global___SandboxConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "expected_revision", b"expected_revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateSandboxConfigRequest: _TypeAlias = CreateSandboxConfigRequest  # noqa: Y015

@_typing.final
class CreateSandboxConfigResponse(_message.Message):
    """Created sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    @_builtins.property
    def sandbox(self) -> Global___SandboxConfig:
        """Created sandbox configuration entry."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox: Global___SandboxConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["sandbox", b"sandbox"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandbox", b"sandbox"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateSandboxConfigResponse: _TypeAlias = CreateSandboxConfigResponse  # noqa: Y015

@_typing.final
class UpdateSandboxConfigRequest(_message.Message):
    """Update single sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    sandbox_id: _builtins.str
    """Target sandbox identifier to update."""
    @_builtins.property
    def config(self) -> Global___SandboxConfigInput:
        """New sandbox configuration payload."""

    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        config: Global___SandboxConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateSandboxConfigRequest: _TypeAlias = UpdateSandboxConfigRequest  # noqa: Y015

@_typing.final
class UpdateSandboxConfigResponse(_message.Message):
    """Updated sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    @_builtins.property
    def sandbox(self) -> Global___SandboxConfig:
        """Updated sandbox configuration entry."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox: Global___SandboxConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["sandbox", b"sandbox"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandbox", b"sandbox"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateSandboxConfigResponse: _TypeAlias = UpdateSandboxConfigResponse  # noqa: Y015

@_typing.final
class DeleteSandboxConfigRequest(_message.Message):
    """Delete single sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    sandbox_id: _builtins.str
    """Target sandbox identifier to delete."""
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteSandboxConfigRequest: _TypeAlias = DeleteSandboxConfigRequest  # noqa: Y015

@_typing.final
class DeleteSandboxConfigResponse(_message.Message):
    """Delete confirmation."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    sandbox_id: _builtins.str
    """Deleted sandbox identifier."""
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteSandboxConfigResponse: _TypeAlias = DeleteSandboxConfigResponse  # noqa: Y015

@_typing.final
class UpdateSandboxTimeOfDayRequest(_message.Message):
    """Admin request for time-of-day preset update in sandbox configuration."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    PRESET_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    sandbox_id: _builtins.str
    """Target sandbox identifier."""
    preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType
    """New default in-game time-of-day preset for target sandbox."""
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "preset", b"preset", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateSandboxTimeOfDayRequest: _TypeAlias = UpdateSandboxTimeOfDayRequest  # noqa: Y015

@_typing.final
class UpdateSandboxTimeOfDayResponse(_message.Message):
    """Time-of-day preset update response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    PRESET_FIELD_NUMBER: _builtins.int
    APPLIED_AT_UTC_FIELD_NUMBER: _builtins.int
    APPLIED_TO_ACTIVE_RUNTIME_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    sandbox_id: _builtins.str
    """Target sandbox identifier."""
    preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType
    """Updated default in-game time-of-day preset."""
    applied_to_active_runtime: _builtins.bool
    """true if update was also applied to currently active runtime sandbox instance."""
    @_builtins.property
    def applied_at_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC timestamp when configuration update was applied."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType = ...,
        applied_at_utc: _timestamp_pb2.Timestamp | None = ...,
        applied_to_active_runtime: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["applied_at_utc", b"applied_at_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["applied_at_utc", b"applied_at_utc", "applied_to_active_runtime", b"applied_to_active_runtime", "preset", b"preset", "revision", b"revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateSandboxTimeOfDayResponse: _TypeAlias = UpdateSandboxTimeOfDayResponse  # noqa: Y015

@_typing.final
class RaceConfigInput(_message.Message):
    """Race configuration payload provided by admin tools."""

    DESCRIPTOR: _descriptor.Descriptor

    RACE_NAME_FIELD_NUMBER: _builtins.int
    START_TIME_UTC_FIELD_NUMBER: _builtins.int
    RACE_DURATION_SEC_FIELD_NUMBER: _builtins.int
    MAP_ID_FIELD_NUMBER: _builtins.int
    START_PLACEMENT_MODE_FIELD_NUMBER: _builtins.int
    POINTS_MULTIPLIER_FIXED_FIELD_NUMBER: _builtins.int
    TIME_OF_DAY_PRESET_FIELD_NUMBER: _builtins.int
    race_name: _builtins.str
    """Human-readable race name shown in frontend."""
    race_duration_sec: _builtins.int
    """Race duration in seconds, counted from running phase start."""
    map_id: _builtins.str
    """Track/map identifier used by race simulation."""
    start_placement_mode: Global___StartPlacementMode.ValueType
    """Team start placement policy."""
    points_multiplier_fixed: _builtins.float
    """Fixed points multiplier."""
    time_of_day_preset: Global___RaceTimeOfDayPreset.ValueType
    """In-game time-of-day preset."""
    @_builtins.property
    def start_time_utc(self) -> _timestamp_pb2.Timestamp:
        """UTC datetime when backend automatically enters staging phase for this race."""

    def __init__(
        self,
        *,
        race_name: _builtins.str = ...,
        start_time_utc: _timestamp_pb2.Timestamp | None = ...,
        race_duration_sec: _builtins.int = ...,
        map_id: _builtins.str = ...,
        start_placement_mode: Global___StartPlacementMode.ValueType = ...,
        points_multiplier_fixed: _builtins.float = ...,
        time_of_day_preset: Global___RaceTimeOfDayPreset.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["start_time_utc", b"start_time_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["map_id", b"map_id", "points_multiplier_fixed", b"points_multiplier_fixed", "race_duration_sec", b"race_duration_sec", "race_name", b"race_name", "start_placement_mode", b"start_placement_mode", "start_time_utc", b"start_time_utc", "time_of_day_preset", b"time_of_day_preset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RaceConfigInput: _TypeAlias = RaceConfigInput  # noqa: Y015

@_typing.final
class RaceConfig(_message.Message):
    """Persisted race configuration entry with backend-assigned identifier."""

    DESCRIPTOR: _descriptor.Descriptor

    RACE_ID_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    race_id: _builtins.str
    """Stable race identifier."""
    @_builtins.property
    def config(self) -> Global___RaceConfigInput:
        """User-provided race configuration fields."""

    def __init__(
        self,
        *,
        race_id: _builtins.str = ...,
        config: Global___RaceConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "race_id", b"race_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RaceConfig: _TypeAlias = RaceConfig  # noqa: Y015

@_typing.final
class GetRaceConfigsRequest(_message.Message):
    """Request for persisted race configuration schedule."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetRaceConfigsRequest: _TypeAlias = GetRaceConfigsRequest  # noqa: Y015

@_typing.final
class GetRaceConfigsResponse(_message.Message):
    """Response with persisted race configuration schedule."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACES_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    @_builtins.property
    def races(self) -> _containers.RepeatedCompositeFieldContainer[Global___RaceConfig]:
        """Entries should be sorted by start_time_utc ascending and have unique race_id."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        races: _abc.Iterable[Global___RaceConfig] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["races", b"races", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetRaceConfigsResponse: _TypeAlias = GetRaceConfigsResponse  # noqa: Y015

@_typing.final
class CreateRaceConfigRequest(_message.Message):
    """Create single race configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    @_builtins.property
    def config(self) -> Global___RaceConfigInput:
        """New race configuration payload."""

    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        config: Global___RaceConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "expected_revision", b"expected_revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateRaceConfigRequest: _TypeAlias = CreateRaceConfigRequest  # noqa: Y015

@_typing.final
class CreateRaceConfigResponse(_message.Message):
    """Created race configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    @_builtins.property
    def race(self) -> Global___RaceConfig:
        """Created race configuration entry."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race: Global___RaceConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["race", b"race"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["race", b"race", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateRaceConfigResponse: _TypeAlias = CreateRaceConfigResponse  # noqa: Y015

@_typing.final
class UpdateRaceConfigRequest(_message.Message):
    """Update single race configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    race_id: _builtins.str
    """Target race identifier to update."""
    @_builtins.property
    def config(self) -> Global___RaceConfigInput:
        """New race configuration payload.
        Active race cannot be updated.
        """

    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
        config: Global___RaceConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "expected_revision", b"expected_revision", "race_id", b"race_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateRaceConfigRequest: _TypeAlias = UpdateRaceConfigRequest  # noqa: Y015

@_typing.final
class UpdateRaceConfigResponse(_message.Message):
    """Updated race configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    @_builtins.property
    def race(self) -> Global___RaceConfig:
        """Updated race configuration entry."""

    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race: Global___RaceConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["race", b"race"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["race", b"race", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateRaceConfigResponse: _TypeAlias = UpdateRaceConfigResponse  # noqa: Y015

@_typing.final
class DeleteRaceConfigRequest(_message.Message):
    """Delete single race configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    race_id: _builtins.str
    """Target race identifier to delete.
    Active race cannot be deleted.
    """
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "race_id", b"race_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteRaceConfigRequest: _TypeAlias = DeleteRaceConfigRequest  # noqa: Y015

@_typing.final
class DeleteRaceConfigResponse(_message.Message):
    """Delete confirmation."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    RACE_ID_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    race_id: _builtins.str
    """Deleted race identifier."""
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        race_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["race_id", b"race_id", "revision", b"revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteRaceConfigResponse: _TypeAlias = DeleteRaceConfigResponse  # noqa: Y015
