"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from hackarena3.proto.race.v1 import runtime_settings_pb2 as _runtime_settings_pb2
from hackarena3.proto.weather.v1 import weather_pb2 as _weather_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _LocalTimeOfDayMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LocalTimeOfDayModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LocalTimeOfDayMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LOCAL_TIME_OF_DAY_MODE_UNSPECIFIED: _LocalTimeOfDayMode.ValueType  # 0
    LOCAL_TIME_OF_DAY_MODE_FIXED_PRESET: _LocalTimeOfDayMode.ValueType  # 1
    """Use fixed_preset from LocalTimeOfDaySettings."""
    LOCAL_TIME_OF_DAY_MODE_AUTO_BY_LOCAL_TIME: _LocalTimeOfDayMode.ValueType  # 2
    """Resolve preset from backend local system time."""

class LocalTimeOfDayMode(_LocalTimeOfDayMode, metaclass=_LocalTimeOfDayModeEnumTypeWrapper):
    """Local sandbox time-of-day resolution mode."""

LOCAL_TIME_OF_DAY_MODE_UNSPECIFIED: LocalTimeOfDayMode.ValueType  # 0
LOCAL_TIME_OF_DAY_MODE_FIXED_PRESET: LocalTimeOfDayMode.ValueType  # 1
"""Use fixed_preset from LocalTimeOfDaySettings."""
LOCAL_TIME_OF_DAY_MODE_AUTO_BY_LOCAL_TIME: LocalTimeOfDayMode.ValueType  # 2
"""Resolve preset from backend local system time."""
Global___LocalTimeOfDayMode: _TypeAlias = LocalTimeOfDayMode  # noqa: Y015

class _LocalSandboxSpawnMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LocalSandboxSpawnModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LocalSandboxSpawnMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LOCAL_SANDBOX_SPAWN_MODE_UNSPECIFIED: _LocalSandboxSpawnMode.ValueType  # 0
    LOCAL_SANDBOX_SPAWN_MODE_START_LINE: _LocalSandboxSpawnMode.ValueType  # 1
    """Spawn at start-line position."""
    LOCAL_SANDBOX_SPAWN_MODE_RANDOM_ON_TRACK: _LocalSandboxSpawnMode.ValueType  # 2
    """Spawn at random point on track."""
    LOCAL_SANDBOX_SPAWN_MODE_IN_PIT: _LocalSandboxSpawnMode.ValueType  # 3
    """Spawn inside pit area."""
    LOCAL_SANDBOX_SPAWN_MODE_RANDOM_START_SLOT: _LocalSandboxSpawnMode.ValueType  # 4
    """Spawn at random start slot (from predefined start-grid slots)."""

class LocalSandboxSpawnMode(_LocalSandboxSpawnMode, metaclass=_LocalSandboxSpawnModeEnumTypeWrapper):
    """Local sandbox spawn mode used by local backend sessions."""

LOCAL_SANDBOX_SPAWN_MODE_UNSPECIFIED: LocalSandboxSpawnMode.ValueType  # 0
LOCAL_SANDBOX_SPAWN_MODE_START_LINE: LocalSandboxSpawnMode.ValueType  # 1
"""Spawn at start-line position."""
LOCAL_SANDBOX_SPAWN_MODE_RANDOM_ON_TRACK: LocalSandboxSpawnMode.ValueType  # 2
"""Spawn at random point on track."""
LOCAL_SANDBOX_SPAWN_MODE_IN_PIT: LocalSandboxSpawnMode.ValueType  # 3
"""Spawn inside pit area."""
LOCAL_SANDBOX_SPAWN_MODE_RANDOM_START_SLOT: LocalSandboxSpawnMode.ValueType  # 4
"""Spawn at random start slot (from predefined start-grid slots)."""
Global___LocalSandboxSpawnMode: _TypeAlias = LocalSandboxSpawnMode  # noqa: Y015

@_typing.final
class LocalTimeOfDaySettings(_message.Message):
    """Local sandbox time-of-day settings."""

    DESCRIPTOR: _descriptor.Descriptor

    MODE_FIELD_NUMBER: _builtins.int
    FIXED_PRESET_FIELD_NUMBER: _builtins.int
    mode: Global___LocalTimeOfDayMode.ValueType
    fixed_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType
    """Used when mode is LOCAL_TIME_OF_DAY_MODE_FIXED_PRESET."""
    def __init__(
        self,
        *,
        mode: Global___LocalTimeOfDayMode.ValueType = ...,
        fixed_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fixed_preset", b"fixed_preset", "mode", b"mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalTimeOfDaySettings: _TypeAlias = LocalTimeOfDaySettings  # noqa: Y015

@_typing.final
class LocalWeatherSettings(_message.Message):
    """Local sandbox weather settings."""

    DESCRIPTOR: _descriptor.Descriptor

    WEATHER_TYPE_FIELD_NUMBER: _builtins.int
    TEMPERATURE_C_FIELD_NUMBER: _builtins.int
    weather_type: _weather_pb2.WeatherType.ValueType
    temperature_c: _builtins.int
    """Air temperature in Celsius degrees."""
    def __init__(
        self,
        *,
        weather_type: _weather_pb2.WeatherType.ValueType = ...,
        temperature_c: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["temperature_c", b"temperature_c", "weather_type", b"weather_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalWeatherSettings: _TypeAlias = LocalWeatherSettings  # noqa: Y015

@_typing.final
class LocalSandboxConfigInput(_message.Message):
    """Local sandbox configuration payload."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_NAME_FIELD_NUMBER: _builtins.int
    MAP_ID_FIELD_NUMBER: _builtins.int
    TIME_OF_DAY_FIELD_NUMBER: _builtins.int
    GHOST_MODE_FIELD_NUMBER: _builtins.int
    WEATHER_FIELD_NUMBER: _builtins.int
    SPAWN_MODE_FIELD_NUMBER: _builtins.int
    sandbox_name: _builtins.str
    """Human-readable sandbox name shown in frontend."""
    map_id: _builtins.str
    """Track/map identifier used by sandbox simulation."""
    spawn_mode: Global___LocalSandboxSpawnMode.ValueType
    @_builtins.property
    def time_of_day(self) -> Global___LocalTimeOfDaySettings: ...
    @_builtins.property
    def ghost_mode(self) -> _runtime_settings_pb2.GhostModeSettings: ...
    @_builtins.property
    def weather(self) -> Global___LocalWeatherSettings: ...
    def __init__(
        self,
        *,
        sandbox_name: _builtins.str = ...,
        map_id: _builtins.str = ...,
        time_of_day: Global___LocalTimeOfDaySettings | None = ...,
        ghost_mode: _runtime_settings_pb2.GhostModeSettings | None = ...,
        weather: Global___LocalWeatherSettings | None = ...,
        spawn_mode: Global___LocalSandboxSpawnMode.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ghost_mode", b"ghost_mode", "time_of_day", b"time_of_day", "weather", b"weather"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ghost_mode", b"ghost_mode", "map_id", b"map_id", "sandbox_name", b"sandbox_name", "spawn_mode", b"spawn_mode", "time_of_day", b"time_of_day", "weather", b"weather"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalSandboxConfigInput: _TypeAlias = LocalSandboxConfigInput  # noqa: Y015

@_typing.final
class LocalSandboxConfig(_message.Message):
    """Persisted local sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    sandbox_id: _builtins.str
    """Stable sandbox identifier."""
    @_builtins.property
    def config(self) -> Global___LocalSandboxConfigInput: ...
    def __init__(
        self,
        *,
        sandbox_id: _builtins.str = ...,
        config: Global___LocalSandboxConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalSandboxConfig: _TypeAlias = LocalSandboxConfig  # noqa: Y015

@_typing.final
class LocalActiveSandboxRuntimeInfo(_message.Message):
    """Active local sandbox runtime details."""

    DESCRIPTOR: _descriptor.Descriptor

    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    SANDBOX_NAME_FIELD_NUMBER: _builtins.int
    MAP_ID_FIELD_NUMBER: _builtins.int
    ACTIVE_TIME_OF_DAY_PRESET_FIELD_NUMBER: _builtins.int
    TIME_OF_DAY_FIELD_NUMBER: _builtins.int
    GHOST_MODE_FIELD_NUMBER: _builtins.int
    WEATHER_FIELD_NUMBER: _builtins.int
    SPAWN_MODE_FIELD_NUMBER: _builtins.int
    STARTED_AT_UTC_FIELD_NUMBER: _builtins.int
    ACTIVE_PLAYER_COUNT_FIELD_NUMBER: _builtins.int
    sandbox_id: _builtins.str
    sandbox_name: _builtins.str
    map_id: _builtins.str
    active_time_of_day_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType
    """Currently resolved in-session time-of-day preset."""
    spawn_mode: Global___LocalSandboxSpawnMode.ValueType
    active_player_count: _builtins.int
    @_builtins.property
    def time_of_day(self) -> Global___LocalTimeOfDaySettings: ...
    @_builtins.property
    def ghost_mode(self) -> _runtime_settings_pb2.GhostModeSettings: ...
    @_builtins.property
    def weather(self) -> Global___LocalWeatherSettings: ...
    @_builtins.property
    def started_at_utc(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        sandbox_id: _builtins.str = ...,
        sandbox_name: _builtins.str = ...,
        map_id: _builtins.str = ...,
        active_time_of_day_preset: _runtime_settings_pb2.RuntimeTimeOfDayPreset.ValueType = ...,
        time_of_day: Global___LocalTimeOfDaySettings | None = ...,
        ghost_mode: _runtime_settings_pb2.GhostModeSettings | None = ...,
        weather: Global___LocalWeatherSettings | None = ...,
        spawn_mode: Global___LocalSandboxSpawnMode.ValueType = ...,
        started_at_utc: _timestamp_pb2.Timestamp | None = ...,
        active_player_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ghost_mode", b"ghost_mode", "started_at_utc", b"started_at_utc", "time_of_day", b"time_of_day", "weather", b"weather"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_player_count", b"active_player_count", "active_time_of_day_preset", b"active_time_of_day_preset", "ghost_mode", b"ghost_mode", "map_id", b"map_id", "sandbox_id", b"sandbox_id", "sandbox_name", b"sandbox_name", "spawn_mode", b"spawn_mode", "started_at_utc", b"started_at_utc", "time_of_day", b"time_of_day", "weather", b"weather"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalActiveSandboxRuntimeInfo: _TypeAlias = LocalActiveSandboxRuntimeInfo  # noqa: Y015

@_typing.final
class LocalRuntimeState(_message.Message):
    """Local runtime state snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SERVER_TIME_UTC_FIELD_NUMBER: _builtins.int
    ACTIVE_SANDBOXES_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    @_builtins.property
    def server_time_utc(self) -> _timestamp_pb2.Timestamp:
        """Server UTC timestamp."""

    @_builtins.property
    def active_sandboxes(self) -> _containers.RepeatedCompositeFieldContainer[Global___LocalActiveSandboxRuntimeInfo]: ...
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        server_time_utc: _timestamp_pb2.Timestamp | None = ...,
        active_sandboxes: _abc.Iterable[Global___LocalActiveSandboxRuntimeInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["server_time_utc", b"server_time_utc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_sandboxes", b"active_sandboxes", "revision", b"revision", "server_time_utc", b"server_time_utc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LocalRuntimeState: _TypeAlias = LocalRuntimeState  # noqa: Y015

@_typing.final
class GetLocalSandboxConfigsRequest(_message.Message):
    """Request for persisted local sandbox configuration list."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetLocalSandboxConfigsRequest: _TypeAlias = GetLocalSandboxConfigsRequest  # noqa: Y015

@_typing.final
class GetLocalSandboxConfigsResponse(_message.Message):
    """Response with persisted local sandbox configuration list."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOXES_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    @_builtins.property
    def sandboxes(self) -> _containers.RepeatedCompositeFieldContainer[Global___LocalSandboxConfig]: ...
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandboxes: _abc.Iterable[Global___LocalSandboxConfig] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandboxes", b"sandboxes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetLocalSandboxConfigsResponse: _TypeAlias = GetLocalSandboxConfigsResponse  # noqa: Y015

@_typing.final
class CreateLocalSandboxConfigRequest(_message.Message):
    """Create single local sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    @_builtins.property
    def config(self) -> Global___LocalSandboxConfigInput: ...
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        config: Global___LocalSandboxConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "expected_revision", b"expected_revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateLocalSandboxConfigRequest: _TypeAlias = CreateLocalSandboxConfigRequest  # noqa: Y015

@_typing.final
class CreateLocalSandboxConfigResponse(_message.Message):
    """Created local sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    @_builtins.property
    def sandbox(self) -> Global___LocalSandboxConfig: ...
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox: Global___LocalSandboxConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["sandbox", b"sandbox"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandbox", b"sandbox"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CreateLocalSandboxConfigResponse: _TypeAlias = CreateLocalSandboxConfigResponse  # noqa: Y015

@_typing.final
class UpdateLocalSandboxConfigRequest(_message.Message):
    """Update single local sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    sandbox_id: _builtins.str
    @_builtins.property
    def config(self) -> Global___LocalSandboxConfigInput:
        """Active sandbox cannot be updated with full config replacement."""

    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        config: Global___LocalSandboxConfigInput | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateLocalSandboxConfigRequest: _TypeAlias = UpdateLocalSandboxConfigRequest  # noqa: Y015

@_typing.final
class UpdateLocalSandboxConfigResponse(_message.Message):
    """Updated local sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    @_builtins.property
    def sandbox(self) -> Global___LocalSandboxConfig: ...
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox: Global___LocalSandboxConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["sandbox", b"sandbox"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandbox", b"sandbox"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateLocalSandboxConfigResponse: _TypeAlias = UpdateLocalSandboxConfigResponse  # noqa: Y015

@_typing.final
class DeleteLocalSandboxConfigRequest(_message.Message):
    """Delete single local sandbox configuration entry."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    sandbox_id: _builtins.str
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteLocalSandboxConfigRequest: _TypeAlias = DeleteLocalSandboxConfigRequest  # noqa: Y015

@_typing.final
class DeleteLocalSandboxConfigResponse(_message.Message):
    """Delete local sandbox configuration confirmation."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    sandbox_id: _builtins.str
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DeleteLocalSandboxConfigResponse: _TypeAlias = DeleteLocalSandboxConfigResponse  # noqa: Y015

@_typing.final
class UpdateLocalSandboxTimeOfDayRequest(_message.Message):
    """Update local sandbox time-of-day settings."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    TIME_OF_DAY_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    sandbox_id: _builtins.str
    @_builtins.property
    def time_of_day(self) -> Global___LocalTimeOfDaySettings: ...
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        time_of_day: Global___LocalTimeOfDaySettings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time_of_day", b"time_of_day"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id", "time_of_day", b"time_of_day"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateLocalSandboxTimeOfDayRequest: _TypeAlias = UpdateLocalSandboxTimeOfDayRequest  # noqa: Y015

@_typing.final
class UpdateLocalSandboxTimeOfDayResponse(_message.Message):
    """Time-of-day settings update response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    TIME_OF_DAY_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    sandbox_id: _builtins.str
    @_builtins.property
    def time_of_day(self) -> Global___LocalTimeOfDaySettings: ...
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        time_of_day: Global___LocalTimeOfDaySettings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time_of_day", b"time_of_day"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandbox_id", b"sandbox_id", "time_of_day", b"time_of_day"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateLocalSandboxTimeOfDayResponse: _TypeAlias = UpdateLocalSandboxTimeOfDayResponse  # noqa: Y015

@_typing.final
class UpdateLocalSandboxWeatherRequest(_message.Message):
    """Update local sandbox weather settings."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    WEATHER_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    sandbox_id: _builtins.str
    @_builtins.property
    def weather(self) -> Global___LocalWeatherSettings: ...
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        weather: Global___LocalWeatherSettings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["weather", b"weather"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id", "weather", b"weather"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateLocalSandboxWeatherRequest: _TypeAlias = UpdateLocalSandboxWeatherRequest  # noqa: Y015

@_typing.final
class UpdateLocalSandboxWeatherResponse(_message.Message):
    """Weather settings update response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    WEATHER_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    sandbox_id: _builtins.str
    @_builtins.property
    def weather(self) -> Global___LocalWeatherSettings: ...
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        weather: Global___LocalWeatherSettings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["weather", b"weather"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandbox_id", b"sandbox_id", "weather", b"weather"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateLocalSandboxWeatherResponse: _TypeAlias = UpdateLocalSandboxWeatherResponse  # noqa: Y015

@_typing.final
class UpdateLocalSandboxSpawnModeRequest(_message.Message):
    """Update local sandbox spawn mode."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    SPAWN_MODE_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current config revision, otherwise request is rejected."""
    sandbox_id: _builtins.str
    spawn_mode: Global___LocalSandboxSpawnMode.ValueType
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        spawn_mode: Global___LocalSandboxSpawnMode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id", "spawn_mode", b"spawn_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateLocalSandboxSpawnModeRequest: _TypeAlias = UpdateLocalSandboxSpawnModeRequest  # noqa: Y015

@_typing.final
class UpdateLocalSandboxSpawnModeResponse(_message.Message):
    """Spawn mode update response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    SPAWN_MODE_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic config revision used for optimistic concurrency."""
    sandbox_id: _builtins.str
    spawn_mode: Global___LocalSandboxSpawnMode.ValueType
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        sandbox_id: _builtins.str = ...,
        spawn_mode: Global___LocalSandboxSpawnMode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision", b"revision", "sandbox_id", b"sandbox_id", "spawn_mode", b"spawn_mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UpdateLocalSandboxSpawnModeResponse: _TypeAlias = UpdateLocalSandboxSpawnModeResponse  # noqa: Y015

@_typing.final
class SetLocalSandboxActivationRequest(_message.Message):
    """Immediate local sandbox activation/deactivation request."""

    DESCRIPTOR: _descriptor.Descriptor

    EXPECTED_REVISION_FIELD_NUMBER: _builtins.int
    ACTIVATE_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    expected_revision: _builtins.int
    """Must match current runtime revision, otherwise request is rejected."""
    activate: _builtins.bool
    """true = activate target sandbox immediately, false = deactivate immediately."""
    sandbox_id: _builtins.str
    def __init__(
        self,
        *,
        expected_revision: _builtins.int = ...,
        activate: _builtins.bool = ...,
        sandbox_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activate", b"activate", "expected_revision", b"expected_revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetLocalSandboxActivationRequest: _TypeAlias = SetLocalSandboxActivationRequest  # noqa: Y015

@_typing.final
class SetLocalSandboxActivationResponse(_message.Message):
    """Immediate local sandbox activation/deactivation response."""

    DESCRIPTOR: _descriptor.Descriptor

    REVISION_FIELD_NUMBER: _builtins.int
    ACTIVATE_FIELD_NUMBER: _builtins.int
    SANDBOX_ID_FIELD_NUMBER: _builtins.int
    revision: _builtins.int
    """Monotonic runtime revision used for optimistic concurrency."""
    activate: _builtins.bool
    sandbox_id: _builtins.str
    def __init__(
        self,
        *,
        revision: _builtins.int = ...,
        activate: _builtins.bool = ...,
        sandbox_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activate", b"activate", "revision", b"revision", "sandbox_id", b"sandbox_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetLocalSandboxActivationResponse: _TypeAlias = SetLocalSandboxActivationResponse  # noqa: Y015

@_typing.final
class GetLocalRuntimeStateRequest(_message.Message):
    """Request current local runtime state."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetLocalRuntimeStateRequest: _TypeAlias = GetLocalRuntimeStateRequest  # noqa: Y015

@_typing.final
class GetLocalRuntimeStateResponse(_message.Message):
    """Response with current local runtime state snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def state(self) -> Global___LocalRuntimeState: ...
    def __init__(
        self,
        *,
        state: Global___LocalRuntimeState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetLocalRuntimeStateResponse: _TypeAlias = GetLocalRuntimeStateResponse  # noqa: Y015

@_typing.final
class StreamLocalRuntimeStateRequest(_message.Message):
    """Stream request for local runtime state updates."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StreamLocalRuntimeStateRequest: _TypeAlias = StreamLocalRuntimeStateRequest  # noqa: Y015

@_typing.final
class StreamLocalRuntimeStateResponse(_message.Message):
    """Stream response with local runtime state snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def state(self) -> Global___LocalRuntimeState: ...
    def __init__(
        self,
        *,
        state: Global___LocalRuntimeState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StreamLocalRuntimeStateResponse: _TypeAlias = StreamLocalRuntimeStateResponse  # noqa: Y015
