"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from hackarena3.proto.race.v1 import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _GhostModePhase:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _GhostModePhaseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GhostModePhase.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GHOST_MODE_PHASE_UNSPECIFIED: _GhostModePhase.ValueType  # 0
    GHOST_MODE_PHASE_INACTIVE: _GhostModePhase.ValueType  # 1
    """Ghost mode is disabled for this vehicle and collisions are enabled."""
    GHOST_MODE_PHASE_ACTIVE: _GhostModePhase.ValueType  # 2
    """Ghost mode is enabled for this vehicle and collisions are disabled."""
    GHOST_MODE_PHASE_PENDING_EXIT: _GhostModePhase.ValueType  # 3
    """Ghost mode is still active, but exit countdown is currently running."""

class GhostModePhase(_GhostModePhase, metaclass=_GhostModePhaseEnumTypeWrapper):
    """High-level ghost mode phase used by clients for UX state rendering."""

GHOST_MODE_PHASE_UNSPECIFIED: GhostModePhase.ValueType  # 0
GHOST_MODE_PHASE_INACTIVE: GhostModePhase.ValueType  # 1
"""Ghost mode is disabled for this vehicle and collisions are enabled."""
GHOST_MODE_PHASE_ACTIVE: GhostModePhase.ValueType  # 2
"""Ghost mode is enabled for this vehicle and collisions are disabled."""
GHOST_MODE_PHASE_PENDING_EXIT: GhostModePhase.ValueType  # 3
"""Ghost mode is still active, but exit countdown is currently running."""
Global___GhostModePhase: _TypeAlias = GhostModePhase  # noqa: Y015

class _GhostModeBlocker:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _GhostModeBlockerEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GhostModeBlocker.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GHOST_MODE_BLOCKER_UNSPECIFIED: _GhostModeBlocker.ValueType  # 0
    GHOST_MODE_BLOCKER_LAPS_REQUIREMENT_NOT_MET: _GhostModeBlocker.ValueType  # 1
    """completed_laps is below GhostModeSettings.until_completed_laps."""
    GHOST_MODE_BLOCKER_EXIT_SPEED_NOT_MET: _GhostModeBlocker.ValueType  # 2
    """Current speed is not above GhostModeSettings.exit_speed_min_mps."""
    GHOST_MODE_BLOCKER_EXIT_DELAY_RUNNING: _GhostModeBlocker.ValueType  # 3
    """Exit speed condition is met, but exit delay is still counting down."""
    GHOST_MODE_BLOCKER_VEHICLE_OVERLAP_ACTIVE: _GhostModeBlocker.ValueType  # 4
    """Vehicle overlap is currently present and prevents ghost mode exit.
    Evaluated per vehicle, not as a single global race flag.
    """
    GHOST_MODE_BLOCKER_OVERLAP_EXIT_DELAY_RUNNING: _GhostModeBlocker.ValueType  # 5
    """Overlap is cleared for this vehicle, but no-overlap exit delay is still counting down.
    Evaluated per vehicle, not as a single global race flag.
    """
    GHOST_MODE_BLOCKER_IN_PIT: _GhostModeBlocker.ValueType  # 6
    """Vehicle is currently in pit area."""

class GhostModeBlocker(_GhostModeBlocker, metaclass=_GhostModeBlockerEnumTypeWrapper):
    """Active conditions that currently keep or can keep a vehicle in ghost mode."""

GHOST_MODE_BLOCKER_UNSPECIFIED: GhostModeBlocker.ValueType  # 0
GHOST_MODE_BLOCKER_LAPS_REQUIREMENT_NOT_MET: GhostModeBlocker.ValueType  # 1
"""completed_laps is below GhostModeSettings.until_completed_laps."""
GHOST_MODE_BLOCKER_EXIT_SPEED_NOT_MET: GhostModeBlocker.ValueType  # 2
"""Current speed is not above GhostModeSettings.exit_speed_min_mps."""
GHOST_MODE_BLOCKER_EXIT_DELAY_RUNNING: GhostModeBlocker.ValueType  # 3
"""Exit speed condition is met, but exit delay is still counting down."""
GHOST_MODE_BLOCKER_VEHICLE_OVERLAP_ACTIVE: GhostModeBlocker.ValueType  # 4
"""Vehicle overlap is currently present and prevents ghost mode exit.
Evaluated per vehicle, not as a single global race flag.
"""
GHOST_MODE_BLOCKER_OVERLAP_EXIT_DELAY_RUNNING: GhostModeBlocker.ValueType  # 5
"""Overlap is cleared for this vehicle, but no-overlap exit delay is still counting down.
Evaluated per vehicle, not as a single global race flag.
"""
GHOST_MODE_BLOCKER_IN_PIT: GhostModeBlocker.ValueType  # 6
"""Vehicle is currently in pit area."""
Global___GhostModeBlocker: _TypeAlias = GhostModeBlocker  # noqa: Y015

class _PitstopZoneFlag:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PitstopZoneFlagEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PitstopZoneFlag.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PITSTOP_ZONE_FLAG_UNSPECIFIED: _PitstopZoneFlag.ValueType  # 0
    PITSTOP_ZONE_FLAG_ENTER: _PitstopZoneFlag.ValueType  # 1
    """Bit 0 (1): vehicle overlaps pitstop enter zone."""
    PITSTOP_ZONE_FLAG_FIX: _PitstopZoneFlag.ValueType  # 2
    """Bit 1 (2): vehicle overlaps pitstop fix zone."""
    PITSTOP_ZONE_FLAG_EXIT: _PitstopZoneFlag.ValueType  # 4
    """Bit 2 (4): vehicle overlaps pitstop exit zone."""

class PitstopZoneFlag(_PitstopZoneFlag, metaclass=_PitstopZoneFlagEnumTypeWrapper):
    """Pitstop zones encoded as bit flags for pitstop_zone_flags."""

PITSTOP_ZONE_FLAG_UNSPECIFIED: PitstopZoneFlag.ValueType  # 0
PITSTOP_ZONE_FLAG_ENTER: PitstopZoneFlag.ValueType  # 1
"""Bit 0 (1): vehicle overlaps pitstop enter zone."""
PITSTOP_ZONE_FLAG_FIX: PitstopZoneFlag.ValueType  # 2
"""Bit 1 (2): vehicle overlaps pitstop fix zone."""
PITSTOP_ZONE_FLAG_EXIT: PitstopZoneFlag.ValueType  # 4
"""Bit 2 (4): vehicle overlaps pitstop exit zone."""
Global___PitstopZoneFlag: _TypeAlias = PitstopZoneFlag  # noqa: Y015

class _TireType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TireTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TireType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TIRE_TYPE_UNSPECIFIED: _TireType.ValueType  # 0
    TIRE_TYPE_HARD: _TireType.ValueType  # 1
    TIRE_TYPE_SOFT: _TireType.ValueType  # 2
    TIRE_TYPE_WET: _TireType.ValueType  # 3

class TireType(_TireType, metaclass=_TireTypeEnumTypeWrapper):
    """Installed tire compound for a vehicle."""

TIRE_TYPE_UNSPECIFIED: TireType.ValueType  # 0
TIRE_TYPE_HARD: TireType.ValueType  # 1
TIRE_TYPE_SOFT: TireType.ValueType  # 2
TIRE_TYPE_WET: TireType.ValueType  # 3
Global___TireType: _TypeAlias = TireType  # noqa: Y015

@_typing.final
class TireWearPerWheel(_message.Message):
    """Per-wheel tire wear values normalized to range [0.0, 1.0]."""

    DESCRIPTOR: _descriptor.Descriptor

    FRONT_LEFT_FIELD_NUMBER: _builtins.int
    FRONT_RIGHT_FIELD_NUMBER: _builtins.int
    REAR_LEFT_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_FIELD_NUMBER: _builtins.int
    front_left: _builtins.float
    front_right: _builtins.float
    rear_left: _builtins.float
    rear_right: _builtins.float
    def __init__(
        self,
        *,
        front_left: _builtins.float = ...,
        front_right: _builtins.float = ...,
        rear_left: _builtins.float = ...,
        rear_right: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["front_left", b"front_left", "front_right", b"front_right", "rear_left", b"rear_left", "rear_right", b"rear_right"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TireWearPerWheel: _TypeAlias = TireWearPerWheel  # noqa: Y015

@_typing.final
class TireTemperaturePerWheel(_message.Message):
    """Per-wheel tire temperature in degrees Celsius."""

    DESCRIPTOR: _descriptor.Descriptor

    FRONT_LEFT_CELSIUS_FIELD_NUMBER: _builtins.int
    FRONT_RIGHT_CELSIUS_FIELD_NUMBER: _builtins.int
    REAR_LEFT_CELSIUS_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_CELSIUS_FIELD_NUMBER: _builtins.int
    front_left_celsius: _builtins.float
    front_right_celsius: _builtins.float
    rear_left_celsius: _builtins.float
    rear_right_celsius: _builtins.float
    def __init__(
        self,
        *,
        front_left_celsius: _builtins.float = ...,
        front_right_celsius: _builtins.float = ...,
        rear_left_celsius: _builtins.float = ...,
        rear_right_celsius: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["front_left_celsius", b"front_left_celsius", "front_right_celsius", b"front_right_celsius", "rear_left_celsius", b"rear_left_celsius", "rear_right_celsius", b"rear_right_celsius"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TireTemperaturePerWheel: _TypeAlias = TireTemperaturePerWheel  # noqa: Y015

@_typing.final
class GhostModeState(_message.Message):
    """Runtime ghost mode state for a single vehicle.
    Pairwise collision rule:
    can_collide_pair(A,B) = A.can_collide_now && B.can_collide_now.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CAN_COLLIDE_NOW_FIELD_NUMBER: _builtins.int
    PHASE_FIELD_NUMBER: _builtins.int
    BLOCKERS_FIELD_NUMBER: _builtins.int
    EXIT_DELAY_REMAINING_MS_FIELD_NUMBER: _builtins.int
    can_collide_now: _builtins.bool
    """Authoritative collision flag for this vehicle.
    Clients should use this as the only gameplay truth for collision checks.
    """
    phase: Global___GhostModePhase.ValueType
    """Current high-level ghost mode phase for UX/debug.
    Do not infer collision enablement from phase; use can_collide_now.
    PENDING_EXIT remains non-collidable until transition to INACTIVE.
    """
    exit_delay_remaining_ms: _builtins.int
    """Aggregated remaining time to ghost-mode exit in milliseconds.
    Should be > 0 only when phase is PENDING_EXIT.
    """
    @_builtins.property
    def blockers(self) -> _containers.RepeatedScalarFieldContainer[Global___GhostModeBlocker.ValueType]:
        """Active blockers at current tick. May contain multiple values."""

    def __init__(
        self,
        *,
        can_collide_now: _builtins.bool = ...,
        phase: Global___GhostModePhase.ValueType = ...,
        blockers: _abc.Iterable[Global___GhostModeBlocker.ValueType] | None = ...,
        exit_delay_remaining_ms: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blockers", b"blockers", "can_collide_now", b"can_collide_now", "exit_delay_remaining_ms", b"exit_delay_remaining_ms", "phase", b"phase"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GhostModeState: _TypeAlias = GhostModeState  # noqa: Y015

@_typing.final
class CarKinematics(_message.Message):
    """Core pose data shared across views."""

    DESCRIPTOR: _descriptor.Descriptor

    POSITION_FIELD_NUMBER: _builtins.int
    ORIENTATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def position(self) -> _common_pb2.Vector3: ...
    @_builtins.property
    def orientation(self) -> _common_pb2.Quaternion: ...
    def __init__(
        self,
        *,
        position: _common_pb2.Vector3 | None = ...,
        orientation: _common_pb2.Quaternion | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["orientation", b"orientation", "position", b"position"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["orientation", b"orientation", "position", b"position"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CarKinematics: _TypeAlias = CarKinematics  # noqa: Y015

@_typing.final
class CarParticipantState(_message.Message):
    """Full car telemetry."""

    DESCRIPTOR: _descriptor.Descriptor

    LAST_APPLIED_CLIENT_SEQ_FIELD_NUMBER: _builtins.int
    SPEED_MPS_FIELD_NUMBER: _builtins.int
    ENGINE_RPM_FIELD_NUMBER: _builtins.int
    GEAR_FIELD_NUMBER: _builtins.int
    THROTTLE_APPLIED_FIELD_NUMBER: _builtins.int
    BRAKE_APPLIED_FIELD_NUMBER: _builtins.int
    GHOST_MODE_FIELD_NUMBER: _builtins.int
    PITSTOP_ZONE_FLAGS_FIELD_NUMBER: _builtins.int
    WHEELS_IN_PITSTOP_FIELD_NUMBER: _builtins.int
    TIRE_TYPE_FIELD_NUMBER: _builtins.int
    TIRE_WEAR_FIELD_NUMBER: _builtins.int
    TIRE_TEMPERATURE_CELSIUS_FIELD_NUMBER: _builtins.int
    last_applied_client_seq: _builtins.int
    speed_mps: _builtins.float
    engine_rpm: _builtins.float
    gear: _builtins.int
    throttle_applied: _builtins.float
    brake_applied: _builtins.float
    pitstop_zone_flags: _builtins.int
    """Active pitstop zones encoded as PitstopZoneFlag bitmask.
    Bits:
    - ENTER = 1
    - FIX = 2
    - EXIT = 4
    Multiple flags may be set at the same time.
    """
    wheels_in_pitstop: _builtins.int
    """Number of wheels currently inside pitstop zones (range 0..4)."""
    tire_type: Global___TireType.ValueType
    """Installed tire compound."""
    @_builtins.property
    def ghost_mode(self) -> Global___GhostModeState:
        """Runtime ghost mode state for this vehicle."""

    @_builtins.property
    def tire_wear(self) -> Global___TireWearPerWheel:
        """Tire wear per wheel, normalized to [0.0, 1.0]."""

    @_builtins.property
    def tire_temperature_celsius(self) -> Global___TireTemperaturePerWheel:
        """Tire temperature per wheel in degrees Celsius."""

    def __init__(
        self,
        *,
        last_applied_client_seq: _builtins.int = ...,
        speed_mps: _builtins.float = ...,
        engine_rpm: _builtins.float = ...,
        gear: _builtins.int = ...,
        throttle_applied: _builtins.float = ...,
        brake_applied: _builtins.float = ...,
        ghost_mode: Global___GhostModeState | None = ...,
        pitstop_zone_flags: _builtins.int = ...,
        wheels_in_pitstop: _builtins.int = ...,
        tire_type: Global___TireType.ValueType = ...,
        tire_wear: Global___TireWearPerWheel | None = ...,
        tire_temperature_celsius: Global___TireTemperaturePerWheel | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ghost_mode", b"ghost_mode", "tire_temperature_celsius", b"tire_temperature_celsius", "tire_wear", b"tire_wear"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["brake_applied", b"brake_applied", "engine_rpm", b"engine_rpm", "gear", b"gear", "ghost_mode", b"ghost_mode", "last_applied_client_seq", b"last_applied_client_seq", "pitstop_zone_flags", b"pitstop_zone_flags", "speed_mps", b"speed_mps", "throttle_applied", b"throttle_applied", "tire_temperature_celsius", b"tire_temperature_celsius", "tire_type", b"tire_type", "tire_wear", b"tire_wear", "wheels_in_pitstop", b"wheels_in_pitstop"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CarParticipantState: _TypeAlias = CarParticipantState  # noqa: Y015

@_typing.final
class CarRenderState(_message.Message):
    """Minimal data needed for rendering visuals."""

    DESCRIPTOR: _descriptor.Descriptor

    WHEEL_SPEEDS_FIELD_NUMBER: _builtins.int
    FRONT_LEFT_WHEEL_ORIENTATION_RAD_FIELD_NUMBER: _builtins.int
    FRONT_RIGHT_WHEEL_ORIENTATION_RAD_FIELD_NUMBER: _builtins.int
    front_left_wheel_orientation_rad: _builtins.float
    """Front-left wheel orientation in radians."""
    front_right_wheel_orientation_rad: _builtins.float
    """Front-right wheel orientation in radians."""
    @_builtins.property
    def wheel_speeds(self) -> _common_pb2.WheelSpeeds: ...
    def __init__(
        self,
        *,
        wheel_speeds: _common_pb2.WheelSpeeds | None = ...,
        front_left_wheel_orientation_rad: _builtins.float = ...,
        front_right_wheel_orientation_rad: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["wheel_speeds", b"wheel_speeds"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["front_left_wheel_orientation_rad", b"front_left_wheel_orientation_rad", "front_right_wheel_orientation_rad", b"front_right_wheel_orientation_rad", "wheel_speeds", b"wheel_speeds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CarRenderState: _TypeAlias = CarRenderState  # noqa: Y015

@_typing.final
class FrontendCarFullState(_message.Message):
    """Full state for frontend spectator mode."""

    DESCRIPTOR: _descriptor.Descriptor

    CAR_ID_FIELD_NUMBER: _builtins.int
    KINEMATICS_FIELD_NUMBER: _builtins.int
    TELEMETRY_FIELD_NUMBER: _builtins.int
    RENDER_FIELD_NUMBER: _builtins.int
    car_id: _builtins.int
    @_builtins.property
    def kinematics(self) -> Global___CarKinematics: ...
    @_builtins.property
    def telemetry(self) -> Global___CarParticipantState: ...
    @_builtins.property
    def render(self) -> Global___CarRenderState: ...
    def __init__(
        self,
        *,
        car_id: _builtins.int = ...,
        kinematics: Global___CarKinematics | None = ...,
        telemetry: Global___CarParticipantState | None = ...,
        render: Global___CarRenderState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["kinematics", b"kinematics", "render", b"render", "telemetry", b"telemetry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["car_id", b"car_id", "kinematics", b"kinematics", "render", b"render", "telemetry", b"telemetry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FrontendCarFullState: _TypeAlias = FrontendCarFullState  # noqa: Y015

@_typing.final
class FrontendSpectatorDebugInfo(_message.Message):
    """Optional debug-only telemetry for spectator snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    ENGINE_RACE_ELAPSED_SEC_FIELD_NUMBER: _builtins.int
    engine_race_elapsed_sec: _builtins.float
    """Engine-reported race elapsed time in seconds from boink_get_race_duration().
    Uses engine Real precision (float); best-effort and non-authoritative for UI/gameplay logic.
    """
    def __init__(
        self,
        *,
        engine_race_elapsed_sec: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["engine_race_elapsed_sec", b"engine_race_elapsed_sec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FrontendSpectatorDebugInfo: _TypeAlias = FrontendSpectatorDebugInfo  # noqa: Y015

@_typing.final
class FrontendSpectatorSnapshot(_message.Message):
    """Spectator feed: full state for all cars."""

    DESCRIPTOR: _descriptor.Descriptor

    TICK_FIELD_NUMBER: _builtins.int
    SERVER_TIME_MS_FIELD_NUMBER: _builtins.int
    CARS_FIELD_NUMBER: _builtins.int
    DEBUG_FIELD_NUMBER: _builtins.int
    tick: _builtins.int
    server_time_ms: _builtins.int
    """Milliseconds since Unix epoch (UTC)."""
    @_builtins.property
    def cars(self) -> _containers.RepeatedCompositeFieldContainer[Global___FrontendCarFullState]: ...
    @_builtins.property
    def debug(self) -> Global___FrontendSpectatorDebugInfo:
        """Optional debug-only telemetry block."""

    def __init__(
        self,
        *,
        tick: _builtins.int = ...,
        server_time_ms: _builtins.int = ...,
        cars: _abc.Iterable[Global___FrontendCarFullState] | None = ...,
        debug: Global___FrontendSpectatorDebugInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["debug", b"debug"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cars", b"cars", "debug", b"debug", "server_time_ms", b"server_time_ms", "tick", b"tick"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___FrontendSpectatorSnapshot: _TypeAlias = FrontendSpectatorSnapshot  # noqa: Y015

@_typing.final
class ParticipantSelfState(_message.Message):
    """Participant view of own car (full driver detail)."""

    DESCRIPTOR: _descriptor.Descriptor

    CAR_ID_FIELD_NUMBER: _builtins.int
    KINEMATICS_FIELD_NUMBER: _builtins.int
    TELEMETRY_FIELD_NUMBER: _builtins.int
    car_id: _builtins.int
    @_builtins.property
    def kinematics(self) -> Global___CarKinematics: ...
    @_builtins.property
    def telemetry(self) -> Global___CarParticipantState: ...
    def __init__(
        self,
        *,
        car_id: _builtins.int = ...,
        kinematics: Global___CarKinematics | None = ...,
        telemetry: Global___CarParticipantState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["kinematics", b"kinematics", "telemetry", b"telemetry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["car_id", b"car_id", "kinematics", b"kinematics", "telemetry", b"telemetry"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ParticipantSelfState: _TypeAlias = ParticipantSelfState  # noqa: Y015

@_typing.final
class ParticipantOpponentState(_message.Message):
    """Participant view of opponent cars."""

    DESCRIPTOR: _descriptor.Descriptor

    CAR_ID_FIELD_NUMBER: _builtins.int
    KINEMATICS_FIELD_NUMBER: _builtins.int
    GHOST_MODE_FIELD_NUMBER: _builtins.int
    car_id: _builtins.int
    @_builtins.property
    def kinematics(self) -> Global___CarKinematics: ...
    @_builtins.property
    def ghost_mode(self) -> Global___GhostModeState:
        """Runtime ghost mode state for this opponent vehicle."""

    def __init__(
        self,
        *,
        car_id: _builtins.int = ...,
        kinematics: Global___CarKinematics | None = ...,
        ghost_mode: Global___GhostModeState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["ghost_mode", b"ghost_mode", "kinematics", b"kinematics"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["car_id", b"car_id", "ghost_mode", b"ghost_mode", "kinematics", b"kinematics"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ParticipantOpponentState: _TypeAlias = ParticipantOpponentState  # noqa: Y015

@_typing.final
class ParticipantSnapshot(_message.Message):
    """Participant snapshot (self + opponents)."""

    DESCRIPTOR: _descriptor.Descriptor

    TICK_FIELD_NUMBER: _builtins.int
    SERVER_TIME_MS_FIELD_NUMBER: _builtins.int
    SELF_FIELD_NUMBER: _builtins.int
    OPPONENTS_FIELD_NUMBER: _builtins.int
    tick: _builtins.int
    server_time_ms: _builtins.int
    """Milliseconds since Unix epoch (UTC)."""
    @_builtins.property
    def self(self) -> Global___ParticipantSelfState: ...
    @_builtins.property
    def opponents(self) -> _containers.RepeatedCompositeFieldContainer[Global___ParticipantOpponentState]: ...
    def __init__(
        self_,  # pyright: ignore[reportSelfClsParameterName]
        *,
        tick: _builtins.int = ...,
        server_time_ms: _builtins.int = ...,
        self: Global___ParticipantSelfState | None = ...,
        opponents: _abc.Iterable[Global___ParticipantOpponentState] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["self", b"self"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["opponents", b"opponents", "self", b"self", "server_time_ms", b"server_time_ms", "tick", b"tick"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ParticipantSnapshot: _TypeAlias = ParticipantSnapshot  # noqa: Y015
