"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from hackarena3.proto.race.v1 import common_pb2 as _common_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TrackData(_message.Message):
    """Static centerline geometry for one lap.
    Units are SI (meters, radians). World frame is right-handed with Y-up.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAP_ID_FIELD_NUMBER: _builtins.int
    LAP_LENGTH_M_FIELD_NUMBER: _builtins.int
    CENTERLINE_SAMPLES_FIELD_NUMBER: _builtins.int
    PITSTOP_DATA_FIELD_NUMBER: _builtins.int
    map_id: _builtins.str
    """Track identifier."""
    lap_length_m: _builtins.float
    """Full arc length of one lap along the main centerline.
    Must be > 0.
    """
    @_builtins.property
    def centerline_samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___CenterlineSample]:
        """Ordered centerline samples for one closed lap.
        Rules:
        - strictly increasing by s_m,
        - centerline_samples[0].s_m == 0,
        - for each sample: 0 <= s_m < lap_length_m,
        - closing segment wraps from last sample to first sample,
        - arc length wraps every lap: s == lap_length_m is equivalent to s == 0.
        """

    @_builtins.property
    def pitstop_data(self) -> Global___PitstopData:
        """Pitstop centerline geometry split into enter/fix/exit sections."""

    def __init__(
        self,
        *,
        map_id: _builtins.str = ...,
        lap_length_m: _builtins.float = ...,
        centerline_samples: _abc.Iterable[Global___CenterlineSample] | None = ...,
        pitstop_data: Global___PitstopData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pitstop_data", b"pitstop_data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["centerline_samples", b"centerline_samples", "lap_length_m", b"lap_length_m", "map_id", b"map_id", "pitstop_data", b"pitstop_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TrackData: _TypeAlias = TrackData  # noqa: Y015

@_typing.final
class PitstopData(_message.Message):
    """Pitstop centerline geometry split into enter/fix/exit sections."""

    DESCRIPTOR: _descriptor.Descriptor

    ENTER_CENTERLINE_SAMPLES_FIELD_NUMBER: _builtins.int
    FIX_CENTERLINE_SAMPLES_FIELD_NUMBER: _builtins.int
    EXIT_CENTERLINE_SAMPLES_FIELD_NUMBER: _builtins.int
    LENGTH_M_FIELD_NUMBER: _builtins.int
    length_m: _builtins.float
    """Total arc length of full pitstop path (enter + fix + exit), in meters."""
    @_builtins.property
    def enter_centerline_samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___CenterlineSample]: ...
    @_builtins.property
    def fix_centerline_samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___CenterlineSample]: ...
    @_builtins.property
    def exit_centerline_samples(self) -> _containers.RepeatedCompositeFieldContainer[Global___CenterlineSample]: ...
    def __init__(
        self,
        *,
        enter_centerline_samples: _abc.Iterable[Global___CenterlineSample] | None = ...,
        fix_centerline_samples: _abc.Iterable[Global___CenterlineSample] | None = ...,
        exit_centerline_samples: _abc.Iterable[Global___CenterlineSample] | None = ...,
        length_m: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enter_centerline_samples", b"enter_centerline_samples", "exit_centerline_samples", b"exit_centerline_samples", "fix_centerline_samples", b"fix_centerline_samples", "length_m", b"length_m"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PitstopData: _TypeAlias = PitstopData  # noqa: Y015

@_typing.final
class CenterlineSample(_message.Message):
    """Centerline sample with local frame and derived geometry."""

    DESCRIPTOR: _descriptor.Descriptor

    S_M_FIELD_NUMBER: _builtins.int
    POSITION_FIELD_NUMBER: _builtins.int
    TANGENT_FIELD_NUMBER: _builtins.int
    NORMAL_FIELD_NUMBER: _builtins.int
    RIGHT_FIELD_NUMBER: _builtins.int
    LEFT_WIDTH_M_FIELD_NUMBER: _builtins.int
    RIGHT_WIDTH_M_FIELD_NUMBER: _builtins.int
    CURVATURE_1PM_FIELD_NUMBER: _builtins.int
    GRADE_RAD_FIELD_NUMBER: _builtins.int
    BANK_RAD_FIELD_NUMBER: _builtins.int
    s_m: _builtins.float
    """Distance along centerline in meters in [0, lap_length_m)."""
    left_width_m: _builtins.float
    """Lateral drivable bound to track-left from centerline, measured along local right axis.
    Corridor points satisfy: position + right * d, where d in [-left_width_m, +right_width_m].
    Raw track geometry only (vehicle footprint and safety margin are not included).
    Must be >= 0.
    """
    right_width_m: _builtins.float
    """Lateral drivable bound to track-right from centerline, measured along local right axis.
    Corridor points satisfy: position + right * d, where d in [-left_width_m, +right_width_m].
    Raw track geometry only (vehicle footprint and safety margin are not included).
    Must be >= 0.
    """
    curvature_1pm: _builtins.float
    """Signed centerline curvature [1/m], approx d(heading_rad)/ds.
    Negative = left turn, positive = right turn (local track frame).
    """
    grade_rad: _builtins.float
    """Longitudinal slope angle in radians (0 = flat, positive uphill).
    Positive means elevation increases in the +s direction.
    """
    bank_rad: _builtins.float
    """Crossfall/banking angle in radians around tangent.
    Positive when the right side of the track is lower.
    """
    @_builtins.property
    def position(self) -> _common_pb2.Vector3:
        """World-space centerline position in 3D track geometry."""

    @_builtins.property
    def tangent(self) -> _common_pb2.Vector3:
        """Unit tangent vector. Points in track-forward direction (increasing s_m)."""

    @_builtins.property
    def normal(self) -> _common_pb2.Vector3:
        """Unit surface normal at centerline (track local up), not global Y-up.
        Normal orientation is continuous around the full lap (no sign flips).
        """

    @_builtins.property
    def right(self) -> _common_pb2.Vector3:
        """Unit right vector (track-right direction).
        Must satisfy: right = normalize(cross(normal, tangent)).
        tangent/normal/right are mutually orthogonal.
        """

    def __init__(
        self,
        *,
        s_m: _builtins.float = ...,
        position: _common_pb2.Vector3 | None = ...,
        tangent: _common_pb2.Vector3 | None = ...,
        normal: _common_pb2.Vector3 | None = ...,
        right: _common_pb2.Vector3 | None = ...,
        left_width_m: _builtins.float = ...,
        right_width_m: _builtins.float = ...,
        curvature_1pm: _builtins.float = ...,
        grade_rad: _builtins.float = ...,
        bank_rad: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["normal", b"normal", "position", b"position", "right", b"right", "tangent", b"tangent"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bank_rad", b"bank_rad", "curvature_1pm", b"curvature_1pm", "grade_rad", b"grade_rad", "left_width_m", b"left_width_m", "normal", b"normal", "position", b"position", "right", b"right", "right_width_m", b"right_width_m", "s_m", b"s_m", "tangent", b"tangent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CenterlineSample: _TypeAlias = CenterlineSample  # noqa: Y015

@_typing.final
class GetTrackDataRequest(_message.Message):
    """Request for static centerline geometry used by wrappers and bot clients."""

    DESCRIPTOR: _descriptor.Descriptor

    MAP_ID_FIELD_NUMBER: _builtins.int
    map_id: _builtins.str
    """Track identifier."""
    def __init__(
        self,
        *,
        map_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["map_id", b"map_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTrackDataRequest: _TypeAlias = GetTrackDataRequest  # noqa: Y015

@_typing.final
class GetTrackDataResponse(_message.Message):
    """Response with static centerline geometry."""

    DESCRIPTOR: _descriptor.Descriptor

    TRACK_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def track(self) -> Global___TrackData: ...
    def __init__(
        self,
        *,
        track: Global___TrackData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["track", b"track"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["track", b"track"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetTrackDataResponse: _TypeAlias = GetTrackDataResponse  # noqa: Y015
