# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hackarena3.proto.race.v1 import track_pb2 as race_dot_v1_dot_track__pb2


class TrackServiceStub(object):
    """API for machine-readable track geometry used by wrappers and bot clients.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrackData = channel.unary_unary(
                '/race.v1.TrackService/GetTrackData',
                request_serializer=race_dot_v1_dot_track__pb2.GetTrackDataRequest.SerializeToString,
                response_deserializer=race_dot_v1_dot_track__pb2.GetTrackDataResponse.FromString,
                _registered_method=True)


class TrackServiceServicer(object):
    """API for machine-readable track geometry used by wrappers and bot clients.
    """

    def GetTrackData(self, request, context):
        """Returns TrackData for the specified track.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrackData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrackData,
                    request_deserializer=race_dot_v1_dot_track__pb2.GetTrackDataRequest.FromString,
                    response_serializer=race_dot_v1_dot_track__pb2.GetTrackDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'race.v1.TrackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('race.v1.TrackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackService(object):
    """API for machine-readable track geometry used by wrappers and bot clients.
    """

    @staticmethod
    def GetTrackData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/race.v1.TrackService/GetTrackData',
            race_dot_v1_dot_track__pb2.GetTrackDataRequest.SerializeToString,
            race_dot_v1_dot_track__pb2.GetTrackDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
